"""Unit tests for pipeline template generators (IMP-03, IMP-04, BUILD-06, TWO-03, PIPE-08).

Tests cover:
- TestGitLfs: Git LFS .gitattributes and .gitignore generation
- TestNormalMapBake: Blender Python normal map baking script generation
- TestSpriteAtlas: SpriteAtlas and sprite animation C# script generation
- TestSpriteEditor: Sprite Editor configuration C# script generation
- TestAssetPostprocessor: AssetPostprocessor C# script generation
"""

import pytest

from veilbreakers_mcp.shared.unity_templates.pipeline_templates import (
    generate_gitlfs_config,
    generate_gitignore,
    generate_normal_map_bake_script,
    generate_sprite_atlas_script,
    generate_sprite_animation_script,
    generate_sprite_editor_config_script,
    generate_asset_postprocessor_script,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def check_brace_balance(text: str) -> bool:
    """Verify that braces are balanced throughout the string."""
    depth = 0
    for ch in text:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        if depth < 0:
            return False
    return depth == 0


# ===================================================================
# TestGitLfs (IMP-03)
# ===================================================================


class TestGitLfs:
    """Tests for generate_gitlfs_config and generate_gitignore."""

    def test_gitlfs_config_basic(self):
        result = generate_gitlfs_config()
        assert "filter=lfs" in result
        assert "*.fbx" in result
        assert "*.png" in result
        assert "*.wav" in result
        assert "*.ttf" in result
        assert "*.mp4" in result

    def test_gitlfs_config_no_asset_tracking(self):
        """Verify *.asset is NOT tracked with LFS (Unity YAML text)."""
        result = generate_gitlfs_config()
        # .asset should not appear as an LFS-tracked extension
        for line in result.splitlines():
            if "filter=lfs" in line:
                assert "*.asset" not in line, (
                    ".asset files are YAML text and should not be LFS-tracked"
                )

    def test_gitlfs_config_extra_extensions(self):
        result = generate_gitlfs_config(extra_extensions=[".custom", "dat"])
        assert "*.custom" in result
        assert "*.dat" in result
        assert "filter=lfs" in result

    def test_gitlfs_yaml_merge(self):
        result = generate_gitlfs_config(include_unity_yaml_merge=True)
        assert "merge=unityyamlmerge" in result
        assert "*.unity" in result
        assert "*.prefab" in result
        assert "*.mat" in result

    def test_gitlfs_no_yaml_merge(self):
        result = generate_gitlfs_config(include_unity_yaml_merge=False)
        assert "merge=unityyamlmerge" not in result

    def test_gitignore_basic(self):
        result = generate_gitignore()
        assert "[Ll]ibrary" in result
        assert "[Tt]emp" in result
        assert "*.csproj" in result
        assert "*.sln" in result

    def test_gitignore_extra_patterns(self):
        result = generate_gitignore(extra_patterns=["*.myext", "custom_dir/"])
        assert "*.myext" in result
        assert "custom_dir/" in result

    def test_gitlfs_header_comment(self):
        result = generate_gitlfs_config()
        assert result.startswith("# Generated by VeilBreakers")

    def test_gitlfs_all_3d_model_extensions(self):
        result = generate_gitlfs_config()
        assert "*.obj" in result
        assert "*.blend" in result

    def test_gitlfs_all_texture_extensions(self):
        result = generate_gitlfs_config()
        assert "*.psd" in result
        assert "*.tga" in result
        assert "*.tif" in result
        assert "*.exr" in result
        assert "*.hdr" in result
        assert "*.jpg" in result

    def test_gitlfs_audio_extensions(self):
        result = generate_gitlfs_config()
        assert "*.mp3" in result
        assert "*.ogg" in result

    def test_gitlfs_unity_binary_extensions(self):
        result = generate_gitlfs_config()
        assert "*.cubemap" in result
        assert "*.unitypackage" in result

    def test_gitignore_unity_directories(self):
        result = generate_gitignore()
        assert "[Oo]bj" in result
        assert "[Bb]uild" in result
        assert "[Bb]uilds" in result
        assert "[Ll]ogs" in result
        assert "[Uu]ser[Ss]ettings" in result
        assert "[Mm]emoryCaptures" in result
        assert "[Rr]ecordings" in result

    def test_gitignore_ide_artifacts(self):
        result = generate_gitignore()
        assert "*.suo" in result
        assert "*.user" in result
        assert "*.pdb" in result
        assert "*.opendb" in result
        assert "*.VC.db" in result

    def test_gitignore_os_specific(self):
        result = generate_gitignore()
        assert ".DS_Store" in result
        assert "Thumbs.db" in result
        assert "*.lnk" in result
        assert "*.swp" in result

    def test_gitignore_build_outputs(self):
        result = generate_gitignore()
        assert "*.apk" in result
        assert "*.aab" in result

    def test_gitignore_jetbrains(self):
        result = generate_gitignore()
        assert "JetBrains" in result

    def test_gitignore_crashlytics(self):
        result = generate_gitignore()
        assert "crashlytics-build.properties" in result


# ===================================================================
# TestNormalMapBake (IMP-04)
# ===================================================================


class TestNormalMapBake:
    """Tests for generate_normal_map_bake_script."""

    def test_normal_map_bake_basic(self):
        result = generate_normal_map_bake_script("HighPoly", "LowPoly")
        assert "bpy.ops.object.bake" in result
        assert "NORMAL" in result
        assert "TANGENT" in result
        assert "selected_to_active" in result

    def test_normal_map_bake_image_size(self):
        result = generate_normal_map_bake_script(
            "HighPoly", "LowPoly", image_size=4096
        )
        assert "4096" in result

    def test_normal_map_bake_cage(self):
        result = generate_normal_map_bake_script(
            "HighPoly", "LowPoly", cage_extrusion=0.2
        )
        assert "cage_extrusion" in result.lower() or "CAGE_EXTRUSION" in result
        assert "0.2" in result

    def test_normal_map_bake_samples(self):
        result = generate_normal_map_bake_script(
            "HighPoly", "LowPoly", samples=32
        )
        assert "32" in result

    def test_normal_map_bake_object_space(self):
        result = generate_normal_map_bake_script(
            "HighPoly", "LowPoly", normal_space="OBJECT"
        )
        assert "OBJECT" in result

    def test_normal_map_bake_uses_cycles(self):
        result = generate_normal_map_bake_script("HighPoly", "LowPoly")
        assert "CYCLES" in result

    def test_normal_map_bake_no_csharp(self):
        """Verify output is Blender Python, not C#."""
        result = generate_normal_map_bake_script("HighPoly", "LowPoly")
        # Must not contain C# patterns
        assert "using UnityEngine;" not in result
        assert "using UnityEditor;" not in result
        assert "namespace " not in result

    def test_normal_map_bake_only_allowed_imports(self):
        """Verify only bpy/mathutils/bmesh/math imports are used."""
        result = generate_normal_map_bake_script("HighPoly", "LowPoly")
        assert "import bpy" in result
        assert "import mathutils" in result
        # Should NOT import disallowed modules
        assert "import os" not in result
        assert "import sys" not in result
        assert "import subprocess" not in result

    def test_normal_map_bake_object_names(self):
        result = generate_normal_map_bake_script("MyHighPoly", "MyLowPoly")
        assert "MyHighPoly" in result
        assert "MyLowPoly" in result

    def test_normal_map_bake_output_name(self):
        result = generate_normal_map_bake_script(
            "HighPoly", "LowPoly", output_image_name="custom_normal"
        )
        assert "custom_normal" in result

    def test_normal_map_bake_saves_image(self):
        result = generate_normal_map_bake_script("HighPoly", "LowPoly")
        assert ".save()" in result or "bake_image.save()" in result

    def test_normal_map_bake_creates_image(self):
        result = generate_normal_map_bake_script("HighPoly", "LowPoly")
        assert "bpy.data.images.new" in result


# ===================================================================
# TestSpriteAtlas (BUILD-06)
# ===================================================================


class TestSpriteAtlas:
    """Tests for generate_sprite_atlas_script and generate_sprite_animation_script."""

    def test_sprite_atlas_basic(self):
        result = generate_sprite_atlas_script("UIAtlas", "Assets/Art/Sprites/UI")
        assert "SpriteAtlas" in result
        assert ".spriteatlas" in result
        assert "AssetDatabase.CreateAsset" in result

    def test_sprite_atlas_v1_extension(self):
        """Verify output uses .spriteatlas NOT .spriteatlasv2."""
        result = generate_sprite_atlas_script("UIAtlas", "Assets/Art/Sprites/UI")
        assert ".spriteatlas" in result
        assert ".spriteatlasv2" not in result

    def test_sprite_atlas_packing_settings(self):
        result = generate_sprite_atlas_script(
            "TestAtlas",
            "Assets/Art/Sprites",
            padding=8,
            enable_rotation=True,
        )
        assert "padding = 8" in result
        assert "enableRotation = true" in result

    def test_sprite_atlas_texture_settings(self):
        result = generate_sprite_atlas_script(
            "TestAtlas", "Assets/Art/Sprites", srgb=True
        )
        assert "sRGB = true" in result
        assert "filterMode" in result

    def test_sprite_atlas_include_in_build(self):
        result = generate_sprite_atlas_script(
            "TestAtlas",
            "Assets/Art/Sprites",
            include_in_build=False,
        )
        assert "SetIncludeInBuild(false)" in result

    def test_sprite_atlas_balanced_braces(self):
        result = generate_sprite_atlas_script("UIAtlas", "Assets/Art/Sprites/UI")
        assert check_brace_balance(result), "Braces are not balanced"

    def test_sprite_atlas_usings(self):
        result = generate_sprite_atlas_script("UIAtlas", "Assets/Art/Sprites/UI")
        assert "using UnityEditor.U2D;" in result
        assert "using UnityEngine.U2D;" in result

    def test_sprite_atlas_max_texture_size(self):
        result = generate_sprite_atlas_script(
            "TestAtlas", "Assets/Art", max_texture_size=2048
        )
        assert "2048" in result

    def test_sprite_atlas_filter_mode_point(self):
        result = generate_sprite_atlas_script(
            "TestAtlas", "Assets/Art", filter_mode="Point"
        )
        assert "FilterMode.Point" in result

    def test_sprite_atlas_tight_packing_disabled(self):
        result = generate_sprite_atlas_script(
            "TestAtlas", "Assets/Art", enable_tight_packing=False
        )
        assert "enableTightPacking = false" in result

    def test_sprite_animation_basic(self):
        result = generate_sprite_animation_script(
            "WalkAnim", "Assets/Art/Sprites/Walk"
        )
        assert "AnimationClip" in result
        assert "ObjectReferenceKeyframe" in result
        assert "AnimationUtility" in result

    def test_sprite_animation_loop(self):
        result = generate_sprite_animation_script(
            "WalkAnim", "Assets/Art/Sprites/Walk", loop=True
        )
        assert "loopTime = true" in result
        assert "WrapMode.Loop" in result

    def test_sprite_animation_no_loop(self):
        result = generate_sprite_animation_script(
            "AttackAnim", "Assets/Art/Sprites/Attack", loop=False
        )
        assert "loopTime = false" in result
        assert "WrapMode.Once" in result

    def test_sprite_animation_frame_rate(self):
        result = generate_sprite_animation_script(
            "WalkAnim", "Assets/Art/Sprites/Walk", frame_rate=24
        )
        assert "frameRate = 24" in result or "clip.frameRate = 24" in result

    def test_sprite_animation_balanced_braces(self):
        result = generate_sprite_animation_script(
            "WalkAnim", "Assets/Art/Sprites/Walk"
        )
        assert check_brace_balance(result), "Braces are not balanced"

    def test_sprite_animation_sprite_renderer_binding(self):
        result = generate_sprite_animation_script(
            "WalkAnim", "Assets/Art/Sprites/Walk"
        )
        assert "SpriteRenderer" in result
        assert "m_Sprite" in result

    def test_sprite_animation_finds_assets(self):
        result = generate_sprite_animation_script(
            "WalkAnim", "Assets/Art/Sprites/Walk"
        )
        assert "FindAssets" in result
        assert "t:Sprite" in result

    def test_sprite_animation_writes_result(self):
        result = generate_sprite_animation_script(
            "WalkAnim", "Assets/Art/Sprites/Walk"
        )
        assert "vb_result.json" in result


# ===================================================================
# TestSpriteEditor (TWO-03)
# ===================================================================


class TestSpriteEditor:
    """Tests for generate_sprite_editor_config_script."""

    def test_sprite_editor_pivot(self):
        result = generate_sprite_editor_config_script(
            "Assets/test.png", pivot=(0.5, 0.0)
        )
        assert "spritePivot" in result
        assert "Vector2" in result
        assert "0.5f" in result
        assert "0.0f" in result

    def test_sprite_editor_border(self):
        result = generate_sprite_editor_config_script(
            "Assets/test.png", border=(10, 10, 10, 10)
        )
        assert "spriteBorder" in result
        assert "Vector4" in result
        assert "10f" in result

    def test_sprite_editor_ppu(self):
        result = generate_sprite_editor_config_script(
            "Assets/test.png", pixels_per_unit=32
        )
        assert "32" in result
        assert "spritePixelsPerUnit" in result

    def test_sprite_editor_reimport(self):
        result = generate_sprite_editor_config_script("Assets/test.png")
        assert "SaveAndReimport" in result

    def test_sprite_editor_balanced_braces(self):
        result = generate_sprite_editor_config_script(
            "Assets/test.png", pivot=(0.5, 0.5), border=(5, 5, 5, 5)
        )
        assert check_brace_balance(result), "Braces are not balanced"

    def test_sprite_editor_texture_type(self):
        result = generate_sprite_editor_config_script("Assets/test.png")
        assert "TextureImporterType.Sprite" in result

    def test_sprite_editor_sprite_mode(self):
        result = generate_sprite_editor_config_script(
            "Assets/test.png", sprite_mode=2
        )
        assert "(SpriteImportMode)2" in result

    def test_sprite_editor_custom_alignment(self):
        """Pivot provided should use alignment=9 (Custom)."""
        result = generate_sprite_editor_config_script(
            "Assets/test.png", pivot=(0.25, 0.75)
        )
        assert "spriteAlignment = 9" in result

    def test_sprite_editor_writes_result(self):
        result = generate_sprite_editor_config_script("Assets/test.png")
        assert "vb_result.json" in result

    def test_sprite_editor_physics_shape(self):
        shape = [[(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]]
        result = generate_sprite_editor_config_script(
            "Assets/test.png", custom_physics_shape=shape
        )
        assert "SetPhysicsShape" in result
        assert "Vector2" in result


# ===================================================================
# TestAssetPostprocessor (PIPE-08)
# ===================================================================


class TestAssetPostprocessor:
    """Tests for generate_asset_postprocessor_script."""

    def test_postprocessor_basic(self):
        result = generate_asset_postprocessor_script("VBPostprocessor")
        assert "AssetPostprocessor" in result
        assert "GetVersion" in result
        assert "OnPreprocessTexture" in result

    def test_postprocessor_version(self):
        result = generate_asset_postprocessor_script("VBPostprocessor", version=3)
        assert "return 3;" in result

    def test_postprocessor_texture_rules(self):
        rules = [
            {
                "folder_pattern": "Sprites/",
                "settings_dict": {
                    "textureType": "Sprite",
                    "maxTextureSize": 2048,
                },
            }
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", texture_rules=rules
        )
        assert "TextureImporterType.Sprite" in result
        assert "2048" in result
        assert 'assetPath.Contains("Sprites/")' in result

    def test_postprocessor_model_rules(self):
        rules = [
            {
                "folder_pattern": "@",
                "settings_dict": {
                    "importMaterials": False,
                    "importAnimation": True,
                },
            }
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", model_rules=rules
        )
        assert "OnPreprocessModel" in result
        assert "importMaterials = false" in result
        assert "importAnimation = true" in result

    def test_postprocessor_no_onpostprocess(self):
        """Verify output does NOT contain OnPostprocess callbacks."""
        result = generate_asset_postprocessor_script("VBPostprocessor")
        assert "OnPostprocessTexture" not in result
        assert "OnPostprocessModel" not in result
        assert "OnPostprocessAudio" not in result

    def test_postprocessor_namespace(self):
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", namespace="VeilBreakers.Pipeline"
        )
        assert "namespace VeilBreakers.Pipeline" in result

    def test_postprocessor_balanced_braces(self):
        rules = [
            {
                "folder_pattern": "Characters/",
                "settings_dict": {"maxTextureSize": 4096, "sRGBTexture": True},
            }
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", texture_rules=rules
        )
        assert check_brace_balance(result), "Braces are not balanced"

    def test_postprocessor_audio_rules(self):
        rules = [
            {
                "folder_pattern": "SFX/",
                "settings_dict": {
                    "forceToMono": True,
                    "loadInBackground": False,
                },
            }
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", audio_rules=rules
        )
        assert "OnPreprocessAudio" in result
        assert "forceToMono = true" in result
        assert "loadInBackground = false" in result

    def test_postprocessor_multiple_texture_rules(self):
        rules = [
            {
                "folder_pattern": "UI/",
                "settings_dict": {"textureType": "Sprite"},
            },
            {
                "folder_pattern": "Characters/",
                "settings_dict": {"maxTextureSize": 4096},
            },
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", texture_rules=rules
        )
        assert 'assetPath.Contains("UI/")' in result
        assert 'assetPath.Contains("Characters/")' in result
        assert "else if" in result

    def test_postprocessor_default_version(self):
        result = generate_asset_postprocessor_script("VBPostprocessor")
        assert "return 1;" in result

    def test_postprocessor_class_name(self):
        result = generate_asset_postprocessor_script("MyCustomProcessor")
        assert "class MyCustomProcessor : AssetPostprocessor" in result

    def test_postprocessor_srgb_texture_setting(self):
        rules = [
            {
                "folder_pattern": "NormalMaps/",
                "settings_dict": {"sRGBTexture": False},
            }
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", texture_rules=rules
        )
        assert "sRGBTexture = false" in result

    def test_postprocessor_model_animation_type(self):
        rules = [
            {
                "folder_pattern": "Characters/",
                "settings_dict": {"animationType": "Humanoid"},
            }
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", model_rules=rules
        )
        assert "ModelImporterAnimationType.Humanoid" in result

    def test_postprocessor_model_mesh_compression(self):
        rules = [
            {
                "folder_pattern": "Props/",
                "settings_dict": {"meshCompression": "Medium"},
            }
        ]
        result = generate_asset_postprocessor_script(
            "VBPostprocessor", model_rules=rules
        )
        assert "ModelImporterMeshCompression.Medium" in result
