"""Encounter and AI system C# template generators for Unity.

Each function returns a complete C# source string (or tuple of strings for
multi-file generators) for encounter scripting, dynamic difficulty adjustment,
encounter balance simulation, and boss AI behavior systems.

Exports:
    generate_encounter_system_script    -- AID-01: SO wave definitions + MonoBehaviour manager
    generate_ai_director_script         -- AID-02: AnimationCurve-driven difficulty adjustment
    generate_encounter_simulator_script -- AID-03: Monte Carlo encounter simulation EditorWindow
    generate_boss_ai_script             -- VB-10: Multi-phase hierarchical FSM boss AI
"""

from __future__ import annotations

import re

from ._cs_sanitize import sanitize_cs_string, sanitize_cs_identifier


_CS_RESERVED = frozenset({
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
    "checked", "class", "const", "continue", "decimal", "default", "delegate",
    "do", "double", "else", "enum", "event", "explicit", "extern", "false",
    "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
    "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
    "new", "null", "object", "operator", "out", "override", "params", "private",
    "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
    "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
    "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
    "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
})


def _safe_namespace(ns: str) -> str:
    """Sanitize a C# namespace to prevent code injection."""
    sanitized = re.sub(r"[^a-zA-Z0-9_.]", "", ns)
    sanitized = re.sub(r"\.{2,}", ".", sanitized).strip(".")
    if not sanitized:
        return "Generated"
    segments = sanitized.split(".")
    fixed: list[str] = []
    for seg in segments:
        if not seg:
            continue
        if seg[0].isdigit():
            seg = f"_{seg}"
        if seg in _CS_RESERVED:
            seg = f"@{seg}"
        fixed.append(seg)
    return ".".join(fixed) or "Generated"


# ---------------------------------------------------------------------------
# AID-01: Encounter system (SO wave definitions + manager)
# ---------------------------------------------------------------------------


def generate_encounter_system_script(
    name: str = "Encounter",
    namespace: str = "",
) -> tuple[str, str]:
    """Generate SO-based wave definitions and encounter manager MonoBehaviour.

    Returns a 2-tuple: (wave_data_so_cs, encounter_manager_cs).

    The wave data ScriptableObject defines SpawnEntry arrays with spawn
    conditions and victory/defeat callbacks. The encounter manager uses
    trigger volumes and coroutine-based wave spawning with fog gate support.

    Args:
        name: Encounter name (sanitized for C# identifier).
        namespace: Optional C# namespace.

    Returns:
        Tuple of (wave_definition_so, encounter_manager) C# source strings.
    """
    safe_name = sanitize_cs_identifier(name)
    safe_str = sanitize_cs_string(name)

    ns = _safe_namespace(namespace) if namespace else ""
    ns_open = f"namespace {ns}\n{{" if ns else ""
    ns_close = "}" if ns else ""
    indent = "    " if ns else ""

    # ---- Wave Definition ScriptableObject ----
    so_lines: list[str] = []
    so_lines.append("using UnityEngine;")
    so_lines.append("using System;")
    so_lines.append("")
    if ns_open:
        so_lines.append(ns_open)

    so_lines.append(f"{indent}/// <summary>")
    so_lines.append(f"{indent}/// Serializable spawn entry for encounter wave definitions.")
    so_lines.append(f"{indent}/// Generated by VeilBreakers MCP toolkit.")
    so_lines.append(f"{indent}/// </summary>")
    so_lines.append(f"{indent}[Serializable]")
    so_lines.append(f"{indent}public class SpawnEntry")
    so_lines.append(f"{indent}{{")
    so_lines.append(f"{indent}    [Tooltip(\"Prefab name to spawn\")]")
    so_lines.append(f"{indent}    public string prefabName;")
    so_lines.append(f"{indent}    [Tooltip(\"Number of enemies to spawn\")]")
    so_lines.append(f"{indent}    public int count = 1;")
    so_lines.append(f"{indent}    [Tooltip(\"Delay between each spawn in seconds\")]")
    so_lines.append(f"{indent}    public float spawnDelay = 0.5f;")
    so_lines.append(f"{indent}    [Tooltip(\"Difficulty multiplier applied by AI director\")]")
    so_lines.append(f"{indent}    public float difficultyMultiplier = 1.0f;")
    so_lines.append(f"{indent}}}")
    so_lines.append("")

    so_lines.append(f"{indent}/// <summary>")
    so_lines.append(f"{indent}/// ScriptableObject defining a single wave in an encounter.")
    so_lines.append(f"{indent}/// Contains spawn entries, victory/defeat conditions, and timing.")
    so_lines.append(f"{indent}/// </summary>")
    so_lines.append(f'{indent}[CreateAssetMenu(menuName = "VeilBreakers/Encounter/Wave Definition")]')
    so_lines.append(f"{indent}public class VB_WaveDefinition : ScriptableObject")
    so_lines.append(f"{indent}{{")
    so_lines.append(f"{indent}    [Header(\"Spawn Configuration\")]")
    so_lines.append(f"{indent}    public SpawnEntry[] entries;")
    so_lines.append("")
    so_lines.append(f"{indent}    [Header(\"Timing\")]")
    so_lines.append(f"{indent}    [Tooltip(\"Delay before this wave starts after previous wave completes\")]")
    so_lines.append(f"{indent}    public float waveDelay = 2.0f;")
    so_lines.append("")
    so_lines.append(f"{indent}    [Header(\"Victory Conditions\")]")
    so_lines.append(f"{indent}    [Tooltip(\"Conditions: all_dead, timer, objective, boss_dead\")]")
    so_lines.append(f"{indent}    public string[] victoryConditions = new string[] {{ \"all_dead\" }};")
    so_lines.append(f"{indent}    [Tooltip(\"Time limit for timer victory condition\")]")
    so_lines.append(f"{indent}    public float timeLimit = 60f;")
    so_lines.append("")
    so_lines.append(f"{indent}    [Header(\"Defeat Conditions\")]")
    so_lines.append(f"{indent}    [Tooltip(\"Condition: player_death, time_expired, objective_failed\")]")
    so_lines.append(f"{indent}    public string defeatCondition = \"player_death\";")
    so_lines.append(f"{indent}}}")

    if ns_close:
        so_lines.append(ns_close)

    wave_so_cs = "\n".join(so_lines)

    # ---- Encounter Manager MonoBehaviour ----
    mgr_lines: list[str] = []
    mgr_lines.append("using UnityEngine;")
    mgr_lines.append("using UnityEngine.Events;")
    mgr_lines.append("using System.Collections;")
    mgr_lines.append("using System.Collections.Generic;")
    mgr_lines.append("")
    if ns_open:
        mgr_lines.append(ns_open)

    mgr_lines.append(f"{indent}/// <summary>")
    mgr_lines.append(f"{indent}/// Encounter manager for {safe_str}.")
    mgr_lines.append(f"{indent}/// Manages wave-based encounter spawning with trigger volumes,")
    mgr_lines.append(f"{indent}/// victory/defeat conditions, fog gates, and AI director integration.")
    mgr_lines.append(f"{indent}/// Generated by VeilBreakers MCP toolkit.")
    mgr_lines.append(f"{indent}/// </summary>")
    mgr_lines.append(f"{indent}public class VB_EncounterManager_{safe_name} : MonoBehaviour")
    mgr_lines.append(f"{indent}{{")

    # Fields
    mgr_lines.append(f"{indent}    [Header(\"Wave Configuration\")]")
    mgr_lines.append(f"{indent}    [SerializeField] private List<VB_WaveDefinition> _waves;")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}    [Header(\"Fog Gates\")]")
    mgr_lines.append(f"{indent}    [SerializeField] private GameObject[] _fogGates;")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}    [Header(\"Events\")]")
    mgr_lines.append(f"{indent}    public UnityEvent OnEncounterStarted;")
    mgr_lines.append(f"{indent}    public UnityEvent<int> OnWaveStarted;")
    mgr_lines.append(f"{indent}    public UnityEvent OnWaveComplete;")
    mgr_lines.append(f"{indent}    public UnityEvent OnEncounterVictory;")
    mgr_lines.append(f"{indent}    public UnityEvent OnEncounterDefeat;")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}    // Runtime state")
    mgr_lines.append(f"{indent}    private int _currentWaveIndex;")
    mgr_lines.append(f"{indent}    private int _spawnedCount;")
    mgr_lines.append(f"{indent}    private int _defeatedCount;")
    mgr_lines.append(f"{indent}    private float _waveElapsedTime;")
    mgr_lines.append(f"{indent}    private bool _encounterActive;")
    mgr_lines.append(f"{indent}    private bool _encounterComplete;")
    mgr_lines.append(f"{indent}    private float _difficultyModifier = 1.0f;")
    mgr_lines.append(f"{indent}    private Coroutine _encounterCoroutine;")
    mgr_lines.append("")

    # OnTriggerEnter
    mgr_lines.append(f"{indent}    private void OnTriggerEnter(Collider other)")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f'{indent}        if (!_encounterActive && !_encounterComplete && other.CompareTag("Player"))')
    mgr_lines.append(f"{indent}        {{")
    mgr_lines.append(f"{indent}            StartEncounter();")
    mgr_lines.append(f"{indent}        }}")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # StartEncounter
    mgr_lines.append(f"{indent}    /// <summary>Start the encounter sequence.</summary>")
    mgr_lines.append(f"{indent}    public void StartEncounter()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        if (_encounterActive || _encounterComplete) return;")
    mgr_lines.append(f"{indent}        _encounterActive = true;")
    mgr_lines.append(f"{indent}        _currentWaveIndex = 0;")
    mgr_lines.append(f"{indent}        _spawnedCount = 0;")
    mgr_lines.append(f"{indent}        _defeatedCount = 0;")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}        // Enable fog gates")
    mgr_lines.append(f"{indent}        if (_fogGates != null)")
    mgr_lines.append(f"{indent}        {{")
    mgr_lines.append(f"{indent}            foreach (var gate in _fogGates)")
    mgr_lines.append(f"{indent}                if (gate != null) gate.SetActive(true);")
    mgr_lines.append(f"{indent}        }}")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}        OnEncounterStarted?.Invoke();")
    mgr_lines.append(f"{indent}        _encounterCoroutine = StartCoroutine(RunEncounter());")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # RunEncounter coroutine
    mgr_lines.append(f"{indent}    private IEnumerator RunEncounter()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        for (int w = 0; w < _waves.Count; w++)")
    mgr_lines.append(f"{indent}        {{")
    mgr_lines.append(f"{indent}            _currentWaveIndex = w;")
    mgr_lines.append(f"{indent}            var wave = _waves[w];")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}            // Wait for wave delay")
    mgr_lines.append(f"{indent}            if (wave.waveDelay > 0)")
    mgr_lines.append(f"{indent}                yield return new WaitForSeconds(wave.waveDelay);")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}            _spawnedCount = 0;")
    mgr_lines.append(f"{indent}            _defeatedCount = 0;")
    mgr_lines.append(f"{indent}            _waveElapsedTime = 0f;")
    mgr_lines.append(f"{indent}            OnWaveStarted?.Invoke(w);")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}            // Spawn enemies for this wave")
    mgr_lines.append(f"{indent}            if (wave.entries != null)")
    mgr_lines.append(f"{indent}            {{")
    mgr_lines.append(f"{indent}                foreach (var entry in wave.entries)")
    mgr_lines.append(f"{indent}                {{")
    mgr_lines.append(f"{indent}                    int adjustedCount = Mathf.RoundToInt(entry.count * entry.difficultyMultiplier * _difficultyModifier);")
    mgr_lines.append(f"{indent}                    for (int i = 0; i < adjustedCount; i++)")
    mgr_lines.append(f"{indent}                    {{")
    mgr_lines.append(f"{indent}                        SpawnEnemy(entry.prefabName);")
    mgr_lines.append(f"{indent}                        _spawnedCount++;")
    mgr_lines.append(f"{indent}                        if (entry.spawnDelay > 0)")
    mgr_lines.append(f"{indent}                            yield return new WaitForSeconds(entry.spawnDelay);")
    mgr_lines.append(f"{indent}                    }}")
    mgr_lines.append(f"{indent}                }}")
    mgr_lines.append(f"{indent}            }}")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}            // Wait for victory condition")
    mgr_lines.append(f"{indent}            bool waveComplete = false;")
    mgr_lines.append(f"{indent}            while (!waveComplete)")
    mgr_lines.append(f"{indent}            {{")
    mgr_lines.append(f"{indent}                _waveElapsedTime += Time.deltaTime;")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}                // Check defeat")
    mgr_lines.append(f'{indent}                if (wave.defeatCondition == "time_expired" && _waveElapsedTime >= wave.timeLimit)')
    mgr_lines.append(f"{indent}                {{")
    mgr_lines.append(f"{indent}                    HandleDefeat();")
    mgr_lines.append(f"{indent}                    yield break;")
    mgr_lines.append(f"{indent}                }}")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}                // Check victory conditions")
    mgr_lines.append(f"{indent}                if (wave.victoryConditions != null && wave.victoryConditions.Length > 0)")
    mgr_lines.append(f"{indent}                {{")
    mgr_lines.append(f"{indent}                    foreach (var condition in wave.victoryConditions)")
    mgr_lines.append(f"{indent}                    {{")
    mgr_lines.append(f'{indent}                        if (condition == "all_dead" && _defeatedCount >= _spawnedCount && _spawnedCount > 0)')
    mgr_lines.append(f"{indent}                            waveComplete = true;")
    mgr_lines.append(f'{indent}                        else if (condition == "timer" && _waveElapsedTime >= wave.timeLimit)')
    mgr_lines.append(f"{indent}                            waveComplete = true;")
    mgr_lines.append(f'{indent}                        else if (condition == "boss_dead" && _defeatedCount >= _spawnedCount && _spawnedCount > 0)')
    mgr_lines.append(f"{indent}                            waveComplete = true;")
    mgr_lines.append(f"{indent}                    }}")
    mgr_lines.append(f"{indent}                }}")
    mgr_lines.append(f"{indent}                else")
    mgr_lines.append(f"{indent}                {{")
    mgr_lines.append(f"{indent}                    // Default: wave complete when all spawned enemies are dead")
    mgr_lines.append(f"{indent}                    if (_defeatedCount >= _spawnedCount && _spawnedCount > 0)")
    mgr_lines.append(f"{indent}                        waveComplete = true;")
    mgr_lines.append(f"{indent}                }}")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}                yield return null;")
    mgr_lines.append(f"{indent}            }}")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}            OnWaveComplete?.Invoke();")
    mgr_lines.append(f"{indent}        }}")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}        // All waves complete = victory")
    mgr_lines.append(f"{indent}        HandleVictory();")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # SpawnEnemy
    mgr_lines.append(f"{indent}    private void SpawnEnemy(string prefabName)")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        var prefab = Resources.Load<GameObject>(prefabName);")
    mgr_lines.append(f"{indent}        if (prefab == null)")
    mgr_lines.append(f"{indent}        {{")
    mgr_lines.append(f'{indent}            Debug.LogWarning($"Encounter: Could not load prefab \'{{prefabName}}\'");')
    mgr_lines.append(f"{indent}            return;")
    mgr_lines.append(f"{indent}        }}")
    mgr_lines.append(f"{indent}        Vector3 spawnPos = transform.position + Random.insideUnitSphere * 5f;")
    mgr_lines.append(f"{indent}        spawnPos.y = transform.position.y;")
    mgr_lines.append(f"{indent}        Instantiate(prefab, spawnPos, Quaternion.identity);")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # OnEnemyDefeated
    mgr_lines.append(f"{indent}    /// <summary>Call when an enemy in this encounter is defeated.</summary>")
    mgr_lines.append(f"{indent}    public void OnEnemyDefeated()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        _defeatedCount++;")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # HandleVictory / HandleDefeat
    mgr_lines.append(f"{indent}    private void HandleVictory()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        _encounterActive = false;")
    mgr_lines.append(f"{indent}        _encounterComplete = true;")
    mgr_lines.append(f"{indent}        DisableFogGates();")
    mgr_lines.append(f"{indent}        OnEncounterVictory?.Invoke();")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")
    mgr_lines.append(f"{indent}    private void HandleDefeat()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        if (!_encounterActive) return;")
    mgr_lines.append(f"{indent}        _encounterActive = false;")
    mgr_lines.append(f"{indent}        StopAllCoroutines();")
    mgr_lines.append(f"{indent}        _encounterCoroutine = null;")
    mgr_lines.append(f"{indent}        OnEncounterDefeat?.Invoke();")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # DisableFogGates
    mgr_lines.append(f"{indent}    private void DisableFogGates()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        if (_fogGates != null)")
    mgr_lines.append(f"{indent}        {{")
    mgr_lines.append(f"{indent}            foreach (var gate in _fogGates)")
    mgr_lines.append(f"{indent}                if (gate != null) gate.SetActive(false);")
    mgr_lines.append(f"{indent}        }}")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # SetDifficultyModifier
    mgr_lines.append(f"{indent}    /// <summary>Set difficulty modifier from AI director.</summary>")
    mgr_lines.append(f"{indent}    public void SetDifficultyModifier(float modifier)")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        _difficultyModifier = Mathf.Max(0.1f, modifier);")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # ResetEncounter
    mgr_lines.append(f"{indent}    /// <summary>Reset encounter to allow replay.</summary>")
    mgr_lines.append(f"{indent}    public void ResetEncounter()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        if (_encounterCoroutine != null)")
    mgr_lines.append(f"{indent}            StopCoroutine(_encounterCoroutine);")
    mgr_lines.append(f"{indent}        _encounterActive = false;")
    mgr_lines.append(f"{indent}        _encounterComplete = false;")
    mgr_lines.append(f"{indent}        _currentWaveIndex = 0;")
    mgr_lines.append(f"{indent}        _spawnedCount = 0;")
    mgr_lines.append(f"{indent}        _defeatedCount = 0;")
    mgr_lines.append(f"{indent}        _waveElapsedTime = 0f;")
    mgr_lines.append(f"{indent}        DisableFogGates();")
    mgr_lines.append(f"{indent}    }}")
    mgr_lines.append("")

    # ForceEndEncounter
    mgr_lines.append(f"{indent}    /// <summary>Force-end the encounter immediately.</summary>")
    mgr_lines.append(f"{indent}    public void ForceEndEncounter()")
    mgr_lines.append(f"{indent}    {{")
    mgr_lines.append(f"{indent}        if (_encounterCoroutine != null)")
    mgr_lines.append(f"{indent}            StopCoroutine(_encounterCoroutine);")
    mgr_lines.append(f"{indent}        _encounterActive = false;")
    mgr_lines.append(f"{indent}        _encounterComplete = true;")
    mgr_lines.append(f"{indent}        DisableFogGates();")
    mgr_lines.append(f"{indent}    }}")

    mgr_lines.append(f"{indent}}}")
    if ns_close:
        mgr_lines.append(ns_close)

    manager_cs = "\n".join(mgr_lines)

    return (wave_so_cs, manager_cs)


# ---------------------------------------------------------------------------
# AID-02: AI Director (dynamic difficulty adjustment)
# ---------------------------------------------------------------------------


def generate_ai_director_script(
    name: str = "AIDirector",
    namespace: str = "",
) -> str:
    """Generate AI director MonoBehaviour with AnimationCurve-driven difficulty.

    Tracks player performance (deaths, clear time, damage ratio) across
    encounters and adjusts difficulty score (0.0-1.0) using lerped smoothing.
    Difficulty score is evaluated against AnimationCurve fields for spawn
    rate and enemy stat multipliers.

    Args:
        name: Director name (sanitized for C# identifier).
        namespace: Optional C# namespace.

    Returns:
        Complete C# source string.
    """
    safe_name = sanitize_cs_identifier(name)
    safe_str = sanitize_cs_string(name)

    ns = _safe_namespace(namespace) if namespace else ""
    ns_open = f"namespace {ns}\n{{" if ns else ""
    ns_close = "}" if ns else ""
    indent = "    " if ns else ""

    lines: list[str] = []
    lines.append("using UnityEngine;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    if ns_open:
        lines.append(ns_open)

    lines.append(f"{indent}/// <summary>")
    lines.append(f"{indent}/// AI Director for {safe_str}.")
    lines.append(f"{indent}/// Tracks player performance and dynamically adjusts difficulty")
    lines.append(f"{indent}/// using AnimationCurve-driven spawn rate and stat multipliers.")
    lines.append(f"{indent}/// Generated by VeilBreakers MCP toolkit.")
    lines.append(f"{indent}/// </summary>")
    lines.append(f"{indent}public class VB_AIDirector_{safe_name} : MonoBehaviour")
    lines.append(f"{indent}{{")

    # Difficulty fields
    lines.append(f"{indent}    [Header(\"Difficulty Configuration\")]")
    lines.append(f"{indent}    [SerializeField] private AnimationCurve _spawnRateCurve = AnimationCurve.Linear(0f, 0.5f, 1f, 2.0f);")
    lines.append(f"{indent}    [SerializeField] private AnimationCurve _enemyStatCurve = AnimationCurve.Linear(0f, 0.7f, 1f, 1.5f);")
    lines.append(f"{indent}    [SerializeField] private float _adjustmentSpeed = 0.1f;")
    lines.append("")

    # Performance tracking
    lines.append(f"{indent}    [Header(\"Performance Tracking\")]")
    lines.append(f"{indent}    [SerializeField, Range(0f, 1f)] private float _difficultyScore = 0.5f;")
    lines.append(f"{indent}    private float _targetDifficulty = 0.5f;")
    lines.append(f"{indent}    private int _recentDeaths;")
    lines.append(f"{indent}    private float _averageClearTime;")
    lines.append(f"{indent}    private float _damageTakenRatio;")
    lines.append("")

    # Sliding window
    lines.append(f"{indent}    // Sliding window for moving averages (last 5 encounters)")
    lines.append(f"{indent}    private List<float> _clearTimes = new List<float>();")
    lines.append(f"{indent}    private List<int> _deathCounts = new List<int>();")
    lines.append(f"{indent}    private List<float> _damageRatios = new List<float>();")
    lines.append(f"{indent}    private const int _windowSize = 5;")
    lines.append("")

    # Per-encounter tracking
    lines.append(f"{indent}    // Per-encounter tracking")
    lines.append(f"{indent}    private int _encounterKills;")
    lines.append(f"{indent}    private int _encounterDeaths;")
    lines.append(f"{indent}    private float _encounterDamageDealt;")
    lines.append(f"{indent}    private float _encounterDamageTaken;")
    lines.append(f"{indent}    private float _encounterTimeElapsed;")
    lines.append("")

    # Properties
    lines.append(f"{indent}    /// <summary>Current difficulty score (0.0 to 1.0).</summary>")
    lines.append(f"{indent}    public float DifficultyScore => _difficultyScore;")
    lines.append("")

    # Update
    lines.append(f"{indent}    private void Update()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        UpdateDifficulty();")
    lines.append(f"{indent}    }}")
    lines.append("")

    # UpdateDifficulty
    lines.append(f"{indent}    /// <summary>Lerp difficulty toward target. Called each frame.</summary>")
    lines.append(f"{indent}    public void UpdateDifficulty()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _difficultyScore = Mathf.Lerp(_difficultyScore, _targetDifficulty, _adjustmentSpeed * Time.deltaTime);")
    lines.append(f"{indent}        _difficultyScore = Mathf.Clamp01(_difficultyScore);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # GetSpawnRateMultiplier
    lines.append(f"{indent}    /// <summary>Evaluate spawn rate multiplier from difficulty curve.</summary>")
    lines.append(f"{indent}    public float GetSpawnRateMultiplier()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        return _spawnRateCurve.Evaluate(_difficultyScore);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # GetStatMultiplier
    lines.append(f"{indent}    /// <summary>Evaluate enemy stat multiplier from difficulty curve.</summary>")
    lines.append(f"{indent}    public float GetStatMultiplier()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        return _enemyStatCurve.Evaluate(_difficultyScore);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # RecordEncounterResult
    lines.append(f"{indent}    /// <summary>Record the result of a completed encounter.</summary>")
    lines.append(f"{indent}    public void RecordEncounterResult(float clearTime, int deaths, float damageRatio)")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        // Update sliding windows")
    lines.append(f"{indent}        _clearTimes.Add(clearTime);")
    lines.append(f"{indent}        if (_clearTimes.Count > _windowSize) _clearTimes.RemoveAt(0);")
    lines.append("")
    lines.append(f"{indent}        _deathCounts.Add(deaths);")
    lines.append(f"{indent}        if (_deathCounts.Count > _windowSize) _deathCounts.RemoveAt(0);")
    lines.append("")
    lines.append(f"{indent}        _damageRatios.Add(damageRatio);")
    lines.append(f"{indent}        if (_damageRatios.Count > _windowSize) _damageRatios.RemoveAt(0);")
    lines.append("")
    lines.append(f"{indent}        // Calculate moving averages")
    lines.append(f"{indent}        _averageClearTime = 0f;")
    lines.append(f"{indent}        foreach (var t in _clearTimes) _averageClearTime += t;")
    lines.append(f"{indent}        _averageClearTime /= _clearTimes.Count;")
    lines.append("")
    lines.append(f"{indent}        _recentDeaths = 0;")
    lines.append(f"{indent}        foreach (var d in _deathCounts) _recentDeaths += d;")
    lines.append("")
    lines.append(f"{indent}        _damageTakenRatio = 0f;")
    lines.append(f"{indent}        foreach (var r in _damageRatios) _damageTakenRatio += r;")
    lines.append(f"{indent}        _damageTakenRatio /= _damageRatios.Count;")
    lines.append("")
    lines.append(f"{indent}        // Calculate target difficulty")
    lines.append(f"{indent}        // Decrease on deaths, increase on fast clears and low damage")
    lines.append(f"{indent}        float deathPenalty = _recentDeaths * 0.05f;")
    lines.append(f"{indent}        float speedBonus = (_averageClearTime < 30f) ? 0.1f : (_averageClearTime < 60f) ? 0.05f : 0f;")
    lines.append(f"{indent}        float damageBonus = (1f - _damageTakenRatio) * 0.1f;")
    lines.append("")
    lines.append(f"{indent}        _targetDifficulty = Mathf.Clamp01(0.5f - deathPenalty + speedBonus + damageBonus);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # Integration: push difficulty to EncounterManagers
    lines.append(f"{indent}    /// <summary>Push current difficulty modifier to all encounter managers in scene.</summary>")
    lines.append(f"{indent}    public void ApplyDifficultyToEncounters()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        float modifier = GetSpawnRateMultiplier();")
    lines.append(f"{indent}        var managers = FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None);")
    lines.append(f"{indent}        foreach (var mgr in managers)")
    lines.append(f"{indent}        {{")
    lines.append(f'{indent}            var method = mgr.GetType().GetMethod("SetDifficultyModifier");')
    lines.append(f"{indent}            if (method != null)")
    lines.append(f"{indent}                method.Invoke(mgr, new object[] {{ modifier }});")
    lines.append(f"{indent}        }}")
    lines.append(f"{indent}    }}")

    lines.append(f"{indent}}}")
    if ns_close:
        lines.append(ns_close)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# AID-03: Encounter simulator (Monte Carlo EditorWindow)
# ---------------------------------------------------------------------------


def generate_encounter_simulator_script(
    name: str = "EncounterSimulator",
    namespace: str = "",
) -> str:
    """Generate IMGUI EditorWindow for Monte Carlo encounter simulation.

    Runs N configurable simulation runs of wave-based encounters with
    player DPS vs enemy HP, dodge chance, and AI director difficulty.
    Displays win rate, average clear time, HP remaining, and difficulty
    recommendation.

    EDITOR ONLY -- uses ``#if UNITY_EDITOR`` and ``using UnityEditor;``.

    Args:
        name: Simulator window name (sanitized for C# identifier).
        namespace: Optional C# namespace.

    Returns:
        Complete C# source string.
    """
    safe_name = sanitize_cs_identifier(name)

    ns = _safe_namespace(namespace) if namespace else ""
    ns_open = f"namespace {ns}\n{{" if ns else ""
    ns_close = "}" if ns else ""
    indent = "    " if ns else ""

    lines: list[str] = []
    lines.append("#if UNITY_EDITOR")
    lines.append("using UnityEngine;")
    lines.append("using UnityEditor;")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("using System.IO;")
    lines.append("")
    if ns_open:
        lines.append(ns_open)

    lines.append(f"{indent}/// <summary>")
    lines.append(f"{indent}/// Monte Carlo encounter simulation EditorWindow.")
    lines.append(f"{indent}/// Runs N full encounter simulations with wave spawning,")
    lines.append(f"{indent}/// player DPS vs enemy HP, and statistical analysis.")
    lines.append(f"{indent}/// Generated by VeilBreakers MCP toolkit.")
    lines.append(f"{indent}/// </summary>")
    lines.append(f"{indent}public class VB_{safe_name} : EditorWindow")
    lines.append(f"{indent}{{")

    # Simulation parameters
    lines.append(f"{indent}    [Header(\"Simulation Parameters\")]")
    lines.append(f"{indent}    private int _simulationCount = 1000;")
    lines.append(f"{indent}    private float _playerDPS = 120f;")
    lines.append(f"{indent}    private float _playerHP = 500f;")
    lines.append(f"{indent}    private float _playerDodgeChance = 0.15f;")
    lines.append("")

    # Wave config
    lines.append(f"{indent}    [Header(\"Wave Configuration\")]")
    lines.append(f"{indent}    private int _waveCount = 3;")
    lines.append(f"{indent}    private int _enemiesPerWave = 5;")
    lines.append(f"{indent}    private float _enemyHP = 200f;")
    lines.append(f"{indent}    private float _enemyDPS = 30f;")
    lines.append("")

    # AI Director
    lines.append(f"{indent}    [Header(\"AI Director\")]")
    lines.append(f"{indent}    private float _difficultyScore = 0.5f;")
    lines.append("")

    # Simulation state
    lines.append(f"{indent}    // Simulation state")
    lines.append(f"{indent}    private bool _isSimulating;")
    lines.append(f"{indent}    private int _completedRuns;")
    lines.append(f"{indent}    private int _batchSize = 50;")
    lines.append("")

    # Results
    lines.append(f"{indent}    // Results")
    lines.append(f"{indent}    private bool _hasResults;")
    lines.append(f"{indent}    private float _winRate;")
    lines.append(f"{indent}    private float _avgClearTime;")
    lines.append(f"{indent}    private float _stdDevClearTime;")
    lines.append(f"{indent}    private float _avgPlayerHPRemaining;")
    lines.append(f"{indent}    private float _avgDPSDealt;")
    lines.append(f"{indent}    private string _difficultyRecommendation = \"\";")
    lines.append("")
    lines.append(f"{indent}    // Accumulated stats for running simulation")
    lines.append(f"{indent}    private int _totalWins;")
    lines.append(f"{indent}    private List<float> _allClearTimes;")
    lines.append(f"{indent}    private float _totalPlayerHPRemaining;")
    lines.append(f"{indent}    private float _totalDamageDealt;")
    lines.append(f"{indent}    private float _totalTimeElapsed;")
    lines.append("")

    # MenuItem
    lines.append(f'{indent}    [MenuItem("VeilBreakers/Tools/Encounter Simulator")]')
    lines.append(f"{indent}    public static void ShowWindow()")
    lines.append(f"{indent}    {{")
    lines.append(f'{indent}        GetWindow<VB_{safe_name}>("Encounter Simulator");')
    lines.append(f"{indent}    }}")
    lines.append("")

    # OnGUI
    lines.append(f"{indent}    private void OnGUI()")
    lines.append(f"{indent}    {{")
    lines.append(f'{indent}        GUILayout.Label("Monte Carlo Encounter Simulator", EditorStyles.boldLabel);')
    lines.append(f"{indent}        EditorGUILayout.Space();")
    lines.append("")
    lines.append(f"{indent}        // Player stats")
    lines.append(f'{indent}        GUILayout.Label("Player Stats", EditorStyles.miniBoldLabel);')
    lines.append(f'{indent}        _playerDPS = EditorGUILayout.FloatField("Player DPS", _playerDPS);')
    lines.append(f'{indent}        _playerHP = EditorGUILayout.FloatField("Player HP", _playerHP);')
    lines.append(f'{indent}        _playerDodgeChance = EditorGUILayout.Slider("Dodge Chance", _playerDodgeChance, 0f, 1f);')
    lines.append(f"{indent}        EditorGUILayout.Space();")
    lines.append("")
    lines.append(f"{indent}        // Wave config")
    lines.append(f'{indent}        GUILayout.Label("Wave Configuration", EditorStyles.miniBoldLabel);')
    lines.append(f'{indent}        _waveCount = EditorGUILayout.IntField("Wave Count", _waveCount);')
    lines.append(f'{indent}        _enemiesPerWave = EditorGUILayout.IntField("Enemies Per Wave", _enemiesPerWave);')
    lines.append(f'{indent}        _enemyHP = EditorGUILayout.FloatField("Enemy HP", _enemyHP);')
    lines.append(f'{indent}        _enemyDPS = EditorGUILayout.FloatField("Enemy DPS", _enemyDPS);')
    lines.append(f"{indent}        EditorGUILayout.Space();")
    lines.append("")
    lines.append(f"{indent}        // Simulation settings")
    lines.append(f'{indent}        GUILayout.Label("Simulation Settings", EditorStyles.miniBoldLabel);')
    lines.append(f'{indent}        _simulationCount = EditorGUILayout.IntField("Simulation Count", _simulationCount);')
    lines.append(f'{indent}        _difficultyScore = EditorGUILayout.Slider("Difficulty Score", _difficultyScore, 0f, 1f);')
    lines.append(f"{indent}        EditorGUILayout.Space();")
    lines.append("")

    # Run button
    lines.append(f"{indent}        EditorGUI.BeginDisabledGroup(_isSimulating);")
    lines.append(f'{indent}        if (GUILayout.Button("Run Simulation"))')
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            StartSimulation();")
    lines.append(f"{indent}        }}")
    lines.append(f"{indent}        EditorGUI.EndDisabledGroup();")
    lines.append("")

    # Progress bar
    lines.append(f"{indent}        if (_isSimulating)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            float progress = (float)_completedRuns / _simulationCount;")
    lines.append(f'{indent}            EditorGUI.ProgressBar(EditorGUILayout.GetControlRect(false, 20f), progress, $"Simulating... {{_completedRuns}}/{{_simulationCount}}");')
    lines.append(f"{indent}        }}")
    lines.append("")

    # Results
    lines.append(f"{indent}        if (_hasResults)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            EditorGUILayout.Space();")
    lines.append(f'{indent}            GUILayout.Label("Results", EditorStyles.boldLabel);')
    lines.append(f'{indent}            EditorGUILayout.LabelField("Win Rate", (_winRate * 100f).ToString("F1") + "%");')
    lines.append(f'{indent}            EditorGUILayout.LabelField("Avg Clear Time", _avgClearTime.ToString("F2") + "s");')
    lines.append(f'{indent}            EditorGUILayout.LabelField("Std Dev Clear Time", _stdDevClearTime.ToString("F2") + "s");')
    lines.append(f'{indent}            EditorGUILayout.LabelField("Avg Player HP Remaining", _avgPlayerHPRemaining.ToString("F1"));')
    lines.append(f'{indent}            EditorGUILayout.LabelField("Avg DPS Dealt", _avgDPSDealt.ToString("F1"));')
    lines.append(f"{indent}            EditorGUILayout.Space();")
    lines.append(f'{indent}            EditorGUILayout.LabelField("Difficulty Recommendation", _difficultyRecommendation, EditorStyles.boldLabel);')
    lines.append(f"{indent}            EditorGUILayout.Space();")
    lines.append("")
    lines.append(f'{indent}            if (GUILayout.Button("Export Results to JSON"))')
    lines.append(f"{indent}            {{")
    lines.append(f"{indent}                ExportResults();")
    lines.append(f"{indent}            }}")
    lines.append(f"{indent}        }}")
    lines.append(f"{indent}    }}")
    lines.append("")

    # StartSimulation
    lines.append(f"{indent}    private void StartSimulation()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _isSimulating = true;")
    lines.append(f"{indent}        _completedRuns = 0;")
    lines.append(f"{indent}        _totalWins = 0;")
    lines.append(f"{indent}        _allClearTimes = new List<float>();")
    lines.append(f"{indent}        _totalPlayerHPRemaining = 0f;")
    lines.append(f"{indent}        _totalDamageDealt = 0f;")
    lines.append(f"{indent}        _totalTimeElapsed = 0f;")
    lines.append(f"{indent}        _hasResults = false;")
    lines.append(f"{indent}        EditorApplication.update += SimulationBatch;")
    lines.append(f"{indent}    }}")
    lines.append("")

    # SimulationBatch (per-frame batched execution)
    lines.append(f"{indent}    private void SimulationBatch()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        int batchEnd = Mathf.Min(_completedRuns + _batchSize, _simulationCount);")
    lines.append(f"{indent}        var rng = new System.Random(_completedRuns);")
    lines.append("")
    lines.append(f"{indent}        for (int i = _completedRuns; i < batchEnd; i++)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            RunSingleSimulation(rng);")
    lines.append(f"{indent}        }}")
    lines.append("")
    lines.append(f"{indent}        _completedRuns = batchEnd;")
    lines.append("")
    lines.append(f"{indent}        if (_completedRuns >= _simulationCount)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            EditorApplication.update -= SimulationBatch;")
    lines.append(f"{indent}            FinalizeResults();")
    lines.append(f"{indent}        }}")
    lines.append("")
    lines.append(f"{indent}        Repaint();")
    lines.append(f"{indent}    }}")
    lines.append("")

    # RunSingleSimulation
    lines.append(f"{indent}    private void RunSingleSimulation(System.Random rng)")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        float pHP = _playerHP;")
    lines.append(f"{indent}        float totalDamageDealt = 0f;")
    lines.append(f"{indent}        float timeElapsed = 0f;")
    lines.append(f"{indent}        float dt = 0.1f; // simulation time step")
    lines.append(f"{indent}        float diffMultiplier = 0.5f + _difficultyScore; // 0.5x to 1.5x")
    lines.append("")
    lines.append(f"{indent}        for (int wave = 0; wave < _waveCount; wave++)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            int enemiesAlive = Mathf.RoundToInt(_enemiesPerWave * diffMultiplier);")
    lines.append(f"{indent}            float[] enemyHPs = new float[enemiesAlive];")
    lines.append(f"{indent}            for (int e = 0; e < enemiesAlive; e++)")
    lines.append(f"{indent}                enemyHPs[e] = _enemyHP * diffMultiplier;")
    lines.append("")
    lines.append(f"{indent}            while (enemiesAlive > 0 && pHP > 0)")
    lines.append(f"{indent}            {{")
    lines.append(f"{indent}                timeElapsed += dt;")
    lines.append("")
    lines.append(f"{indent}                // Player deals DPS * dt spread across alive enemies")
    lines.append(f"{indent}                float playerDamage = _playerDPS * dt;")
    lines.append(f"{indent}                for (int e = 0; e < enemyHPs.Length; e++)")
    lines.append(f"{indent}                {{")
    lines.append(f"{indent}                    if (enemyHPs[e] <= 0) continue;")
    lines.append(f"{indent}                    enemyHPs[e] -= playerDamage;")
    lines.append(f"{indent}                    totalDamageDealt += playerDamage;")
    lines.append(f"{indent}                    if (enemyHPs[e] <= 0) enemiesAlive--;")
    lines.append(f"{indent}                    break; // focus fire on one enemy at a time")
    lines.append(f"{indent}                }}")
    lines.append("")
    lines.append(f"{indent}                // Enemies deal DPS * dt * (1-dodgeChance)")
    lines.append(f"{indent}                float dodgeRoll = (float)rng.NextDouble();")
    lines.append(f"{indent}                if (dodgeRoll > _playerDodgeChance)")
    lines.append(f"{indent}                {{")
    lines.append(f"{indent}                    float enemyTotalDPS = _enemyDPS * enemiesAlive * diffMultiplier * dt;")
    lines.append(f"{indent}                    pHP -= enemyTotalDPS;")
    lines.append(f"{indent}                }}")
    lines.append("")
    lines.append(f"{indent}                // Safety: prevent infinite loops")
    lines.append(f"{indent}                if (timeElapsed > 600f) break;")
    lines.append(f"{indent}            }}")
    lines.append("")
    lines.append(f"{indent}            if (pHP <= 0) break;")
    lines.append(f"{indent}        }}")
    lines.append("")
    lines.append(f"{indent}        bool win = pHP > 0;")
    lines.append(f"{indent}        if (win) _totalWins++;")
    lines.append(f"{indent}        _allClearTimes.Add(timeElapsed);")
    lines.append(f"{indent}        _totalPlayerHPRemaining += Mathf.Max(0f, pHP);")
    lines.append(f"{indent}        _totalDamageDealt += totalDamageDealt;")
    lines.append(f"{indent}        _totalTimeElapsed += timeElapsed;")
    lines.append(f"{indent}    }}")
    lines.append("")

    # FinalizeResults
    lines.append(f"{indent}    private void FinalizeResults()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _winRate = (float)_totalWins / _simulationCount;")
    lines.append("")
    lines.append(f"{indent}        // Average clear time")
    lines.append(f"{indent}        float sumTime = 0f;")
    lines.append(f"{indent}        foreach (var t in _allClearTimes) sumTime += t;")
    lines.append(f"{indent}        _avgClearTime = sumTime / _allClearTimes.Count;")
    lines.append("")
    lines.append(f"{indent}        // Standard deviation")
    lines.append(f"{indent}        float sumSqDiff = 0f;")
    lines.append(f"{indent}        foreach (var t in _allClearTimes)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            float diff = t - _avgClearTime;")
    lines.append(f"{indent}            sumSqDiff += diff * diff;")
    lines.append(f"{indent}        }}")
    lines.append(f"{indent}        _stdDevClearTime = Mathf.Sqrt(sumSqDiff / _allClearTimes.Count);")
    lines.append("")
    lines.append(f"{indent}        _avgPlayerHPRemaining = _totalPlayerHPRemaining / _simulationCount;")
    lines.append(f"{indent}        _avgDPSDealt = _totalDamageDealt / Mathf.Max(1f, _totalTimeElapsed);")
    lines.append("")
    lines.append(f"{indent}        // Difficulty recommendation")
    lines.append(f"{indent}        if (_winRate > 0.85f)")
    lines.append(f'{indent}            _difficultyRecommendation = "Too Easy";')
    lines.append(f"{indent}        else if (_winRate >= 0.45f)")
    lines.append(f'{indent}            _difficultyRecommendation = "Balanced";')
    lines.append(f"{indent}        else")
    lines.append(f'{indent}            _difficultyRecommendation = "Too Hard";')
    lines.append("")
    lines.append(f"{indent}        _isSimulating = false;")
    lines.append(f"{indent}        _hasResults = true;")
    lines.append(f"{indent}    }}")
    lines.append("")

    # ExportResults
    lines.append(f"{indent}    private void ExportResults()")
    lines.append(f"{indent}    {{")
    lines.append(f'{indent}        string path = EditorUtility.SaveFilePanel("Export Simulation Results", "", "encounter_simulation", "json");')
    lines.append(f'{indent}        if (string.IsNullOrEmpty(path)) return;')
    lines.append("")
    lines.append(f"{indent}        var json = JsonUtility.ToJson(new SimulationResults")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            simulationCount = _simulationCount,")
    lines.append(f"{indent}            winRate = _winRate,")
    lines.append(f"{indent}            avgClearTime = _avgClearTime,")
    lines.append(f"{indent}            stdDevClearTime = _stdDevClearTime,")
    lines.append(f"{indent}            avgPlayerHPRemaining = _avgPlayerHPRemaining,")
    lines.append(f"{indent}            avgDPSDealt = _avgDPSDealt,")
    lines.append(f"{indent}            difficultyRecommendation = _difficultyRecommendation,")
    lines.append(f"{indent}            difficultyScore = _difficultyScore")
    lines.append(f"{indent}        }}, true);")
    lines.append("")
    lines.append(f"{indent}        File.WriteAllText(path, json);")
    lines.append(f'{indent}        Debug.Log($"Simulation results exported to {{path}}");')
    lines.append(f"{indent}    }}")
    lines.append("")

    # Results data class
    lines.append(f"{indent}    [Serializable]")
    lines.append(f"{indent}    private class SimulationResults")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        public int simulationCount;")
    lines.append(f"{indent}        public float winRate;")
    lines.append(f"{indent}        public float avgClearTime;")
    lines.append(f"{indent}        public float stdDevClearTime;")
    lines.append(f"{indent}        public float avgPlayerHPRemaining;")
    lines.append(f"{indent}        public float avgDPSDealt;")
    lines.append(f"{indent}        public string difficultyRecommendation;")
    lines.append(f"{indent}        public float difficultyScore;")
    lines.append(f"{indent}    }}")

    lines.append(f"{indent}}}")
    if ns_close:
        lines.append(ns_close)
    lines.append("#endif")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-10: Boss AI (multi-phase hierarchical FSM)
# ---------------------------------------------------------------------------


def generate_boss_ai_script(
    name: str = "Boss",
    phase_count: int = 3,
    namespace: str = "",
) -> str:
    """Generate multi-phase boss AI MonoBehaviour with hierarchical FSM.

    Creates a boss controller with HP threshold-based phase transitions,
    enrage timer, per-phase attack pattern sets, and queued phase transitions
    that don't interrupt current animations.

    Args:
        name: Boss name (sanitized for C# identifier).
        phase_count: Number of boss phases (2-5). Enrage is always added.
        namespace: Optional C# namespace.

    Returns:
        Complete C# source string.
    """
    safe_name = sanitize_cs_identifier(name)
    safe_str = sanitize_cs_string(name)
    phase_count = max(2, min(5, phase_count))

    ns = _safe_namespace(namespace) if namespace else ""
    ns_open = f"namespace {ns}\n{{" if ns else ""
    ns_close = "}" if ns else ""
    indent = "    " if ns else ""

    lines: list[str] = []
    lines.append("using UnityEngine;")
    lines.append("using UnityEngine.Events;")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    if ns_open:
        lines.append(ns_open)

    # AttackPattern struct
    lines.append(f"{indent}/// <summary>")
    lines.append(f"{indent}/// Defines a single attack in a boss's repertoire.")
    lines.append(f"{indent}/// </summary>")
    lines.append(f"{indent}[Serializable]")
    lines.append(f"{indent}public class AttackPattern")
    lines.append(f"{indent}{{")
    lines.append(f"{indent}    public string name;")
    lines.append(f"{indent}    public float damage = 25f;")
    lines.append(f"{indent}    public float range = 5f;")
    lines.append(f"{indent}    public float cooldown = 3f;")
    lines.append(f"{indent}    public string animTrigger;")
    lines.append(f"{indent}    [HideInInspector] public float lastUsedTime;")
    lines.append(f"{indent}}}")
    lines.append("")

    # Phase attack set
    lines.append(f"{indent}/// <summary>")
    lines.append(f"{indent}/// Attack set for a specific boss phase.")
    lines.append(f"{indent}/// </summary>")
    lines.append(f"{indent}[Serializable]")
    lines.append(f"{indent}public class PhaseAttackSet")
    lines.append(f"{indent}{{")
    lines.append(f"{indent}    public List<AttackPattern> attacks = new List<AttackPattern>();")
    lines.append(f"{indent}}}")
    lines.append("")

    lines.append(f"{indent}/// <summary>")
    lines.append(f"{indent}/// Multi-phase boss AI controller for {safe_str}.")
    lines.append(f"{indent}/// Hierarchical FSM with HP threshold phase transitions,")
    lines.append(f"{indent}/// enrage timer, and per-phase attack pattern sets.")
    lines.append(f"{indent}/// Delegates damage calculation to DamageCalculator.")
    lines.append(f"{indent}/// Generated by VeilBreakers MCP toolkit.")
    lines.append(f"{indent}/// </summary>")
    lines.append(f"{indent}public class VB_BossAI_{safe_name} : MonoBehaviour")
    lines.append(f"{indent}{{")

    # BossPhase enum
    phase_values = ", ".join([f"Phase{i + 1}" for i in range(phase_count)] + ["Enrage"])
    lines.append(f"{indent}    public enum BossPhase {{ {phase_values} }}")
    lines.append("")

    # BossState enum
    lines.append(f"{indent}    public enum BossState {{ Idle, Attacking, PhaseTransition, Stunned, Dead }}")
    lines.append("")

    # HP threshold fields
    lines.append(f"{indent}    [Header(\"Phase Thresholds\")]")
    for i in range(1, phase_count):
        threshold = round(1.0 - (i / phase_count), 2)
        field_name = f"_phase{i + 1}Threshold"
        lines.append(f"{indent}    [SerializeField] private float {field_name} = {threshold}f;")
    lines.append("")

    # Enrage
    lines.append(f"{indent}    [Header(\"Enrage\")]")
    lines.append(f"{indent}    [SerializeField] private float _enrageTimer = 180f;")
    lines.append(f"{indent}    private float _enrageElapsed;")
    lines.append(f"{indent}    private bool _isEnraged;")
    lines.append("")

    # Stats
    lines.append(f"{indent}    [Header(\"Stats\")]")
    lines.append(f"{indent}    [SerializeField] private float _maxHP = 10000f;")
    lines.append(f"{indent}    private float _currentHP;")
    lines.append("")

    # Per-phase multipliers
    lines.append(f"{indent}    [Header(\"Per-Phase Multipliers\")]")
    lines.append(f"{indent}    [SerializeField] private float[] _phaseSpeedMultiplier = new float[]")
    lines.append(f"{indent}    {{")
    speed_vals = ", ".join([f"{1.0 + i * 0.15:.2f}f" for i in range(phase_count)] + ["1.80f"])
    lines.append(f"{indent}        {speed_vals}")
    lines.append(f"{indent}    }};")
    lines.append(f"{indent}    [SerializeField] private float[] _phaseDamageMultiplier = new float[]")
    lines.append(f"{indent}    {{")
    dmg_vals = ", ".join([f"{1.0 + i * 0.2:.2f}f" for i in range(phase_count)] + ["2.00f"])
    lines.append(f"{indent}        {dmg_vals}")
    lines.append(f"{indent}    }};")
    lines.append("")

    # Attack sets
    lines.append(f"{indent}    [Header(\"Attack Patterns\")]")
    lines.append(f"{indent}    [SerializeField] private List<PhaseAttackSet> _phaseAttackSets = new List<PhaseAttackSet>();")
    lines.append("")

    # State
    lines.append(f"{indent}    [Header(\"References\")]")
    lines.append(f"{indent}    [SerializeField] private GameObject[] _fogGates;")
    lines.append(f"{indent}    [SerializeField] private Transform _healthBarUI;")
    lines.append(f"{indent}    private Animator _animator;")
    lines.append("")

    # Runtime state
    lines.append(f"{indent}    // Runtime state")
    lines.append(f"{indent}    private BossPhase _currentPhase = BossPhase.Phase1;")
    lines.append(f"{indent}    private BossPhase _targetPhase = BossPhase.Phase1;")
    lines.append(f"{indent}    private BossState _currentState = BossState.Idle;")
    lines.append(f"{indent}    private bool _pendingTransition;")
    lines.append(f"{indent}    private AttackPattern _currentAttack;")
    lines.append(f"{indent}    private float _attackTimer;")
    lines.append("")

    # Events
    lines.append(f"{indent}    [Header(\"Events\")]")
    lines.append(f"{indent}    public UnityEvent<BossPhase> OnPhaseChanged;")
    lines.append(f"{indent}    public UnityEvent OnBossDeath;")
    lines.append(f"{indent}    public UnityEvent OnEnrage;")
    lines.append("")

    # Start
    lines.append(f"{indent}    private void Start()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _currentHP = _maxHP;")
    lines.append(f"{indent}        _animator = GetComponent<Animator>();")
    lines.append(f"{indent}        _enrageElapsed = 0f;")
    lines.append("")
    lines.append(f"{indent}        // Enable fog gates for arena lockdown")
    lines.append(f"{indent}        if (_fogGates != null)")
    lines.append(f"{indent}            foreach (var gate in _fogGates)")
    lines.append(f"{indent}                if (gate != null) gate.SetActive(true);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # Update (FSM)
    lines.append(f"{indent}    private void Update()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        if (_currentState == BossState.Dead) return;")
    lines.append("")
    lines.append(f"{indent}        // Enrage timer")
    lines.append(f"{indent}        if (!_isEnraged)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            _enrageElapsed += Time.deltaTime;")
    lines.append(f"{indent}            if (_enrageElapsed >= _enrageTimer)")
    lines.append(f"{indent}            {{")
    lines.append(f"{indent}                TriggerEnrage();")
    lines.append(f"{indent}            }}")
    lines.append(f"{indent}        }}")
    lines.append("")
    lines.append(f"{indent}        // Check phase transitions")
    lines.append(f"{indent}        CheckPhaseTransition();")
    lines.append("")
    lines.append(f"{indent}        // State machine")
    lines.append(f"{indent}        switch (_currentState)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            case BossState.Idle:")
    lines.append(f"{indent}                // Process pending transitions in idle state")
    lines.append(f"{indent}                if (_pendingTransition)")
    lines.append(f"{indent}                {{")
    lines.append(f"{indent}                    ExecutePhaseTransition();")
    lines.append(f"{indent}                    break;")
    lines.append(f"{indent}                }}")
    lines.append(f"{indent}                SelectAndExecuteAttack();")
    lines.append(f"{indent}                break;")
    lines.append("")
    lines.append(f"{indent}            case BossState.Attacking:")
    lines.append(f"{indent}                _attackTimer -= Time.deltaTime;")
    lines.append(f"{indent}                if (_attackTimer <= 0)")
    lines.append(f"{indent}                    _currentState = BossState.Idle;")
    lines.append(f"{indent}                break;")
    lines.append("")
    lines.append(f"{indent}            case BossState.PhaseTransition:")
    lines.append(f"{indent}                // Wait for transition animation to complete")
    lines.append(f"{indent}                break;")
    lines.append("")
    lines.append(f"{indent}            case BossState.Stunned:")
    lines.append(f"{indent}                break;")
    lines.append(f"{indent}        }}")
    lines.append(f"{indent}    }}")
    lines.append("")

    # CheckPhaseTransition
    lines.append(f"{indent}    /// <summary>Check HP ratio against phase thresholds.</summary>")
    lines.append(f"{indent}    public void CheckPhaseTransition()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        if (_pendingTransition || _currentState == BossState.Dead) return;")
    lines.append(f"{indent}        float hpRatio = _currentHP / _maxHP;")
    lines.append("")
    # Generate threshold checks in reverse order (lowest first for priority)
    for i in range(phase_count - 1, 0, -1):
        phase_enum = f"BossPhase.Phase{i + 1}"
        field_name = f"_phase{i + 1}Threshold"
        lines.append(f"{indent}        if (hpRatio <= {field_name} && _currentPhase != {phase_enum} && (int)_currentPhase < {i})")
        lines.append(f"{indent}        {{")
        lines.append(f"{indent}            _targetPhase = {phase_enum};")
        lines.append(f"{indent}            _pendingTransition = true;")
        lines.append(f"{indent}            return;")
        lines.append(f"{indent}        }}")
    lines.append(f"{indent}    }}")
    lines.append("")

    # ExecutePhaseTransition
    lines.append(f"{indent}    private void ExecutePhaseTransition()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _currentState = BossState.PhaseTransition;")
    lines.append(f"{indent}        _currentPhase = _targetPhase;")
    lines.append(f"{indent}        _pendingTransition = false;")
    lines.append("")
    lines.append(f"{indent}        // Play transition animation")
    lines.append(f"{indent}        if (_animator != null)")
    lines.append(f'{indent}            _animator.SetTrigger("PhaseTransition");')
    lines.append("")
    lines.append(f"{indent}        OnPhaseChanged?.Invoke(_currentPhase);")
    lines.append("")
    lines.append(f"{indent}        // Return to idle after brief transition")
    lines.append(f"{indent}        Invoke(nameof(EndPhaseTransition), 2f);")
    lines.append(f"{indent}    }}")
    lines.append("")

    lines.append(f"{indent}    private void EndPhaseTransition()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _currentState = BossState.Idle;")
    lines.append(f"{indent}    }}")
    lines.append("")

    # TriggerEnrage
    lines.append(f"{indent}    private void TriggerEnrage()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _isEnraged = true;")
    lines.append(f"{indent}        _currentPhase = BossPhase.Enrage;")
    lines.append(f"{indent}        OnEnrage?.Invoke();")
    lines.append(f"{indent}        OnPhaseChanged?.Invoke(BossPhase.Enrage);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # SelectAndExecuteAttack
    lines.append(f"{indent}    private void SelectAndExecuteAttack()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        int phaseIndex = (int)_currentPhase;")
    lines.append(f"{indent}        if (phaseIndex >= _phaseAttackSets.Count || _phaseAttackSets[phaseIndex].attacks.Count == 0)")
    lines.append(f"{indent}            return;")
    lines.append("")
    lines.append(f"{indent}        var attacks = _phaseAttackSets[phaseIndex].attacks;")
    lines.append(f"{indent}        List<AttackPattern> available = new List<AttackPattern>();")
    lines.append(f"{indent}        foreach (var atk in attacks)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            float cooldown = _isEnraged ? atk.cooldown * 0.5f : atk.cooldown;")
    lines.append(f"{indent}            if (Time.time - atk.lastUsedTime >= cooldown)")
    lines.append(f"{indent}                available.Add(atk);")
    lines.append(f"{indent}        }}")
    lines.append("")
    lines.append(f"{indent}        if (available.Count == 0) return;")
    lines.append("")
    lines.append(f"{indent}        // Select random attack from available set")
    lines.append(f"{indent}        var selected = available[UnityEngine.Random.Range(0, available.Count)];")
    lines.append(f"{indent}        ExecuteAttack(selected);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # ExecuteAttack
    lines.append(f"{indent}    private void ExecuteAttack(AttackPattern attack)")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _currentState = BossState.Attacking;")
    lines.append(f"{indent}        _currentAttack = attack;")
    lines.append(f"{indent}        attack.lastUsedTime = Time.time;")
    lines.append("")
    lines.append(f"{indent}        // Apply phase damage multiplier")
    lines.append(f"{indent}        int phaseIdx = Mathf.Min((int)_currentPhase, _phaseDamageMultiplier.Length - 1);")
    lines.append(f"{indent}        float damage = attack.damage * _phaseDamageMultiplier[phaseIdx];")
    lines.append(f"{indent}        if (_isEnraged) damage *= 1.5f;")
    lines.append("")
    lines.append(f"{indent}        // Delegate damage to DamageCalculator")
    lines.append(f"{indent}        DamageCalculator.CalculateDamage(damage, attack.range);")
    lines.append("")
    lines.append(f"{indent}        // Play attack animation")
    lines.append(f"{indent}        if (_animator != null && !string.IsNullOrEmpty(attack.animTrigger))")
    lines.append(f"{indent}            _animator.SetTrigger(attack.animTrigger);")
    lines.append("")
    lines.append(f"{indent}        _attackTimer = attack.cooldown * 0.5f; // attack duration is half of cooldown")
    lines.append(f"{indent}    }}")
    lines.append("")

    # TakeDamage
    lines.append(f"{indent}    /// <summary>Apply damage to the boss.</summary>")
    lines.append(f"{indent}    public void TakeDamage(float amount)")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        if (_currentState == BossState.Dead) return;")
    lines.append(f"{indent}        _currentHP -= amount;")
    lines.append(f"{indent}        if (_currentHP <= 0)")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            _currentHP = 0;")
    lines.append(f"{indent}            HandleDeath();")
    lines.append(f"{indent}        }}")
    lines.append(f"{indent}    }}")
    lines.append("")

    # HandleDeath
    lines.append(f"{indent}    private void HandleDeath()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        _currentState = BossState.Dead;")
    lines.append(f"{indent}        OnBossDeath?.Invoke();")
    lines.append("")
    lines.append(f"{indent}        // Disable fog gates")
    lines.append(f"{indent}        if (_fogGates != null)")
    lines.append(f"{indent}            foreach (var gate in _fogGates)")
    lines.append(f"{indent}                if (gate != null) gate.SetActive(false);")
    lines.append(f"{indent}    }}")
    lines.append("")

    # Stun
    lines.append(f"{indent}    /// <summary>Stun the boss for a duration.</summary>")
    lines.append(f"{indent}    public void Stun(float duration)")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        if (_currentState == BossState.Dead) return;")
    lines.append(f"{indent}        _currentState = BossState.Stunned;")
    lines.append(f"{indent}        Invoke(nameof(EndStun), duration);")
    lines.append(f"{indent}    }}")
    lines.append("")

    lines.append(f"{indent}    private void EndStun()")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        if (_currentState == BossState.Stunned)")
    lines.append(f"{indent}            _currentState = BossState.Idle;")
    lines.append(f"{indent}    }}")
    lines.append("")

    # Properties
    lines.append(f"{indent}    /// <summary>Current boss HP ratio (0.0 to 1.0).</summary>")
    lines.append(f"{indent}    public float HPRatio => _currentHP / _maxHP;")
    lines.append("")
    lines.append(f"{indent}    /// <summary>Current boss phase.</summary>")
    lines.append(f"{indent}    public BossPhase CurrentPhase => _currentPhase;")
    lines.append("")
    lines.append(f"{indent}    /// <summary>Current speed multiplier for this phase.</summary>")
    lines.append(f"{indent}    public float CurrentSpeedMultiplier")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        get")
    lines.append(f"{indent}        {{")
    lines.append(f"{indent}            int idx = Mathf.Min((int)_currentPhase, _phaseSpeedMultiplier.Length - 1);")
    lines.append(f"{indent}            return _phaseSpeedMultiplier[idx];")
    lines.append(f"{indent}        }}")
    lines.append(f"{indent}    }}")

    lines.append(f"{indent}}}")
    lines.append("")

    # DamageCalculator stub (VB delegation pattern)
    lines.append(f"{indent}/// <summary>")
    lines.append(f"{indent}/// Damage calculation utility (VB delegation pattern).")
    lines.append(f"{indent}/// Boss AI delegates all damage calculation to this static class.")
    lines.append(f"{indent}/// </summary>")
    lines.append(f"{indent}public static class DamageCalculator")
    lines.append(f"{indent}{{")
    lines.append(f"{indent}    public static float CalculateDamage(float baseDamage, float range)")
    lines.append(f"{indent}    {{")
    lines.append(f"{indent}        // Placeholder: actual implementation depends on game systems")
    lines.append(f"{indent}        return baseDamage;")
    lines.append(f"{indent}    }}")
    lines.append(f"{indent}}}")

    if ns_close:
        lines.append(ns_close)

    return "\n".join(lines)
