"""Asset pipeline template generators for Unity project setup and workflow automation.

Covers Git LFS configuration, normal map baking workflow, sprite atlas creation,
sprite animation, Sprite Editor configuration, and AssetPostprocessor scripts
for automated import pipelines.

Exports:
    generate_gitlfs_config              -- IMP-03: .gitattributes for Unity LFS tracking
    generate_gitignore                  -- IMP-03: .gitignore for Unity projects
    generate_normal_map_bake_script     -- IMP-04: Blender Python for high-to-low normal bake
    generate_sprite_atlas_script        -- BUILD-06: C# editor script for SpriteAtlas creation
    generate_sprite_animation_script    -- BUILD-06: C# editor script for sprite AnimationClip
    generate_sprite_editor_config_script -- TWO-03: C# editor script for Sprite Editor config
    generate_asset_postprocessor_script -- PIPE-08: C# AssetPostprocessor with folder rules

Helpers:
    _sanitize_cs_string                 -- C# string literal escaping
    _sanitize_cs_identifier             -- C# identifier sanitization
"""

from __future__ import annotations

import re


# ---------------------------------------------------------------------------
# Sanitization helpers (each template module has its own copy)
# ---------------------------------------------------------------------------


def _sanitize_cs_string(value: str) -> str:
    """Escape a value for safe embedding inside a C# string literal.

    Prevents C# code injection by escaping backslashes, quotes, and
    newlines.
    """
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("\n", "\\n")
    value = value.replace("\r", "\\r")
    return value


def _sanitize_cs_identifier(value: str) -> str:
    """Sanitize a value for use as a C# identifier (class name, method name)."""
    return re.sub(r"[^a-zA-Z0-9_]", "", value)


# C# reserved words (needed by _safe_namespace)
_CS_RESERVED = frozenset({
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
    "checked", "class", "const", "continue", "decimal", "default", "delegate",
    "do", "double", "else", "enum", "event", "explicit", "extern", "false",
    "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
    "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
    "new", "null", "object", "operator", "out", "override", "params", "private",
    "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
    "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
    "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
    "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
})


def _safe_namespace(ns: str) -> str:
    """Sanitize a C# namespace to prevent code injection."""
    sanitized = re.sub(r"[^a-zA-Z0-9_.]", "", ns)
    sanitized = re.sub(r"\.{2,}", ".", sanitized).strip(".")
    if not sanitized:
        return "Generated"
    segments = sanitized.split(".")
    fixed: list[str] = []
    for seg in segments:
        if not seg:
            continue
        if seg[0].isdigit():
            seg = f"_{seg}"
        if seg in _CS_RESERVED:
            seg = f"@{seg}"
        fixed.append(seg)
    return ".".join(fixed) if fixed else "Generated"


# ---------------------------------------------------------------------------
# LFS extension categories
# ---------------------------------------------------------------------------

_LFS_CATEGORIES: list[tuple[str, list[str]]] = [
    ("3D Models", ["fbx", "obj", "blend"]),
    ("Textures", ["png", "psd", "tga", "tif", "exr", "hdr", "jpg"]),
    ("Audio", ["wav", "mp3", "ogg"]),
    ("Fonts", ["ttf", "otf"]),
    ("Video", ["mp4", "mov"]),
    ("Unity binary", ["cubemap", "unitypackage"]),
]

_UNITY_YAML_TYPES: list[str] = [
    "unity", "prefab", "mat", "anim", "controller",
]


# ---------------------------------------------------------------------------
# IMP-03: Git LFS configuration
# ---------------------------------------------------------------------------


def generate_gitlfs_config(
    extra_extensions: list[str] | None = None,
    include_unity_yaml_merge: bool = True,
) -> str:
    """Generate a .gitattributes file content string for a Unity project.

    Tracks binary assets with Git LFS and optionally configures Unity YAML
    merge strategy for scene/prefab/material files.

    NOTE: .asset files are NOT tracked with LFS because Unity's Force Text
    serialization mode stores them as YAML text.

    Args:
        extra_extensions: Additional file extensions to track with LFS
            (with or without leading dot, e.g. [".custom", "dat"]).
        include_unity_yaml_merge: Whether to include Unity YAML merge
            strategy rules for *.unity, *.prefab, *.mat, etc.

    Returns:
        Complete .gitattributes file content.
    """
    lines: list[str] = []
    lines.append("# Generated by VeilBreakers MCP Toolkit")
    lines.append("# Git LFS tracking rules for Unity projects")
    lines.append("")

    # LFS tracking rules by category
    for category, extensions in _LFS_CATEGORIES:
        lines.append(f"# {category}")
        for ext in extensions:
            lines.append(f"*.{ext} filter=lfs diff=lfs merge=lfs -text")
        lines.append("")

    # Extra extensions
    if extra_extensions:
        lines.append("# Custom extensions")
        for ext in extra_extensions:
            ext = ext.lstrip(".")
            lines.append(f"*.{ext} filter=lfs diff=lfs merge=lfs -text")
        lines.append("")

    # Unity YAML merge strategy
    if include_unity_yaml_merge:
        lines.append("# Unity YAML merge strategy")
        for yaml_type in _UNITY_YAML_TYPES:
            lines.append(f"*.{yaml_type} merge=unityyamlmerge eol=lf")
        lines.append("")

    return "\n".join(lines)


def generate_gitignore(
    extra_patterns: list[str] | None = None,
) -> str:
    """Generate a .gitignore file content for Unity projects.

    Includes standard Unity ignore patterns for Library, Temp, Build
    directories, IDE files, and platform-specific entries.

    Args:
        extra_patterns: Additional patterns to add to the .gitignore.

    Returns:
        Complete .gitignore file content.
    """
    sections: list[str] = []

    sections.append("# Generated by VeilBreakers MCP Toolkit")
    sections.append("# Unity .gitignore")
    sections.append("")

    # Unity directories
    sections.append("# Unity generated directories")
    sections.append("/[Ll]ibrary/")
    sections.append("/[Tt]emp/")
    sections.append("/[Oo]bj/")
    sections.append("/[Bb]uild/")
    sections.append("/[Bb]uilds/")
    sections.append("/[Ll]ogs/")
    sections.append("/[Uu]ser[Ss]ettings/")
    sections.append("/[Mm]emoryCaptures/")
    sections.append("/[Rr]ecordings/")
    sections.append("")

    # IDE and build artifacts
    sections.append("# IDE and build artifacts")
    sections.append("*.csproj")
    sections.append("*.sln")
    sections.append("*.suo")
    sections.append("*.tmp")
    sections.append("*.user")
    sections.append("*.userprefs")
    sections.append("*.pidb")
    sections.append("*.booproj")
    sections.append("*.svd")
    sections.append("*.pdb")
    sections.append("*.mdb")
    sections.append("*.opendb")
    sections.append("*.VC.db")
    sections.append("")

    # Build outputs
    sections.append("# Build outputs")
    sections.append("*.apk")
    sections.append("*.aab")
    sections.append("*.unitypackage")
    sections.append("*.app")
    sections.append("")

    # JetBrains Rider
    sections.append("# JetBrains Rider")
    sections.append("/Assets/Plugins/Editor/JetBrains*")
    sections.append("")

    # Crashlytics
    sections.append("# Crashlytics")
    sections.append("crashlytics-build.properties")
    sections.append("")

    # OS-specific
    sections.append("# macOS")
    sections.append(".DS_Store")
    sections.append("*.swp")
    sections.append("")
    sections.append("# Windows")
    sections.append("Thumbs.db")
    sections.append("*.lnk")
    sections.append("")

    # Extra patterns
    if extra_patterns:
        sections.append("# Custom patterns")
        for pattern in extra_patterns:
            sections.append(pattern)
        sections.append("")

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# IMP-04: Normal map baking (Blender Python)
# ---------------------------------------------------------------------------


def generate_normal_map_bake_script(
    high_poly_name: str,
    low_poly_name: str,
    output_image_name: str = "normal_map",
    image_size: int = 2048,
    cage_extrusion: float = 0.1,
    samples: int = 16,
    normal_space: str = "TANGENT",
) -> str:
    """Generate Blender Python code for normal map baking from high to low poly.

    Produces a script that:
    - Selects the low poly object and sets it as active
    - Creates a bake target image
    - Generates a cage mesh from the low poly
    - Sets up material node tree with Image Texture node for baking
    - Configures Cycles render engine and bake settings
    - Executes the bake and saves the result

    This returns Blender Python (bpy), NOT C# -- it is meant to be executed
    via the blender_execute tool.

    Args:
        high_poly_name: Name of the high-poly source object in Blender.
        low_poly_name: Name of the low-poly target object in Blender.
        output_image_name: Name for the baked image (without extension).
        image_size: Resolution of the baked image (width and height).
        cage_extrusion: Distance to extrude cage mesh normals outward.
        samples: Number of Cycles render samples for baking.
        normal_space: Normal map space -- "TANGENT" or "OBJECT".

    Returns:
        Blender Python code string.
    """
    # Validate normal_space
    if normal_space not in ("TANGENT", "OBJECT"):
        normal_space = "TANGENT"

    # Escape user-supplied names for safe embedding in Blender Python strings
    def _escape_bpy_string(s: str) -> str:
        return (
            s.replace("\\", "\\\\")
            .replace("'", "\\'")
            .replace('"', '\\"')
            .replace("\n", "\\n")
        )

    safe_high = _escape_bpy_string(high_poly_name)
    safe_low = _escape_bpy_string(low_poly_name)
    safe_img = _escape_bpy_string(output_image_name)

    script = f'''import bpy
import mathutils

# -----------------------------------------------
# Normal Map Baking: {safe_high} -> {safe_low}
# Generated by VeilBreakers MCP Toolkit
# -----------------------------------------------

# Configuration
HIGH_POLY = "{safe_high}"
LOW_POLY = "{safe_low}"
IMAGE_NAME = "{safe_img}"
IMAGE_SIZE = {image_size}
CAGE_EXTRUSION = {cage_extrusion}
SAMPLES = {samples}
NORMAL_SPACE = "{normal_space}"

# Ensure objects exist
high_obj = bpy.data.objects.get(HIGH_POLY)
low_obj = bpy.data.objects.get(LOW_POLY)

if high_obj is None:
    raise ValueError(f"High-poly object '{{HIGH_POLY}}' not found")
if low_obj is None:
    raise ValueError(f"Low-poly object '{{LOW_POLY}}' not found")

# Set render engine to Cycles (required for baking)
bpy.context.scene.render.engine = "CYCLES"
bpy.context.scene.cycles.samples = SAMPLES

# Create bake target image
if IMAGE_NAME in bpy.data.images:
    bpy.data.images.remove(bpy.data.images[IMAGE_NAME])

bake_image = bpy.data.images.new(
    IMAGE_NAME,
    width=IMAGE_SIZE,
    height=IMAGE_SIZE,
    alpha=False,
    float_buffer=True,
)
bake_image.colorspace_settings.name = "Non-Color"

# Generate cage mesh from low poly
cage_name = LOW_POLY + "_cage"
if cage_name in bpy.data.objects:
    old_cage = bpy.data.objects[cage_name]
    bpy.data.objects.remove(old_cage, do_unlink=True)

# Duplicate low poly to create cage
bpy.ops.object.select_all(action="DESELECT")
low_obj.select_set(True)
bpy.context.view_layer.objects.active = low_obj
bpy.ops.object.duplicate()
cage_obj = bpy.context.active_object
cage_obj.name = cage_name

# Extrude cage along normals
cage_mesh = cage_obj.data
for vertex in cage_mesh.vertices:
    vertex.co += vertex.normal * CAGE_EXTRUSION

# Ensure low poly has a material with an Image Texture node for baking
if len(low_obj.data.materials) == 0:
    mat = bpy.data.materials.new(name=LOW_POLY + "_BakeMat")
    mat.use_nodes = True
    low_obj.data.materials.append(mat)

# Set up Image Texture node on each material of low poly
for mat_slot in low_obj.material_slots:
    mat = mat_slot.material
    if mat is None:
        continue
    mat.use_nodes = True
    nodes = mat.node_tree.nodes

    # Create or find Image Texture node for bake target
    bake_node = None
    for node in nodes:
        if node.type == "TEX_IMAGE" and node.image == bake_image:
            bake_node = node
            break

    if bake_node is None:
        bake_node = nodes.new(type="ShaderNodeTexImage")
        bake_node.name = "BakeTarget"
        bake_node.location = (-300, 300)

    bake_node.image = bake_image

    # Set as active node (Blender bakes to the active image texture node)
    nodes.active = bake_node

# Set up bake configuration
bpy.context.scene.render.bake.use_selected_to_active = True
bpy.context.scene.render.bake.cage_extrusion = CAGE_EXTRUSION
bpy.context.scene.render.bake.normal_space = NORMAL_SPACE

# Select high poly, make low poly active
bpy.ops.object.select_all(action="DESELECT")
high_obj.select_set(True)
low_obj.select_set(True)
bpy.context.view_layer.objects.active = low_obj

# Execute bake
bpy.ops.object.bake(type="NORMAL")

# Save baked image
output_path = "//" + IMAGE_NAME + ".exr"
bake_image.filepath_raw = output_path
bake_image.file_format = "OPEN_EXR"
bake_image.save()

# Clean up cage object
cage_ref = bpy.data.objects.get(cage_name)
if cage_ref:
    bpy.data.objects.remove(cage_ref, do_unlink=True)

# Result
result = {{
    "status": "success",
    "output_path": output_path,
    "image_size": IMAGE_SIZE,
    "bake_settings": {{
        "normal_space": NORMAL_SPACE,
        "cage_extrusion": CAGE_EXTRUSION,
        "samples": SAMPLES,
        "use_selected_to_active": True,
    }},
}}
print(result)
'''
    return script


# ---------------------------------------------------------------------------
# BUILD-06: Sprite Atlas creation
# ---------------------------------------------------------------------------


def generate_sprite_atlas_script(
    atlas_name: str,
    source_folder: str,
    output_path: str = "",
    padding: int = 4,
    enable_tight_packing: bool = True,
    enable_rotation: bool = False,
    max_texture_size: int = 4096,
    srgb: bool = True,
    filter_mode: str = "Bilinear",
    include_in_build: bool = True,
) -> str:
    """Generate a C# editor script that creates a SpriteAtlas asset.

    Uses the V1 SpriteAtlas API (.spriteatlas extension) for stable
    programmatic creation. Configures packing settings, texture settings,
    platform settings, and adds the source folder as a packable object.

    Args:
        atlas_name: Name of the atlas (used for class name and asset name).
        source_folder: Unity folder containing sprites (e.g. "Assets/Art/Sprites/UI").
        output_path: Output path for the .spriteatlas asset. Auto-derived if empty.
        padding: Padding between packed sprites in pixels.
        enable_tight_packing: Whether to enable tight mesh packing.
        enable_rotation: Whether to allow sprite rotation during packing.
        max_texture_size: Maximum texture size for the atlas.
        srgb: Whether the atlas texture uses sRGB color space.
        filter_mode: Texture filter mode ("Bilinear", "Point", or "Trilinear").
        include_in_build: Whether to include the atlas in builds.

    Returns:
        Complete C# editor script source.
    """
    safe_name = _sanitize_cs_identifier(atlas_name)
    safe_folder = _sanitize_cs_string(source_folder)

    if not output_path:
        output_path = f"Assets/Art/Atlases/{_sanitize_cs_identifier(atlas_name)}.spriteatlas"
    safe_output = _sanitize_cs_string(output_path)

    # Ensure .spriteatlas extension (V1 API)
    if not safe_output.endswith(".spriteatlas"):
        safe_output = safe_output.rsplit(".", 1)[0] + ".spriteatlas"

    tight_str = "true" if enable_tight_packing else "false"
    rotation_str = "true" if enable_rotation else "false"
    srgb_str = "true" if srgb else "false"
    include_str = "true" if include_in_build else "false"

    # Map filter mode string to Unity enum
    filter_map = {
        "Point": "FilterMode.Point",
        "Bilinear": "FilterMode.Bilinear",
        "Trilinear": "FilterMode.Trilinear",
    }
    filter_enum = filter_map.get(filter_mode, "FilterMode.Bilinear")

    return f'''using UnityEditor;
using UnityEditor.U2D;
using UnityEngine;
using UnityEngine.U2D;
using System.IO;

public class VeilBreakers_Create{safe_name}Atlas
{{
    [MenuItem("VeilBreakers/Assets/Create {safe_name} Atlas")]
    public static void Execute()
    {{
        // Ensure output directory exists
        string outputDir = Path.GetDirectoryName("{safe_output}");
        if (!string.IsNullOrEmpty(outputDir) && !AssetDatabase.IsValidFolder(outputDir))
        {{
            string[] parts = outputDir.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {{
                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }}
        }}

        // Create atlas (V1 API)
        var atlas = new SpriteAtlas();

        // Configure packing settings
        var packSettings = new SpriteAtlasPackingSettings
        {{
            padding = {padding},
            enableTightPacking = {tight_str},
            enableRotation = {rotation_str},
        }};
        atlas.SetPackingSettings(packSettings);

        // Configure texture settings
        var texSettings = new SpriteAtlasTextureSettings
        {{
            sRGB = {srgb_str},
            filterMode = {filter_enum},
        }};
        atlas.SetTextureSettings(texSettings);

        // Configure platform settings
        var platSettings = atlas.GetPlatformSettings("DefaultTexturePlatform");
        platSettings.overridden = true;
        platSettings.maxTextureSize = {max_texture_size};
        atlas.SetPlatformSettings(platSettings);

        // Add source folder as packable
        var folder = AssetDatabase.LoadAssetAtPath<Object>("{safe_folder}");
        if (folder != null)
        {{
            atlas.Add(new[] {{ folder }});
        }}
        else
        {{
            Debug.LogWarning("Source folder not found: {safe_folder}");
        }}

        // Set include in build
        atlas.SetIncludeInBuild({include_str});

        // Save atlas
        AssetDatabase.CreateAsset(atlas, "{safe_output}");
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        // Write result
        string json = "{{\\"status\\": \\"success\\", \\"atlas_path\\": \\"" + "{safe_output}".Replace("\\\\", "/") + "\\", \\"source\\": \\"" + "{safe_folder}".Replace("\\\\", "/") + "\\"}}";
        File.WriteAllText(
            Path.Combine(Application.dataPath, "../Temp/vb_result.json"),
            json
        );

        Debug.Log("SpriteAtlas created: {safe_output}");
    }}
}}
'''


# ---------------------------------------------------------------------------
# BUILD-06: Sprite animation from frames
# ---------------------------------------------------------------------------


def generate_sprite_animation_script(
    clip_name: str,
    sprite_folder: str,
    frame_rate: int = 12,
    loop: bool = True,
    output_path: str = "",
) -> str:
    """Generate a C# editor script that creates an AnimationClip from sprite frames.

    Loads all sprites from a folder, sorts them alphabetically (frame order),
    and creates an AnimationClip with ObjectReferenceKeyframes bound to
    SpriteRenderer.m_Sprite.

    Args:
        clip_name: Name of the animation clip.
        sprite_folder: Unity folder containing individual frame sprites.
        frame_rate: Frames per second for the animation.
        loop: Whether the animation should loop.
        output_path: Output path for the .anim asset. Auto-derived if empty.

    Returns:
        Complete C# editor script source.
    """
    safe_name = _sanitize_cs_identifier(clip_name)
    safe_folder = _sanitize_cs_string(sprite_folder)

    if not output_path:
        output_path = f"Assets/Art/Animations/{_sanitize_cs_identifier(clip_name)}.anim"
    safe_output = _sanitize_cs_string(output_path)

    wrap_mode = "WrapMode.Loop" if loop else "WrapMode.Once"
    loop_str = "true" if loop else "false"

    return f'''using UnityEditor;
using UnityEngine;
using System.IO;
using System.Linq;

public class VeilBreakers_Create{safe_name}Anim
{{
    [MenuItem("VeilBreakers/Assets/Create {safe_name} Animation")]
    public static void Execute()
    {{
        // Find all sprites in the folder
        string[] guids = AssetDatabase.FindAssets("t:Sprite", new[] {{ "{safe_folder}" }});

        if (guids.Length == 0)
        {{
            Debug.LogError("No sprites found in: {safe_folder}");
            return;
        }}

        // Load and sort sprites by name (alphabetical = frame order)
        var sprites = guids
            .Select(g => AssetDatabase.GUIDToAssetPath(g))
            .OrderBy(p => p)
            .Select(p => AssetDatabase.LoadAssetAtPath<Sprite>(p))
            .Where(s => s != null)
            .ToArray();

        if (sprites.Length == 0)
        {{
            Debug.LogError("Failed to load sprites from: {safe_folder}");
            return;
        }}

        // Create animation clip
        var clip = new AnimationClip();
        clip.frameRate = {frame_rate};
        clip.name = "{safe_name}";

        // Create keyframes
        var keyframes = new ObjectReferenceKeyframe[sprites.Length];
        for (int i = 0; i < sprites.Length; i++)
        {{
            keyframes[i] = new ObjectReferenceKeyframe
            {{
                time = (float)i / {frame_rate}f,
                value = sprites[i],
            }};
        }}

        // Bind to SpriteRenderer.m_Sprite
        var binding = EditorCurveBinding.PPtrCurve(
            "",
            typeof(SpriteRenderer),
            "m_Sprite"
        );
        AnimationUtility.SetObjectReferenceCurve(clip, binding, keyframes);

        // Set loop / wrap mode
        var settings = AnimationUtility.GetAnimationClipSettings(clip);
        settings.loopTime = {loop_str};
        AnimationUtility.SetAnimationClipSettings(clip, settings);
        clip.wrapMode = {wrap_mode};

        // Ensure output directory exists
        string outputDir = Path.GetDirectoryName("{safe_output}");
        if (!string.IsNullOrEmpty(outputDir) && !AssetDatabase.IsValidFolder(outputDir))
        {{
            string[] parts = outputDir.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {{
                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }}
        }}

        // Save clip
        AssetDatabase.CreateAsset(clip, "{safe_output}");
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        // Write result
        string json = "{{\\"status\\": \\"success\\", \\"clip_path\\": \\"" + "{safe_output}".Replace("\\\\", "/") + "\\", \\"frame_count\\": " + sprites.Length + ", \\"frame_rate\\": {frame_rate}, \\"loop\\": {loop_str}}}";
        File.WriteAllText(
            Path.Combine(Application.dataPath, "../Temp/vb_result.json"),
            json
        );

        Debug.Log($"AnimationClip created: {safe_output} ({{sprites.Length}} frames at {frame_rate} fps)");
    }}
}}
'''


# ---------------------------------------------------------------------------
# TWO-03: Sprite Editor configuration
# ---------------------------------------------------------------------------


def generate_sprite_editor_config_script(
    sprite_path: str,
    pivot: tuple[float, float] | None = None,
    border: tuple[int, int, int, int] | None = None,
    pixels_per_unit: int = 100,
    sprite_mode: int = 1,
    custom_physics_shape: list[list[tuple[float, float]]] | None = None,
) -> str:
    """Generate a C# editor script that configures Sprite Editor features.

    Applies TextureImporter settings for pivot, 9-slice border, pixels per unit,
    sprite mode, and custom physics shapes.

    Args:
        sprite_path: Path to the sprite asset (e.g. "Assets/Art/Sprites/icon.png").
        pivot: Custom pivot point as (x, y) normalized 0-1. None for default center.
        border: 9-slice border as (left, bottom, right, top). None to skip.
        pixels_per_unit: Sprite pixels per unit.
        sprite_mode: 0=none, 1=single, 2=multiple.
        custom_physics_shape: List of polygon outlines for physics shapes.
            Each outline is a list of (x, y) tuples.

    Returns:
        Complete C# editor script source.
    """
    safe_path = _sanitize_cs_string(sprite_path)
    safe_class = _sanitize_cs_identifier(
        sprite_path.rsplit("/", 1)[-1].rsplit(".", 1)[0]
    )

    # Alignment: 0=Center, 9=Custom when pivot provided
    alignment = 9 if pivot is not None else 0

    # Build pivot code
    pivot_code = ""
    if pivot is not None:
        pivot_code = f"""
        // Set custom pivot
        importer.spritePivot = new Vector2({pivot[0]}f, {pivot[1]}f);
        importer.spriteAlignment = {alignment};"""

    # Build border code
    border_code = ""
    if border is not None:
        border_code = f"""
        // Set 9-slice border (left, bottom, right, top)
        importer.spriteBorder = new Vector4({border[0]}f, {border[1]}f, {border[2]}f, {border[3]}f);"""

    # Build physics shape code
    physics_code = ""
    if custom_physics_shape is not None:
        shape_entries: list[str] = []
        for outline_idx, outline in enumerate(custom_physics_shape):
            points = ", ".join(
                f"new Vector2({x}f, {y}f)" for x, y in outline
            )
            shape_entries.append(
                f"            importer.SetPhysicsShape(0, {outline_idx}, "
                f"new[] {{ {points} }});"
            )
        physics_code = "\n        // Set custom physics shapes\n" + "\n".join(
            shape_entries
        )

    return f'''using UnityEditor;
using UnityEngine;
using System.IO;

public class VeilBreakers_ConfigSprite{safe_class}
{{
    [MenuItem("VeilBreakers/Assets/Configure Sprite {safe_class}")]
    public static void Execute()
    {{
        // Load TextureImporter
        var importer = AssetImporter.GetAtPath("{safe_path}") as TextureImporter;
        if (importer == null)
        {{
            Debug.LogError("TextureImporter not found for: {safe_path}");
            return;
        }}

        // Configure sprite settings
        importer.textureType = TextureImporterType.Sprite;
        importer.spriteImportMode = (SpriteImportMode){sprite_mode};
        importer.spritePixelsPerUnit = {pixels_per_unit};
{pivot_code}
{border_code}
{physics_code}

        // Apply and reimport
        importer.SaveAndReimport();

        // Write result
        string json = "{{\\"status\\": \\"success\\", \\"sprite_path\\": \\"" + "{safe_path}".Replace("\\\\", "/") + "\\", \\"pixels_per_unit\\": {pixels_per_unit}, \\"sprite_mode\\": {sprite_mode}}}";
        File.WriteAllText(
            Path.Combine(Application.dataPath, "../Temp/vb_result.json"),
            json
        );

        Debug.Log("Sprite configured: {safe_path}");
    }}
}}
'''


# ---------------------------------------------------------------------------
# PIPE-08: AssetPostprocessor script generation
# ---------------------------------------------------------------------------


def generate_asset_postprocessor_script(
    processor_name: str,
    version: int = 1,
    texture_rules: list[dict] | None = None,
    model_rules: list[dict] | None = None,
    audio_rules: list[dict] | None = None,
    namespace: str = "VeilBreakers.Editor",
) -> str:
    """Generate a C# AssetPostprocessor script with folder-convention-based rules.

    Creates a postprocessor that auto-configures import settings based on
    folder patterns. Uses OnPreprocess callbacks (NOT OnPostprocess) to avoid
    infinite reimport loops. Includes GetVersion() override for reimport
    detection.

    Args:
        processor_name: Class name for the postprocessor.
        version: Postprocessor version number (increment when changing logic).
        texture_rules: List of dicts with 'folder_pattern' and 'settings_dict'
            for texture import rules. Settings can include: textureType,
            maxTextureSize, textureCompression, sRGBTexture, mipmapEnabled,
            spritePixelsPerUnit, filterMode.
        model_rules: List of dicts with 'folder_pattern' and 'settings_dict'
            for model import rules. Settings can include: importMaterials,
            importAnimation, animationType, meshCompression, globalScale.
        audio_rules: List of dicts with 'folder_pattern' and 'settings_dict'
            for audio import rules. Settings can include: forceToMono,
            loadInBackground, compressionFormat.
        namespace: C# namespace for the generated class.

    Returns:
        Complete C# AssetPostprocessor script source.
    """
    safe_name = _sanitize_cs_identifier(processor_name)
    safe_ns = _sanitize_cs_identifier(namespace.replace(".", "_"))
    clean_ns = _safe_namespace(namespace)

    # Build texture rules code
    texture_method = _build_preprocess_method(
        "OnPreprocessTexture",
        "TextureImporter",
        texture_rules,
        _TEXTURE_SETTING_MAP,
    )

    # Build model rules code
    model_method = _build_preprocess_method(
        "OnPreprocessModel",
        "ModelImporter",
        model_rules,
        _MODEL_SETTING_MAP,
    )

    # Build audio rules code
    audio_method = _build_preprocess_method(
        "OnPreprocessAudio",
        "AudioImporter",
        audio_rules,
        _AUDIO_SETTING_MAP,
    )

    return f'''using UnityEditor;
using UnityEngine;

namespace {clean_ns}
{{
    /// <summary>
    /// Auto-configures import settings based on folder conventions.
    /// Generated by VeilBreakers MCP Toolkit.
    /// </summary>
    public class {safe_name} : AssetPostprocessor
    {{
        /// <summary>
        /// Version number for reimport detection. Increment when changing
        /// processor logic to force re-processing of already-imported assets.
        /// </summary>
        public override uint GetVersion() {{ return {version}; }}

{texture_method}
{model_method}
{audio_method}
    }}
}}
'''


# ---------------------------------------------------------------------------
# AssetPostprocessor setting mapping helpers
# ---------------------------------------------------------------------------

# Maps setting names to (C# property, value formatter) tuples.
# The formatter converts Python values to C# code strings.

_TEXTURE_SETTING_MAP: dict[str, tuple[str, callable]] = {
    "textureType": (
        "importer.textureType",
        lambda v: f"TextureImporterType.{v}",
    ),
    "maxTextureSize": (
        "importer.maxTextureSize",
        lambda v: str(v),
    ),
    "textureCompression": (
        "importer.textureCompression",
        lambda v: f"TextureImporterCompression.{v}",
    ),
    "sRGBTexture": (
        "importer.sRGBTexture",
        lambda v: "true" if v else "false",
    ),
    "mipmapEnabled": (
        "importer.mipmapEnabled",
        lambda v: "true" if v else "false",
    ),
    "spritePixelsPerUnit": (
        "importer.spritePixelsPerUnit",
        lambda v: str(v),
    ),
    "filterMode": (
        "importer.filterMode",
        lambda v: f"FilterMode.{v}",
    ),
}

_MODEL_SETTING_MAP: dict[str, tuple[str, callable]] = {
    "importMaterials": (
        "importer.importMaterials",
        lambda v: "true" if v else "false",
    ),
    "importAnimation": (
        "importer.importAnimation",
        lambda v: "true" if v else "false",
    ),
    "animationType": (
        "importer.animationType",
        lambda v: f"ModelImporterAnimationType.{v}",
    ),
    "meshCompression": (
        "importer.meshCompression",
        lambda v: f"ModelImporterMeshCompression.{v}",
    ),
    "globalScale": (
        "importer.globalScale",
        lambda v: f"{v}f",
    ),
}

_AUDIO_SETTING_MAP: dict[str, tuple[str, callable]] = {
    "forceToMono": (
        "importer.forceToMono",
        lambda v: "true" if v else "false",
    ),
    "loadInBackground": (
        "importer.loadInBackground",
        lambda v: "true" if v else "false",
    ),
    "compressionFormat": (
        "importer.defaultSampleSettings.compressionFormat",
        lambda v: f"AudioCompressionFormat.{v}",
    ),
}


def _build_preprocess_method(
    method_name: str,
    importer_type: str,
    rules: list[dict] | None,
    setting_map: dict[str, tuple[str, callable]],
) -> str:
    """Build a single OnPreprocess* method body from folder rules.

    Args:
        method_name: C# method name (e.g. "OnPreprocessTexture").
        importer_type: C# importer cast type (e.g. "TextureImporter").
        rules: List of rule dicts with folder_pattern and settings_dict.
        setting_map: Mapping from setting names to (property, formatter).

    Returns:
        Indented C# method block.
    """
    if not rules:
        # Still generate the method stub for completeness
        return f"""        void {method_name}()
        {{
            // No rules configured for {importer_type}
        }}
"""

    lines: list[str] = []
    lines.append(f"        void {method_name}()")
    lines.append("        {")
    lines.append(f"            var importer = ({importer_type})assetImporter;")
    lines.append("")

    first = True
    for rule in rules:
        folder_pattern = rule.get("folder_pattern", "")
        settings = rule.get("settings_dict", {})
        safe_pattern = _sanitize_cs_string(folder_pattern)

        keyword = "if" if first else "else if"
        lines.append(
            f'            {keyword} (assetPath.Contains("{safe_pattern}"))'
        )
        lines.append("            {")
        lines.append(f'                // Rules for "{safe_pattern}" folder')

        for setting_name, setting_value in settings.items():
            if setting_name in setting_map:
                prop, formatter = setting_map[setting_name]
                cs_value = formatter(setting_value)
                lines.append(f"                {prop} = {cs_value};")

        lines.append("            }")
        first = False

    lines.append("        }")
    lines.append("")

    return "\n".join(lines)
