"""VeilBreakers-specific combat system C# template generators.

Each function returns a complete C# source string for a runtime MonoBehaviour
or static utility class. These are placed in the Unity project's
Assets/Scripts/Runtime/ directory -- they are NOT editor scripts and must
NEVER reference the UnityEditor namespace.

CRITICAL DESIGN PRINCIPLE: These generators produce WIRING code --
MonoBehaviours that call into existing static utility classes. They do NOT
reimplement brand effectiveness matrices, synergy calculations, corruption
formulas, or damage pipelines. The generated code references existing
VeilBreakers classes by name:
  - BrandSystem.GetEffectiveness()
  - SynergySystem.GetSynergyTier() / GetDamageBonus()
  - CorruptionSystem.GetStatMultiplier() / GetCorruptionState()
  - DamageCalculator.Calculate()
  - EventBus (various events)

Exports:
    generate_player_combat_script      -- VB-01: Player combat controller with FSM
    generate_ability_system_script     -- VB-02: Brand-specific ability system
    generate_synergy_engine_script     -- VB-03: Synergy wiring (delegates to SynergySystem)
    generate_corruption_gameplay_script -- VB-04: Corruption effects (delegates to CorruptionSystem)
    generate_xp_leveling_script        -- VB-05: XP/leveling with EventBus integration
    generate_currency_system_script    -- VB-06: Multi-currency system
    generate_damage_type_script        -- VB-07: Brand-specific damage types (delegates to BrandSystem)
"""

from __future__ import annotations

import re

from ._cs_sanitize import sanitize_cs_string


# ---------------------------------------------------------------------------
# C# reserved words
# ---------------------------------------------------------------------------

_CS_RESERVED = frozenset({
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
    "checked", "class", "const", "continue", "decimal", "default", "delegate",
    "do", "double", "else", "enum", "event", "explicit", "extern", "false",
    "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
    "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
    "new", "null", "object", "operator", "out", "override", "params", "private",
    "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
    "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
    "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
    "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
})


def _safe_namespace(ns: str) -> str:
    """Sanitize a C# namespace to prevent code injection.

    Valid C# namespaces allow only letters, digits, underscores, and dots.
    Strips everything else. Segments starting with a digit get a ``_``
    prefix, and segments that are C# reserved words get an ``@`` prefix.

    Args:
        ns: Raw namespace string.

    Returns:
        Sanitized namespace string safe for C# ``namespace`` declarations.
    """
    sanitized = re.sub(r"[^a-zA-Z0-9_.]", "", ns)
    # Strip leading/trailing dots and collapse consecutive dots
    sanitized = re.sub(r"\.{2,}", ".", sanitized).strip(".")
    if not sanitized:
        return "Generated"
    # Validate each segment: fix leading-digit and reserved-word segments
    segments = sanitized.split(".")
    fixed: list[str] = []
    for seg in segments:
        if not seg:
            continue
        if seg[0].isdigit():
            seg = f"_{seg}"
        if seg in _CS_RESERVED:
            seg = f"@{seg}"
        fixed.append(seg)
    return ".".join(fixed) or "Generated"


# ---------------------------------------------------------------------------
# VB-01: Player combat controller (FSM with combos, dodge, block)
# ---------------------------------------------------------------------------


def generate_player_combat_script(
    light_combo_count: int = 3,
    heavy_combo_count: int = 2,
    dodge_iframe_duration: float = 0.2,
    dodge_distance: float = 4.0,
    block_stamina_drain: float = 10.0,
    stamina_max: float = 100.0,
    stamina_regen_rate: float = 15.0,
    namespace: str = "VeilBreakers.Combat",
    combat_mode: str = "realtime",
) -> str:
    """Generate C# runtime MonoBehaviour for a player combat controller.

    NOTE: This generates a REAL-TIME action combat controller for overworld/exploration combat.
    VeilBreakers also has a TURN-BASED battle system (BattleManager/Combatant) for structured encounters.
    This controller is designed for the overworld, NOT as a replacement for the existing turn-based system.
    Use this for real-time overworld encounters; the existing BattleManager handles structured battles.

    When ``combat_mode`` is ``"turnbased"``, generates a turn-based combat wrapper
    (VB_TurnBasedCombat) that delegates to BattleManager instead of the real-time FSM.

    Produces an FSM-based combat system with light/heavy attack combos,
    dodge with i-frames, block with stamina drain, hit reactions, and
    stamina management. Integrates with existing Combatant, DamageCalculator,
    and EventBus systems.

    Args:
        light_combo_count: Number of hits in the light attack combo chain.
        heavy_combo_count: Number of hits in the heavy attack combo chain.
        dodge_iframe_duration: Duration of invincibility frames during dodge.
        dodge_distance: Distance covered by a dodge roll.
        block_stamina_drain: Stamina consumed per blocked hit.
        stamina_max: Maximum stamina pool.
        stamina_regen_rate: Stamina regenerated per second when idle.
        namespace: C# namespace for the generated class.
        combat_mode: ``"realtime"`` (default) for overworld action combat,
            or ``"turnbased"`` for structured turn-based encounters.

    Returns:
        Complete C# source string.
    """
    if combat_mode == "turnbased":
        return _generate_turnbased_combat_script(namespace=namespace)

    lines = []
    lines.append("using UnityEngine;")
    lines.append("using VeilBreakers.Combat;")
    lines.append("using VeilBreakers.Core;")
    lines.append("using VeilBreakers.Systems;")
    lines.append("using VeilBreakers.Data;")
    lines.append("")
    lines.append("namespace " + _safe_namespace(namespace))
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Player combat controller with FSM state machine.")
    lines.append("    /// Supports light/heavy attack combos, dodge with i-frames,")
    lines.append("    /// block with stamina drain, and hit reactions.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public class VB_PlayerCombat : MonoBehaviour")
    lines.append("    {")
    lines.append("        /// <summary>Combat state machine states.</summary>")
    lines.append("        public enum CombatState")
    lines.append("        {")
    lines.append("            Idle,")
    lines.append("            LightAttack,")
    lines.append("            HeavyAttack,")
    lines.append("            Dodge,")
    lines.append("            Block,")
    lines.append("            HitReaction,")
    lines.append("            Dead")
    lines.append("        }")
    lines.append("")
    lines.append("        [Header(\"Combo Settings\")]")
    lines.append("        public int lightComboCount = " + str(light_combo_count) + ";")
    lines.append("        public int heavyComboCount = " + str(heavy_combo_count) + ";")
    lines.append("        public float comboWindowDuration = 0.5f;")
    lines.append("        public float heavyDamageMultiplier = 1.75f;")
    lines.append("")
    lines.append("        [Header(\"Dodge\")]")
    lines.append("        public float dodgeIFrameDuration = " + str(dodge_iframe_duration) + "f;")
    lines.append("        public float dodgeDistance = " + str(dodge_distance) + "f;")
    lines.append("        public float dodgeDuration = 0.4f;")
    lines.append("        public float dodgeStaminaCost = 20f;")
    lines.append("")
    lines.append("        [Header(\"Block\")]")
    lines.append("        public float blockDamageReduction = 0.5f;")
    lines.append("        public float blockStaminaDrain = " + str(block_stamina_drain) + "f;")
    lines.append("")
    lines.append("        [Header(\"Stamina\")]")
    lines.append("        public float staminaMax = " + str(stamina_max) + "f;")
    lines.append("        public float staminaCurrent;")
    lines.append("        public float staminaRegenRate = " + str(stamina_regen_rate) + "f;")
    lines.append("        public float staminaRegenDelay = 1.0f;")
    lines.append("")
    lines.append("        [Header(\"Hit Reaction\")]")
    lines.append("        public float hitReactionDuration = 0.3f;")
    lines.append("")
    lines.append("        // Runtime state")
    lines.append("        private CombatState _currentState = CombatState.Idle;")
    lines.append("        private int _currentComboIndex = 0;")
    lines.append("        private float _comboTimer = 0f;")
    lines.append("        private float _stateTimer = 0f;")
    lines.append("        private float _staminaRegenTimer = 0f;")
    lines.append("        private bool _isInvincible = false;")
    lines.append("        private float _iFrameTimer = 0f;")
    lines.append("")
    lines.append("        private Vector3 _dodgeDirection;")
    lines.append("        private float _dodgeSpeed;")
    lines.append("")
    lines.append("        // Cached components")
    lines.append("        private Combatant _combatant;")
    lines.append("        private Animator _animator;")
    lines.append("        private CharacterController _characterController;")
    lines.append("")
    lines.append("        /// <summary>Current combat state (read-only).</summary>")
    lines.append("        public CombatState CurrentState => _currentState;")
    lines.append("")
    lines.append("        /// <summary>Whether the player has active i-frames.</summary>")
    lines.append("        public bool IsInvincible => _isInvincible;")
    lines.append("")
    lines.append("        private void Start()")
    lines.append("        {")
    lines.append("            _combatant = GetComponent<Combatant>();")
    lines.append("            if (_combatant == null)")
    lines.append("                Debug.LogWarning(\"[VB_PlayerCombat] No Combatant component found on \" + gameObject.name + \". Combat damage will not function.\");")
    lines.append("            _animator = GetComponent<Animator>();")
    lines.append("            _characterController = GetComponent<CharacterController>();")
    lines.append("            staminaCurrent = staminaMax;")
    lines.append("        }")
    lines.append("")
    lines.append("        private void Update()")
    lines.append("        {")
    lines.append("            UpdateIFrames();")
    lines.append("            UpdateStamina();")
    lines.append("")
    lines.append("            switch (_currentState)")
    lines.append("            {")
    lines.append("                case CombatState.Idle:")
    lines.append("                    HandleIdleState();")
    lines.append("                    break;")
    lines.append("                case CombatState.LightAttack:")
    lines.append("                    HandleLightAttackState();")
    lines.append("                    break;")
    lines.append("                case CombatState.HeavyAttack:")
    lines.append("                    HandleHeavyAttackState();")
    lines.append("                    break;")
    lines.append("                case CombatState.Dodge:")
    lines.append("                    HandleDodgeState();")
    lines.append("                    break;")
    lines.append("                case CombatState.Block:")
    lines.append("                    HandleBlockState();")
    lines.append("                    break;")
    lines.append("                case CombatState.HitReaction:")
    lines.append("                    HandleHitReactionState();")
    lines.append("                    break;")
    lines.append("                case CombatState.Dead:")
    lines.append("                    break;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        // =================================================================")
    lines.append("        // State handlers")
    lines.append("        // =================================================================")
    lines.append("")
    lines.append("        private void HandleIdleState()")
    lines.append("        {")
    lines.append("            // Combo timeout reset")
    lines.append("            if (_comboTimer > 0f)")
    lines.append("            {")
    lines.append("                _comboTimer -= Time.deltaTime;")
    lines.append("                if (_comboTimer <= 0f)")
    lines.append("                    _currentComboIndex = 0;")
    lines.append("            }")
    lines.append("")
    lines.append("            if (GetDodgeInput() && staminaCurrent >= dodgeStaminaCost)")
    lines.append("                EnterDodge();")
    lines.append("            else if (GetBlockInput())")
    lines.append("                EnterBlock();")
    lines.append("            else if (GetHeavyAttackInput())")
    lines.append("                EnterHeavyAttack();")
    lines.append("            else if (GetLightAttackInput())")
    lines.append("                EnterLightAttack();")
    lines.append("        }")
    lines.append("")
    lines.append("        private void HandleLightAttackState()")
    lines.append("        {")
    lines.append("            _stateTimer -= Time.deltaTime;")
    lines.append("            if (_stateTimer <= 0f)")
    lines.append("            {")
    lines.append("                // Allow combo chain input")
    lines.append("                if (GetLightAttackInput() && _currentComboIndex < lightComboCount)")
    lines.append("                {")
    lines.append("                    _currentComboIndex++;")
    lines.append("                    PerformLightAttack();")
    lines.append("                }")
    lines.append("                else")
    lines.append("                {")
    lines.append("                    _comboTimer = comboWindowDuration;")
    lines.append("                    TransitionTo(CombatState.Idle);")
    lines.append("                }")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        private void HandleHeavyAttackState()")
    lines.append("        {")
    lines.append("            _stateTimer -= Time.deltaTime;")
    lines.append("            if (_stateTimer <= 0f)")
    lines.append("            {")
    lines.append("                if (GetHeavyAttackInput() && _currentComboIndex < heavyComboCount)")
    lines.append("                {")
    lines.append("                    _currentComboIndex++;")
    lines.append("                    PerformHeavyAttack();")
    lines.append("                }")
    lines.append("                else")
    lines.append("                {")
    lines.append("                    _comboTimer = comboWindowDuration;")
    lines.append("                    TransitionTo(CombatState.Idle);")
    lines.append("                }")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        private void HandleDodgeState()")
    lines.append("        {")
    lines.append("            _stateTimer -= Time.deltaTime;")
    lines.append("")
    lines.append("            // Spread dodge movement across frames")
    lines.append("            if (_characterController != null)")
    lines.append("                _characterController.Move(_dodgeDirection * _dodgeSpeed * Time.deltaTime);")
    lines.append("")
    lines.append("            if (_stateTimer <= 0f)")
    lines.append("                TransitionTo(CombatState.Idle);")
    lines.append("        }")
    lines.append("")
    lines.append("        private void HandleBlockState()")
    lines.append("        {")
    lines.append("            if (!GetBlockInput() || staminaCurrent <= 0f)")
    lines.append("                TransitionTo(CombatState.Idle);")
    lines.append("        }")
    lines.append("")
    lines.append("        private void HandleHitReactionState()")
    lines.append("        {")
    lines.append("            _stateTimer -= Time.deltaTime;")
    lines.append("            if (_stateTimer <= 0f)")
    lines.append("                TransitionTo(CombatState.Idle);")
    lines.append("        }")
    lines.append("")
    lines.append("        // =================================================================")
    lines.append("        // State transitions")
    lines.append("        // =================================================================")
    lines.append("")
    lines.append("        private void EnterLightAttack()")
    lines.append("        {")
    lines.append("            _currentComboIndex = 1;")
    lines.append("            TransitionTo(CombatState.LightAttack);")
    lines.append("            PerformLightAttack();")
    lines.append("        }")
    lines.append("")
    lines.append("        private void EnterHeavyAttack()")
    lines.append("        {")
    lines.append("            _currentComboIndex = 1;")
    lines.append("            TransitionTo(CombatState.HeavyAttack);")
    lines.append("            PerformHeavyAttack();")
    lines.append("        }")
    lines.append("")
    lines.append("        private void EnterDodge()")
    lines.append("        {")
    lines.append("            staminaCurrent -= dodgeStaminaCost;")
    lines.append("            _staminaRegenTimer = staminaRegenDelay;")
    lines.append("            _isInvincible = true;")
    lines.append("            _iFrameTimer = dodgeIFrameDuration;")
    lines.append("            _stateTimer = dodgeDuration;")
    lines.append("            TransitionTo(CombatState.Dodge);")
    lines.append("")
    lines.append("            // Compute dodge direction and speed for gradual movement")
    lines.append("            _dodgeDirection = GetMoveDirection();")
    lines.append("            if (_dodgeDirection.sqrMagnitude < 0.01f)")
    lines.append("                _dodgeDirection = transform.forward;")
    lines.append("            _dodgeDirection = _dodgeDirection.normalized;")
    lines.append("            _dodgeSpeed = dodgeDuration > 0f ? dodgeDistance / dodgeDuration : dodgeDistance;")
    lines.append("")
    lines.append("            if (_animator != null)")
    lines.append("                _animator.SetTrigger(\"Dodge\");")
    lines.append("        }")
    lines.append("")
    lines.append("        private void EnterBlock()")
    lines.append("        {")
    lines.append("            TransitionTo(CombatState.Block);")
    lines.append("            if (_animator != null)")
    lines.append("                _animator.SetBool(\"IsBlocking\", true);")
    lines.append("        }")
    lines.append("")
    lines.append("        private void TransitionTo(CombatState newState)")
    lines.append("        {")
    lines.append("            if (_currentState == CombatState.Block && _animator != null)")
    lines.append("                _animator.SetBool(\"IsBlocking\", false);")
    lines.append("")
    lines.append("            _currentState = newState;")
    lines.append("        }")
    lines.append("")
    lines.append("        // =================================================================")
    lines.append("        // Attack execution (uses DamageCalculator + EventBus)")
    lines.append("        // =================================================================")
    lines.append("")
    lines.append("        private void PerformLightAttack()")
    lines.append("        {")
    lines.append("            _stateTimer = 0.35f;")
    lines.append("            int basePower = _combatant != null ? _combatant.Attack : 10;")
    lines.append("            float comboMultiplier = 1f + (_currentComboIndex - 1) * 0.15f;")
    lines.append("            int finalPower = Mathf.RoundToInt(basePower * comboMultiplier);")
    lines.append("")
    lines.append("            if (_animator != null)")
    lines.append("                _animator.SetTrigger(\"LightAttack\" + _currentComboIndex);")
    lines.append("")
    lines.append("            PerformDamageCheck(finalPower);")
    lines.append("        }")
    lines.append("")
    lines.append("        private void PerformHeavyAttack()")
    lines.append("        {")
    lines.append("            _stateTimer = 0.6f;")
    lines.append("            int basePower = _combatant != null ? _combatant.Attack : 10;")
    lines.append("            int finalPower = Mathf.RoundToInt(basePower * heavyDamageMultiplier);")
    lines.append("            staminaCurrent -= 15f;")
    lines.append("            _staminaRegenTimer = staminaRegenDelay;")
    lines.append("")
    lines.append("            if (_animator != null)")
    lines.append("                _animator.SetTrigger(\"HeavyAttack\" + _currentComboIndex);")
    lines.append("")
    lines.append("            PerformDamageCheck(finalPower);")
    lines.append("        }")
    lines.append("")
    lines.append("        private void PerformDamageCheck(int basePower)")
    lines.append("        {")
    lines.append("            if (_combatant == null) return;")
    lines.append("")
    lines.append("            // Overlap sphere to find targets")
    lines.append("            Collider[] hits = Physics.OverlapSphere(transform.position + transform.forward * 1.5f, 2f);")
    lines.append("            foreach (var hit in hits)")
    lines.append("            {")
    lines.append("                if (hit.gameObject == gameObject) continue;")
    lines.append("                var target = hit.GetComponent<Combatant>();")
    lines.append("                if (target == null || !target.IsAlive) continue;")
    lines.append("")
    lines.append("                // Use DamageCalculator for damage pipeline")
    lines.append("                DamageResult result = DamageCalculator.Calculate(")
    lines.append("                    _combatant, target, basePower, DamageType.PHYSICAL);")
    lines.append("")
    lines.append("                target.TakeDamage(result.finalDamage, result.isCritical);")
    lines.append("")
    lines.append("                // Fire EventBus event")
    lines.append("                EventBus.DamageDealt(")
    lines.append("                    _combatant != null ? _combatant.CombatantId : \"\",")
    lines.append("                    target.CombatantId,")
    lines.append("                    result.finalDamage,")
    lines.append("                    result.isCritical);")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        // =================================================================")
    lines.append("        // Damage reception (block / hit reaction)")
    lines.append("        // =================================================================")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Called when this player takes damage from an external source.")
    lines.append("        /// </summary>")
    lines.append("        public void ReceiveHit(int damage, bool isCritical)")
    lines.append("        {")
    lines.append("            if (_isInvincible || _currentState == CombatState.Dead)")
    lines.append("                return;")
    lines.append("")
    lines.append("            if (_currentState == CombatState.Block && staminaCurrent > 0f)")
    lines.append("            {")
    lines.append("                // Block reduces damage and drains stamina")
    lines.append("                int reduced = Mathf.RoundToInt(damage * blockDamageReduction);")
    lines.append("                staminaCurrent -= blockStaminaDrain;")
    lines.append("                _staminaRegenTimer = staminaRegenDelay;")
    lines.append("")
    lines.append("                if (staminaCurrent <= 0f)")
    lines.append("                {")
    lines.append("                    // Block broken -- take full unmitigated damage")
    lines.append("                    staminaCurrent = 0f;")
    lines.append("                    TransitionTo(CombatState.HitReaction);")
    lines.append("                    _stateTimer = hitReactionDuration;")
    lines.append("                    if (_combatant != null)")
    lines.append("                        _combatant.TakeDamage(damage, isCritical);")
    lines.append("                }")
    lines.append("                else")
    lines.append("                {")
    lines.append("                    // Block held -- apply reduced damage")
    lines.append("                    if (_combatant != null)")
    lines.append("                        _combatant.TakeDamage(reduced, isCritical);")
    lines.append("                }")
    lines.append("                return;")
    lines.append("            }")
    lines.append("")
    lines.append("            // Unblocked hit -- enter hit reaction")
    lines.append("            TransitionTo(CombatState.HitReaction);")
    lines.append("            _stateTimer = hitReactionDuration;")
    lines.append("            _currentComboIndex = 0;")
    lines.append("")
    lines.append("            if (_animator != null)")
    lines.append("                _animator.SetTrigger(\"HitReaction\");")
    lines.append("")
    lines.append("            if (_combatant != null)")
    lines.append("            {")
    lines.append("                _combatant.TakeDamage(damage, isCritical);")
    lines.append("                if (!_combatant.IsAlive)")
    lines.append("                    TransitionTo(CombatState.Dead);")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        // =================================================================")
    lines.append("        // i-Frame and stamina systems")
    lines.append("        // =================================================================")
    lines.append("")
    lines.append("        private void UpdateIFrames()")
    lines.append("        {")
    lines.append("            if (_isInvincible)")
    lines.append("            {")
    lines.append("                _iFrameTimer -= Time.deltaTime;")
    lines.append("                if (_iFrameTimer <= 0f)")
    lines.append("                    _isInvincible = false;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        private void UpdateStamina()")
    lines.append("        {")
    lines.append("            if (_staminaRegenTimer > 0f)")
    lines.append("            {")
    lines.append("                _staminaRegenTimer -= Time.deltaTime;")
    lines.append("                return;")
    lines.append("            }")
    lines.append("")
    lines.append("            if (_currentState == CombatState.Idle && staminaCurrent < staminaMax)")
    lines.append("            {")
    lines.append("                staminaCurrent = Mathf.Min(staminaMax, staminaCurrent + staminaRegenRate * Time.deltaTime);")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        // =================================================================")
    lines.append("        // Input hooks (override in subclass or wire to Input System)")
    lines.append("        // =================================================================")
    lines.append("")
    lines.append("        /// <summary>Override to provide light attack input.</summary>")
    lines.append("        protected virtual bool GetLightAttackInput() { return Input.GetButtonDown(\"Fire1\"); }")
    lines.append("")
    lines.append("        /// <summary>Override to provide heavy attack input.</summary>")
    lines.append("        protected virtual bool GetHeavyAttackInput() { return Input.GetButtonDown(\"Fire2\"); }")
    lines.append("")
    lines.append("        /// <summary>Override to provide dodge input.</summary>")
    lines.append("        protected virtual bool GetDodgeInput() { return Input.GetKeyDown(KeyCode.Space); }")
    lines.append("")
    lines.append("        /// <summary>Override to provide block input.</summary>")
    lines.append("        protected virtual bool GetBlockInput() { return Input.GetKey(KeyCode.LeftShift); }")
    lines.append("")
    lines.append("        /// <summary>Override to provide movement direction.</summary>")
    lines.append("        protected virtual Vector3 GetMoveDirection()")
    lines.append("        {")
    lines.append("            float h = Input.GetAxisRaw(\"Horizontal\");")
    lines.append("            float v = Input.GetAxisRaw(\"Vertical\");")
    lines.append("            if (Mathf.Approximately(h, 0f) && Mathf.Approximately(v, 0f))")
    lines.append("                return Vector3.zero;")
    lines.append("")
    lines.append("            // Camera-relative direction for third-person control")
    lines.append("            Camera cam = Camera.main;")
    lines.append("            if (cam == null)")
    lines.append("                return new Vector3(h, 0f, v);")
    lines.append("")
    lines.append("            Vector3 camForward = cam.transform.forward;")
    lines.append("            Vector3 camRight = cam.transform.right;")
    lines.append("            camForward.y = 0f;")
    lines.append("            camRight.y = 0f;")
    lines.append("            camForward.Normalize();")
    lines.append("            camRight.Normalize();")
    lines.append("")
    lines.append("            return camForward * v + camRight * h;")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-01b: Turn-based combat wrapper (delegates to BattleManager)
# ---------------------------------------------------------------------------


def _generate_turnbased_combat_script(
    namespace: str = "VeilBreakers.Combat",
) -> str:
    """Generate a turn-based combat wrapper that delegates to BattleManager.

    Produces a MonoBehaviour that bridges between the overworld and the
    existing BattleManager/Combatant turn-based system. Manages turn state
    (PLAYER_TURN, ENEMY_TURN), action selection, and EventBus integration.
    """
    ns = _safe_namespace(namespace)
    lines = []
    lines.append("using UnityEngine;")
    lines.append("using VeilBreakers.Combat;")
    lines.append("using VeilBreakers.Core;")
    lines.append("using VeilBreakers.Systems;")
    lines.append("using VeilBreakers.Data;")
    lines.append("")
    lines.append(f"namespace {ns}")
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Turn-based combat controller that delegates to BattleManager.")
    lines.append("    /// Manages PLAYER_TURN / ENEMY_TURN states for structured encounters.")
    lines.append("    /// For real-time overworld combat, use VB_PlayerCombat instead.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public class VB_TurnBasedCombat : MonoBehaviour")
    lines.append("    {")
    lines.append("        /// <summary>Turn-based battle states.</summary>")
    lines.append("        public enum TurnState")
    lines.append("        {")
    lines.append("            Inactive,")
    lines.append("            BattleStart,")
    lines.append("            PlayerTurn,")
    lines.append("            EnemyTurn,")
    lines.append("            Victory,")
    lines.append("            Defeat")
    lines.append("        }")
    lines.append("")
    lines.append("        [Header(\"Battle References\")]")
    lines.append("        public Combatant playerCombatant;")
    lines.append("        public Combatant[] enemyCombatants;")
    lines.append("")
    lines.append("        // Runtime state")
    lines.append("        private TurnState _currentState = TurnState.Inactive;")
    lines.append("        private int _currentEnemyIndex = 0;")
    lines.append("")
    lines.append("        /// <summary>Current turn state (read-only).</summary>")
    lines.append("        public TurnState CurrentState => _currentState;")
    lines.append("")
    lines.append("        /// <summary>Start a new battle encounter.</summary>")
    lines.append("        public virtual void StartBattle(Combatant player, Combatant[] enemies)")
    lines.append("        {")
    lines.append("            playerCombatant = player;")
    lines.append("            enemyCombatants = enemies;")
    lines.append("            _currentState = TurnState.BattleStart;")
    lines.append("            _currentEnemyIndex = 0;")
    lines.append("            OnBattleStarted?.Invoke();")
    lines.append("            TransitionToPlayerTurn();")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>Transition to player's turn.</summary>")
    lines.append("        protected virtual void TransitionToPlayerTurn()")
    lines.append("        {")
    lines.append("            _currentState = TurnState.PlayerTurn;")
    lines.append("            OnPlayerTurnStarted?.Invoke();")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>Execute a player action and advance to enemy turn.</summary>")
    lines.append("        public virtual void ExecutePlayerAction(string actionId, int targetIndex)")
    lines.append("        {")
    lines.append("            if (_currentState != TurnState.PlayerTurn) return;")
    lines.append("")
    lines.append("            // Delegate damage calculation to existing systems")
    lines.append("            var target = enemyCombatants[Mathf.Clamp(targetIndex, 0, enemyCombatants.Length - 1)];")
    lines.append("            DamageResult result = DamageCalculator.Calculate(playerCombatant, target, playerCombatant.stats.attack, DamageType.PHYSICAL);")
    lines.append("            float damage = result.finalDamage;")
    lines.append("            target.TakeDamage(result);")
    lines.append("            OnPlayerActionExecuted?.Invoke(actionId);")
    lines.append("")
    lines.append("            // Check for victory")
    lines.append("            bool allDefeated = true;")
    lines.append("            foreach (var enemy in enemyCombatants)")
    lines.append("            {")
    lines.append("                if (enemy != null && enemy.gameObject.activeSelf)")
    lines.append("                    allDefeated = false;")
    lines.append("            }")
    lines.append("")
    lines.append("            if (allDefeated)")
    lines.append("            {")
    lines.append("                _currentState = TurnState.Victory;")
    lines.append("                OnBattleVictory?.Invoke();")
    lines.append("                return;")
    lines.append("            }")
    lines.append("")
    lines.append("            TransitionToEnemyTurn();")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>Transition to enemy turn and process AI actions.</summary>")
    lines.append("        protected virtual void TransitionToEnemyTurn()")
    lines.append("        {")
    lines.append("            _currentState = TurnState.EnemyTurn;")
    lines.append("            _currentEnemyIndex = 0;")
    lines.append("            OnEnemyTurnStarted?.Invoke();")
    lines.append("            ProcessNextEnemy();")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>Process the next enemy's action.</summary>")
    lines.append("        protected virtual void ProcessNextEnemy()")
    lines.append("        {")
    lines.append("            while (_currentEnemyIndex < enemyCombatants.Length)")
    lines.append("            {")
    lines.append("                var enemy = enemyCombatants[_currentEnemyIndex];")
    lines.append("                _currentEnemyIndex++;")
    lines.append("")
    lines.append("                if (enemy == null || !enemy.gameObject.activeSelf)")
    lines.append("                    continue;")
    lines.append("")
    lines.append("                // Delegate enemy AI damage to existing systems")
    lines.append("                DamageResult result = DamageCalculator.Calculate(enemy, playerCombatant, enemy.stats.attack, DamageType.PHYSICAL);")
    lines.append("                float damage = result.finalDamage;")
    lines.append("                playerCombatant.TakeDamage(result);")
    lines.append("                OnEnemyActionExecuted?.Invoke();")
    lines.append("                break;")
    lines.append("            }")
    lines.append("")
    lines.append("            // Check for defeat")
    lines.append("            if (playerCombatant == null || !playerCombatant.gameObject.activeSelf)")
    lines.append("            {")
    lines.append("                _currentState = TurnState.Defeat;")
    lines.append("                OnBattleDefeat?.Invoke();")
    lines.append("                return;")
    lines.append("            }")
    lines.append("")
    lines.append("            if (_currentEnemyIndex >= enemyCombatants.Length)")
    lines.append("                TransitionToPlayerTurn();")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>End the battle and clean up.</summary>")
    lines.append("        public virtual void EndBattle()")
    lines.append("        {")
    lines.append("            _currentState = TurnState.Inactive;")
    lines.append("            OnBattleEnded?.Invoke();")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-02: Ability system (brand-specific abilities with cooldowns)
# ---------------------------------------------------------------------------


def generate_ability_system_script(
    max_ability_slots: int = 4,
    mana_max: float = 100.0,
    mana_regen_rate: float = 5.0,
    namespace: str = "VeilBreakers.Combat",
) -> str:
    """Generate C# runtime MonoBehaviour for a brand-specific ability system.

    Produces an ability slot system with cooldown timers, mana resource,
    brand matching, and EventBus integration.

    Args:
        max_ability_slots: Maximum number of ability slots.
        mana_max: Maximum mana pool.
        mana_regen_rate: Mana regenerated per second.
        namespace: C# namespace for the generated class.

    Returns:
        Complete C# source string.
    """
    lines = []
    lines.append("using UnityEngine;")
    lines.append("using System.Collections.Generic;")
    lines.append("using VeilBreakers.Combat;")
    lines.append("using VeilBreakers.Core;")
    lines.append("using VeilBreakers.Data;")
    lines.append("")
    lines.append("namespace " + _safe_namespace(namespace))
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Serializable ability slot for the ability system.")
    lines.append("    /// </summary>")
    lines.append("    [System.Serializable]")
    lines.append("    public class AbilitySlot")
    lines.append("    {")
    lines.append("        public string abilityName;")
    lines.append("        public Brand requiredBrand = Brand.NONE;")
    lines.append("        public float cooldownMax = 5f;")
    lines.append("        public float cooldownRemaining = 0f;")
    lines.append("        public float manaCost = 20f;")
    lines.append("        public KeyCode activationKey = KeyCode.Alpha1;")
    lines.append("        public int basePower = 30;")
    lines.append("")
    lines.append("        /// <summary>Cooldown percentage (0 = ready, 1 = full cooldown).</summary>")
    lines.append("        public float CooldownPercent => cooldownMax > 0f ? cooldownRemaining / cooldownMax : 0f;")
    lines.append("")
    lines.append("        /// <summary>Whether this ability is off cooldown.</summary>")
    lines.append("        public bool IsReady => cooldownRemaining <= 0f;")
    lines.append("    }")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// Brand-specific ability system with cooldowns and mana.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public class VB_AbilitySystem : MonoBehaviour")
    lines.append("    {")
    lines.append("        [Header(\"Ability Slots\")]")
    lines.append("        public AbilitySlot[] abilitySlots = new AbilitySlot[" + str(max_ability_slots) + "];")
    lines.append("")
    lines.append("        [Header(\"Mana\")]")
    lines.append("        public float manaMax = " + str(mana_max) + "f;")
    lines.append("        public float manaCurrent;")
    lines.append("        public float manaRegenRate = " + str(mana_regen_rate) + "f;")
    lines.append("")
    lines.append("        // Cached components")
    lines.append("        private Combatant _combatant;")
    lines.append("        private Animator _animator;")
    lines.append("")
    lines.append("        /// <summary>Maximum ability slots.</summary>")
    lines.append("        public int MaxSlots => " + str(max_ability_slots) + ";")
    lines.append("")
    lines.append("        private void Start()")
    lines.append("        {")
    lines.append("            _combatant = GetComponent<Combatant>();")
    lines.append("            _animator = GetComponent<Animator>();")
    lines.append("            manaCurrent = manaMax;")
    lines.append("        }")
    lines.append("")
    lines.append("        private void Update()")
    lines.append("        {")
    lines.append("            UpdateCooldowns();")
    lines.append("            UpdateManaRegen();")
    lines.append("            CheckAbilityInput();")
    lines.append("        }")
    lines.append("")
    lines.append("        private void UpdateCooldowns()")
    lines.append("        {")
    lines.append("            if (abilitySlots == null) return;")
    lines.append("            for (int i = 0; i < abilitySlots.Length; i++)")
    lines.append("            {")
    lines.append("                if (abilitySlots[i] != null && abilitySlots[i].cooldownRemaining > 0f)")
    lines.append("                    abilitySlots[i].cooldownRemaining -= Time.deltaTime;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        private void UpdateManaRegen()")
    lines.append("        {")
    lines.append("            if (manaCurrent < manaMax)")
    lines.append("                manaCurrent = Mathf.Min(manaMax, manaCurrent + manaRegenRate * Time.deltaTime);")
    lines.append("        }")
    lines.append("")
    lines.append("        private void CheckAbilityInput()")
    lines.append("        {")
    lines.append("            if (abilitySlots == null) return;")
    lines.append("            for (int i = 0; i < abilitySlots.Length; i++)")
    lines.append("            {")
    lines.append("                if (abilitySlots[i] != null && Input.GetKeyDown(abilitySlots[i].activationKey))")
    lines.append("                    TryActivateAbility(i);")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Attempt to activate an ability by slot index.")
    lines.append("        /// Validates cooldown, mana cost, and brand requirement.")
    lines.append("        /// </summary>")
    lines.append("        public bool TryActivateAbility(int slotIndex)")
    lines.append("        {")
    lines.append("            if (abilitySlots == null || slotIndex < 0 || slotIndex >= abilitySlots.Length)")
    lines.append("                return false;")
    lines.append("")
    lines.append("            AbilitySlot slot = abilitySlots[slotIndex];")
    lines.append("            if (slot == null) return false;")
    lines.append("")
    lines.append("            // Cooldown check")
    lines.append("            if (!slot.IsReady)")
    lines.append("                return false;")
    lines.append("")
    lines.append("            // Mana check")
    lines.append("            if (manaCurrent < slot.manaCost)")
    lines.append("                return false;")
    lines.append("")
    lines.append("            // Brand check")
    lines.append("            if (slot.requiredBrand != Brand.NONE)")
    lines.append("            {")
    lines.append("                if (_combatant == null) return false;")
    lines.append("                if (_combatant.Brand != slot.requiredBrand)")
    lines.append("                    return false;")
    lines.append("            }")
    lines.append("")
    lines.append("            // Activate")
    lines.append("            manaCurrent -= slot.manaCost;")
    lines.append("            slot.cooldownRemaining = slot.cooldownMax;")
    lines.append("")
    lines.append("            if (_animator != null)")
    lines.append("                _animator.SetTrigger(\"Ability\" + slotIndex);")
    lines.append("")
    lines.append("            // Fire EventBus event")
    lines.append("            string heroId = _combatant != null ? _combatant.CombatantId : \"\";")
    lines.append("            Brand brand = slot.requiredBrand;")
    lines.append("            EventBus.SkillUsed(heroId, slot.abilityName);")
    lines.append("")
    lines.append("            return true;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Set an ability in the given slot.")
    lines.append("        /// </summary>")
    lines.append("        public void SetAbility(int slotIndex, AbilitySlot ability)")
    lines.append("        {")
    lines.append("            if (slotIndex >= 0 && slotIndex < abilitySlots.Length)")
    lines.append("                abilitySlots[slotIndex] = ability;")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-03: Synergy engine (wiring layer -- delegates to SynergySystem)
# ---------------------------------------------------------------------------


def generate_synergy_engine_script(
    namespace: str = "VeilBreakers.Combat",
) -> str:
    """Generate C# runtime MonoBehaviour for synergy wiring.

    Produces a wiring layer that delegates ALL synergy calculations to
    the existing SynergySystem static class. Does NOT reimplement
    synergy tier logic or damage bonus values.

    Args:
        namespace: C# namespace for the generated class.

    Returns:
        Complete C# source string.
    """
    lines = []
    lines.append("using UnityEngine;")
    lines.append("using VeilBreakers.Combat;")
    lines.append("using VeilBreakers.Core;")
    lines.append("using VeilBreakers.Systems;")
    lines.append("using VeilBreakers.Data;")
    lines.append("")
    lines.append("namespace " + _safe_namespace(namespace))
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Synergy engine wiring layer.")
    lines.append("    /// Delegates all synergy calculations to SynergySystem static class.")
    lines.append("    /// Does NOT reimplement synergy tier logic or damage bonus values.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public class VB_SynergyEngine : MonoBehaviour")
    lines.append("    {")
    lines.append("        [Header(\"Synergy State\")]")
    lines.append("        public SynergySystem.SynergyTier currentTier = SynergySystem.SynergyTier.NEUTRAL;")
    lines.append("        public float currentDamageBonus = 1.0f;")
    lines.append("        public int consecutiveHits = 0;")
    lines.append("        public int comboMeter = 0;")
    lines.append("")
    lines.append("        [Header(\"Visual Feedback\")]")
    lines.append("        public Color fullSynergyColor = new Color(1f, 0.84f, 0f, 1f);   // Gold")
    lines.append("        public Color partialSynergyColor = new Color(0.3f, 0.6f, 1f, 1f); // Blue")
    lines.append("        public Color neutralColor = Color.gray;")
    lines.append("        public Color antiSynergyColor = new Color(1f, 0.2f, 0.2f, 1f);   // Red")
    lines.append("")
    lines.append("        // Cached reference")
    lines.append("        private Combatant _combatant;")
    lines.append("        private SynergySystem.SynergyTier _previousTier;")
    lines.append("")
    lines.append("        private void Start()")
    lines.append("        {")
    lines.append("            _combatant = GetComponent<Combatant>();")
    lines.append("            _previousTier = SynergySystem.SynergyTier.NONE;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Evaluate synergy tier for a party composition.")
    lines.append("        /// Delegates entirely to SynergySystem.GetSynergyTier().")
    lines.append("        /// </summary>")
    lines.append("        public void EvaluateSynergy(Path championPath, Brand[] partyBrands)")
    lines.append("        {")
    lines.append("            // Delegate to existing SynergySystem -- no reimplementation")
    lines.append("            currentTier = SynergySystem.GetSynergyTier(championPath, partyBrands);")
    lines.append("            currentDamageBonus = SynergySystem.GetDamageBonus(currentTier);")
    lines.append("")
    lines.append("            // Notify UI if tier changed")
    lines.append("            if (currentTier != _previousTier)")
    lines.append("            {")
    lines.append("                EventBus.SynergyTierChanged((int)currentTier);")
    lines.append("                _previousTier = currentTier;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Track combo hits for same synergy tier.")
    lines.append("        /// </summary>")
    lines.append("        public void OnHitLanded(SynergySystem.SynergyTier hitTier)")
    lines.append("        {")
    lines.append("            if (hitTier == currentTier)")
    lines.append("            {")
    lines.append("                consecutiveHits++;")
    lines.append("                comboMeter = Mathf.Min(comboMeter + 1, 10);")
    lines.append("            }")
    lines.append("            else")
    lines.append("            {")
    lines.append("                consecutiveHits = 1;")
    lines.append("                comboMeter = 0;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get damage bonus from SynergySystem for the current tier.")
    lines.append("        /// </summary>")
    lines.append("        public float GetCurrentDamageBonus()")
    lines.append("        {")
    lines.append("            return SynergySystem.GetDamageBonus(currentTier);")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get visual feedback color for the current synergy tier.")
    lines.append("        /// </summary>")
    lines.append("        public Color GetTierColor()")
    lines.append("        {")
    lines.append("            switch (currentTier)")
    lines.append("            {")
    lines.append("                case SynergySystem.SynergyTier.FULL:")
    lines.append("                    return fullSynergyColor;")
    lines.append("                case SynergySystem.SynergyTier.PARTIAL:")
    lines.append("                    return partialSynergyColor;")
    lines.append("                case SynergySystem.SynergyTier.ANTI:")
    lines.append("                    return antiSynergyColor;")
    lines.append("                default:")
    lines.append("                    return neutralColor;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Check if combo ability is unlocked via SynergySystem.")
    lines.append("        /// </summary>")
    lines.append("        public bool IsComboUnlocked()")
    lines.append("        {")
    lines.append("            return SynergySystem.IsComboUnlocked(currentTier);")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-04: Corruption gameplay (wiring layer -- delegates to CorruptionSystem)
# ---------------------------------------------------------------------------


def generate_corruption_gameplay_script(
    thresholds: list[float] | None = None,
    namespace: str = "VeilBreakers.Combat",
) -> str:
    """Generate C# runtime MonoBehaviour for corruption gameplay effects.

    Produces a wiring layer that delegates ALL corruption calculations to
    the existing CorruptionSystem static class. Does NOT reimplement
    corruption formulas or state thresholds.

    Args:
        thresholds: Corruption threshold percentages (default [25, 50, 75, 100]).
        namespace: C# namespace for the generated class.

    Returns:
        Complete C# source string.
    """
    if thresholds is None:
        thresholds = [25, 50, 75, 100]

    lines = []
    lines.append("using UnityEngine;")
    lines.append("using VeilBreakers.Combat;")
    lines.append("using VeilBreakers.Core;")
    lines.append("using VeilBreakers.Systems;")
    lines.append("using VeilBreakers.Data;")
    lines.append("")
    lines.append("namespace " + _safe_namespace(namespace))
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Corruption gameplay wiring layer.")
    lines.append("    /// Delegates all corruption calculations to CorruptionSystem static class.")
    lines.append("    /// Does NOT reimplement corruption formulas or state thresholds.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public class VB_CorruptionGameplay : MonoBehaviour")
    lines.append("    {")
    lines.append("        [Header(\"Corruption State\")]")
    lines.append("        [Range(0f, 100f)]")
    lines.append("        public float corruptionPercent = 0f;")
    lines.append("        public CorruptionState currentState = CorruptionState.ASCENDED;")
    lines.append("")
    lines.append("        [Header(\"Thresholds\")]")

    threshold_str = "new float[] { "
    threshold_str += ", ".join(str(int(t)) + "f" for t in thresholds)
    threshold_str += " }"
    lines.append("        public float[] thresholds = " + threshold_str + ";")

    lines.append("")
    lines.append("        [Header(\"Visual Feedback\")]")
    lines.append("        public Renderer characterRenderer;")
    lines.append("        private static readonly int CorruptionLevelProp = Shader.PropertyToID(\"_CorruptionAmount\");")
    lines.append("")
    lines.append("        // Cached components")
    lines.append("        private Combatant _combatant;")
    lines.append("        private CorruptionState _previousState;")
    lines.append("        private MaterialPropertyBlock _materialBlock;")
    lines.append("")
    lines.append("        private void Start()")
    lines.append("        {")
    lines.append("            _combatant = GetComponent<Combatant>();")
    lines.append("            _previousState = CorruptionState.ASCENDED;")
    lines.append("            _materialBlock = new MaterialPropertyBlock();")
    lines.append("            UpdateCorruptionState();")
    lines.append("        }")
    lines.append("")
    lines.append("        private void Update()")
    lines.append("        {")
    lines.append("            // Sync corruption from Combatant if available")
    lines.append("            if (_combatant != null)")
    lines.append("                corruptionPercent = _combatant.Corruption;")
    lines.append("")
    lines.append("            UpdateCorruptionState();")
    lines.append("            UpdateVisualFeedback();")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Evaluate corruption state via CorruptionSystem.")
    lines.append("        /// </summary>")
    lines.append("        private void UpdateCorruptionState()")
    lines.append("        {")
    lines.append("            // Delegate to existing CorruptionSystem -- no reimplementation")
    lines.append("            currentState = CorruptionSystem.GetCorruptionState(corruptionPercent);")
    lines.append("")
    lines.append("            if (currentState != _previousState)")
    lines.append("            {")
    lines.append("                OnCorruptionStateChanged(_previousState, currentState);")
    lines.append("                _previousState = currentState;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Apply stat multiplier from CorruptionSystem to a base stat value.")
    lines.append("        /// </summary>")
    lines.append("        public int GetModifiedStat(int baseStat)")
    lines.append("        {")
    lines.append("            float multiplier = CorruptionSystem.GetStatMultiplier(corruptionPercent);")
    lines.append("            return Mathf.RoundToInt(baseStat * multiplier);")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get stat multiplier for current corruption level.")
    lines.append("        /// Delegates to CorruptionSystem.GetStatMultiplier().")
    lines.append("        /// </summary>")
    lines.append("        public float GetStatMultiplier()")
    lines.append("        {")
    lines.append("            return CorruptionSystem.GetStatMultiplier(corruptionPercent);")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Change corruption percentage and fire events.")
    lines.append("        /// </summary>")
    lines.append("        public void SetCorruption(float newPercent)")
    lines.append("        {")
    lines.append("            corruptionPercent = Mathf.Clamp(newPercent, 0f, 100f);")
    lines.append("")
    lines.append("            if (_combatant != null)")
    lines.append("            {")
    lines.append("                _combatant.SetCorruption(corruptionPercent);")
    lines.append("                EventBus.CorruptionChanged(_combatant.CombatantId, corruptionPercent);")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Called when corruption state transitions.")
    lines.append("        /// </summary>")
    lines.append("        private void OnCorruptionStateChanged(CorruptionState oldState, CorruptionState newState)")
    lines.append("        {")
    lines.append("            Debug.Log($\"[Corruption] State changed: {oldState} -> {newState}\");")
    lines.append("")
    lines.append("            // NPC reaction flag -- dialogue system can check this")
    lines.append("            // High corruption makes NPCs react differently")
    lines.append("            if (newState == CorruptionState.CORRUPTED || newState == CorruptionState.ABYSSAL)")
    lines.append("                Debug.Log(\"[Corruption] NPCs will react to high corruption!\");")
    lines.append("")
    lines.append("            // Ability mutation trigger at high corruption")
    lines.append("            if (newState == CorruptionState.ABYSSAL)")
    lines.append("                Debug.Log(\"[Corruption] Abilities mutated -- stronger but uncontrollable!\");")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Update visual corruption effects via shader parameter.")
    lines.append("        /// </summary>")
    lines.append("        private void UpdateVisualFeedback()")
    lines.append("        {")
    lines.append("            if (characterRenderer != null && _materialBlock != null)")
    lines.append("            {")
    lines.append("                // Use MaterialPropertyBlock to avoid creating material instances")
    lines.append("                characterRenderer.GetPropertyBlock(_materialBlock);")
    lines.append("                _materialBlock.SetFloat(CorruptionLevelProp, corruptionPercent / 100f);")
    lines.append("                characterRenderer.SetPropertyBlock(_materialBlock);")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Check if corruption is at or above a threshold.")
    lines.append("        /// </summary>")
    lines.append("        public bool IsAboveThreshold(int thresholdIndex)")
    lines.append("        {")
    lines.append("            if (thresholdIndex < 0 || thresholdIndex >= thresholds.Length)")
    lines.append("                return false;")
    lines.append("            return corruptionPercent >= thresholds[thresholdIndex];")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-05: XP / leveling system
# ---------------------------------------------------------------------------


def generate_xp_leveling_script(
    max_level: int = 50,
    base_xp_per_level: int = 100,
    xp_scaling_factor: float = 1.15,
    namespace: str = "VeilBreakers.GameSystems",
) -> str:
    """Generate C# runtime MonoBehaviour for an XP and leveling system.

    Integrates with EventBus.HeroLevelUp and supports per-hero-path
    stat scaling.

    Args:
        max_level: Maximum achievable level.
        base_xp_per_level: Base XP needed for the first level-up.
        xp_scaling_factor: Exponential scaling factor per level.
        namespace: C# namespace for the generated class.

    Returns:
        Complete C# source string.
    """
    lines = []
    lines.append("using UnityEngine;")
    lines.append("using VeilBreakers.Core;")
    lines.append("using VeilBreakers.Data;")
    lines.append("")
    lines.append("namespace " + _safe_namespace(namespace))
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// XP and leveling system with exponential scaling.")
    lines.append("    /// Integrates with EventBus.HeroLevelUp for cross-system communication.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public class VB_XPSystem : MonoBehaviour")
    lines.append("    {")
    lines.append("        [Header(\"Identity\")]")
    lines.append("        public string heroId;")
    lines.append("        public Path heroPath = Path.NONE;")
    lines.append("")
    lines.append("        [Header(\"XP Settings\")]")
    lines.append("        public int maxLevel = " + str(max_level) + ";")
    lines.append("        public int baseXPPerLevel = " + str(base_xp_per_level) + ";")
    lines.append("        public float xpScalingFactor = " + str(xp_scaling_factor) + "f;")
    lines.append("")
    lines.append("        [Header(\"Current State\")]")
    lines.append("        public int currentLevel = 1;")
    lines.append("        public int currentXP = 0;")
    lines.append("        public int totalXP = 0;")
    lines.append("")
    lines.append("        [Header(\"Stat Points\")]")
    lines.append("        public int unspentStatPoints = 0;")
    lines.append("        public int bonusAttack = 0;")
    lines.append("        public int bonusDefense = 0;")
    lines.append("        public int bonusMagic = 0;")
    lines.append("        public int bonusVitality = 0;")
    lines.append("")
    lines.append("        /// <summary>XP needed to reach the next level.</summary>")
    lines.append("        public int XPToNextLevel => GetXPForLevel(currentLevel + 1);")
    lines.append("")
    lines.append("        /// <summary>Progress toward next level (0-1).</summary>")
    lines.append("        public float LevelProgress => XPToNextLevel > 0 ? (float)currentXP / XPToNextLevel : 1f;")
    lines.append("")
    lines.append("        private void OnEnable()")
    lines.append("        {")
    lines.append("            // Subscribe to XP-granting events")
    lines.append("            EventBus.OnUnitDefeated += OnEnemyKilled;")
    lines.append("        }")
    lines.append("")
    lines.append("        private void OnDisable()")
    lines.append("        {")
    lines.append("            EventBus.OnUnitDefeated -= OnEnemyKilled;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Calculate XP required for a given level.")
    lines.append("        /// Uses exponential curve: baseXP * (scalingFactor ^ level).")
    lines.append("        /// </summary>")
    lines.append("        public int GetXPForLevel(int level)")
    lines.append("        {")
    lines.append("            if (level <= 1) return 0;")
    lines.append("            return Mathf.RoundToInt(baseXPPerLevel * Mathf.Pow(xpScalingFactor, level - 1));")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Add XP from any source. Triggers level-up if threshold reached.")
    lines.append("        /// </summary>")
    lines.append("        public void AddXP(int amount)")
    lines.append("        {")
    lines.append("            if (currentLevel >= maxLevel) return;")
    lines.append("")
    lines.append("            currentXP += amount;")
    lines.append("            totalXP += amount;")
    lines.append("")
    lines.append("            // Check for level-up (can chain multiple levels)")
    lines.append("            while (currentXP >= XPToNextLevel && currentLevel < maxLevel)")
    lines.append("            {")
    lines.append("                currentXP -= XPToNextLevel;")
    lines.append("                LevelUp();")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Process a level-up: increment level, grant stat points, fire event.")
    lines.append("        /// </summary>")
    lines.append("        private void LevelUp()")
    lines.append("        {")
    lines.append("            currentLevel++;")
    lines.append("")
    lines.append("            // Per-path stat scaling")
    lines.append("            ApplyPathStatBonus(heroPath);")
    lines.append("")
    lines.append("            // Grant manual stat points")
    lines.append("            unspentStatPoints += 3;")
    lines.append("")
    lines.append("            // Fire EventBus event")
    lines.append("            EventBus.HeroLevelUp(heroId, currentLevel);")
    lines.append("")
    lines.append("            Debug.Log($\"[XP] {heroId} leveled up to {currentLevel}!\");")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Apply automatic stat bonuses based on Path.")
    lines.append("        /// Different paths favor different stats.")
    lines.append("        /// </summary>")
    lines.append("        private void ApplyPathStatBonus(Path path)")
    lines.append("        {")
    lines.append("            // Each path gets automatic stat allocation on level-up")
    lines.append("            switch (path)")
    lines.append("            {")
    lines.append("                case Path.IRONBOUND:")
    lines.append("                    bonusDefense += 2;")
    lines.append("                    bonusVitality += 2;")
    lines.append("                    bonusAttack += 1;")
    lines.append("                    break;")
    lines.append("                case Path.FANGBORN:")
    lines.append("                    bonusAttack += 3;")
    lines.append("                    bonusDefense += 1;")
    lines.append("                    bonusVitality += 1;")
    lines.append("                    break;")
    lines.append("                case Path.VOIDTOUCHED:")
    lines.append("                    bonusMagic += 3;")
    lines.append("                    bonusAttack += 1;")
    lines.append("                    bonusVitality += 1;")
    lines.append("                    break;")
    lines.append("                case Path.UNCHAINED:")
    lines.append("                    // Balanced -- equal distribution")
    lines.append("                    bonusAttack += 1;")
    lines.append("                    bonusDefense += 1;")
    lines.append("                    bonusMagic += 1;")
    lines.append("                    bonusVitality += 1;")
    lines.append("                    break;")
    lines.append("                default:")
    lines.append("                    bonusAttack += 1;")
    lines.append("                    bonusDefense += 1;")
    lines.append("                    break;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Manually allocate a stat point.")
    lines.append("        /// </summary>")
    lines.append("        public bool AllocateStatPoint(string statName)")
    lines.append("        {")
    lines.append("            if (unspentStatPoints <= 0) return false;")
    lines.append("")
    lines.append("            switch (statName.ToLower())")
    lines.append("            {")
    lines.append("                case \"attack\":")
    lines.append("                case \"atk\":")
    lines.append("                    bonusAttack++;")
    lines.append("                    break;")
    lines.append("                case \"defense\":")
    lines.append("                case \"def\":")
    lines.append("                    bonusDefense++;")
    lines.append("                    break;")
    lines.append("                case \"magic\":")
    lines.append("                case \"mag\":")
    lines.append("                    bonusMagic++;")
    lines.append("                    break;")
    lines.append("                case \"vitality\":")
    lines.append("                case \"vit\":")
    lines.append("                    bonusVitality++;")
    lines.append("                    break;")
    lines.append("                default:")
    lines.append("                    return false;")
    lines.append("            }")
    lines.append("")
    lines.append("            unspentStatPoints--;")
    lines.append("            return true;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Handle enemy killed event for XP reward.")
    lines.append("        /// </summary>")
    lines.append("        private void OnEnemyKilled(string defeatedId)")
    lines.append("        {")
    lines.append("            // Base XP from kills (could look up per-enemy XP values)")
    lines.append("            AddXP(50);")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-06: Currency system
# ---------------------------------------------------------------------------


def generate_currency_system_script(
    currency_types: list[str] | None = None,
    namespace: str = "VeilBreakers.GameSystems",
) -> str:
    """Generate C# runtime MonoBehaviour for a multi-currency system.

    Produces a singleton-pattern currency manager with earn/spend/query
    methods and EventBus.CurrencyChanged(int) integration.

    Args:
        currency_types: List of currency type names (default: Gold, Souls, Marks).
        namespace: C# namespace for the generated class.

    Returns:
        Complete C# source string.
    """
    if currency_types is None:
        currency_types = ["Gold", "Souls", "Marks"]

    lines = []
    lines.append("using UnityEngine;")
    lines.append("using System.Collections.Generic;")
    lines.append("using VeilBreakers.Core;")
    lines.append("")
    lines.append("namespace " + _safe_namespace(namespace))
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Serializable currency data for save system integration.")
    lines.append("    /// </summary>")
    lines.append("    [System.Serializable]")
    lines.append("    public class CurrencyData")
    lines.append("    {")
    lines.append("        public string currencyType;")
    lines.append("        public int amount;")
    lines.append("    }")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// Multi-currency system with singleton pattern.")
    lines.append("    /// Supports earn, spend, query, and EventBus integration.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public class VB_CurrencySystem : MonoBehaviour")
    lines.append("    {")
    lines.append("        /// <summary>Singleton instance.</summary>")
    lines.append("        public static VB_CurrencySystem Instance { get; private set; }")
    lines.append("")
    lines.append("        [Header(\"Currencies\")]")
    lines.append("        [SerializeField]")
    lines.append("        private List<CurrencyData> _savedCurrencies = new List<CurrencyData>();")
    lines.append("")
    lines.append("        // Runtime currency storage")
    lines.append("        private Dictionary<string, int> _currencies = new Dictionary<string, int>();")
    lines.append("")
    lines.append("        // Transaction history")
    lines.append("        private List<string> _transactionHistory = new List<string>();")
    lines.append("")
    lines.append("        private void Awake()")
    lines.append("        {")
    lines.append("            if (Instance != null && Instance != this)")
    lines.append("            {")
    lines.append("                Destroy(gameObject);")
    lines.append("                return;")
    lines.append("            }")
    lines.append("            Instance = this;")
    lines.append("            DontDestroyOnLoad(gameObject);")
    lines.append("")
    lines.append("            // Initialize default currency types")

    for ct in currency_types:
        safe_ct = sanitize_cs_string(ct)
        lines.append('            _currencies["' + safe_ct + '"] = 0;')

    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Earn currency of the specified type.")
    lines.append("        /// </summary>")
    lines.append("        public void Earn(string currencyType, int amount)")
    lines.append("        {")
    lines.append("            if (amount <= 0) return;")
    lines.append("")
    lines.append("            if (!_currencies.ContainsKey(currencyType))")
    lines.append("                _currencies[currencyType] = 0;")
    lines.append("")
    lines.append("            _currencies[currencyType] += amount;")
    lines.append("")
    lines.append("            _transactionHistory.Add($\"+{amount} {currencyType}\");")
    lines.append("            EventBus.CurrencyChanged(_currencies[currencyType]);")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Spend currency of the specified type. Returns false if insufficient.")
    lines.append("        /// </summary>")
    lines.append("        public bool Spend(string currencyType, int amount)")
    lines.append("        {")
    lines.append("            if (amount <= 0) return false;")
    lines.append("            if (!HasEnough(currencyType, amount)) return false;")
    lines.append("")
    lines.append("            _currencies[currencyType] -= amount;")
    lines.append("")
    lines.append("            _transactionHistory.Add($\"-{amount} {currencyType}\");")
    lines.append("            EventBus.CurrencyChanged(_currencies[currencyType]);")
    lines.append("            return true;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get balance for a currency type.")
    lines.append("        /// </summary>")
    lines.append("        public int GetBalance(string currencyType)")
    lines.append("        {")
    lines.append("            return _currencies.TryGetValue(currencyType, out int val) ? val : 0;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Check if the player has enough of a currency.")
    lines.append("        /// </summary>")
    lines.append("        public bool HasEnough(string currencyType, int amount)")
    lines.append("        {")
    lines.append("            return GetBalance(currencyType) >= amount;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Format a currency amount for display (e.g. \"1,234 Gold\").")
    lines.append("        /// </summary>")
    lines.append("        public string FormatCurrency(string currencyType, int amount)")
    lines.append("        {")
    lines.append("            return $\"{amount:N0} {currencyType}\";")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get formatted balance string for display.")
    lines.append("        /// </summary>")
    lines.append("        public string GetFormattedBalance(string currencyType)")
    lines.append("        {")
    lines.append("            return FormatCurrency(currencyType, GetBalance(currencyType));")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get serializable currency data for save system.")
    lines.append("        /// </summary>")
    lines.append("        public List<CurrencyData> GetSaveData()")
    lines.append("        {")
    lines.append("            var data = new List<CurrencyData>();")
    lines.append("            foreach (var kvp in _currencies)")
    lines.append("            {")
    lines.append("                data.Add(new CurrencyData { currencyType = kvp.Key, amount = kvp.Value });")
    lines.append("            }")
    lines.append("            return data;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Load currency data from save system.")
    lines.append("        /// </summary>")
    lines.append("        public void LoadSaveData(List<CurrencyData> data)")
    lines.append("        {")
    lines.append("            _currencies.Clear();")
    lines.append("            foreach (var item in data)")
    lines.append("            {")
    lines.append("                _currencies[item.currencyType] = item.amount;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get recent transaction history for UI display.")
    lines.append("        /// </summary>")
    lines.append("        public IReadOnlyList<string> GetTransactionHistory()")
    lines.append("        {")
    lines.append("            return _transactionHistory;")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VB-07: Damage type system (wiring layer -- delegates to BrandSystem)
# ---------------------------------------------------------------------------


def generate_damage_type_script(
    namespace: str = "VeilBreakers.Combat",
) -> str:
    """Generate C# static utility class for brand-specific damage types.

    Produces a wiring layer that delegates effectiveness calculations to
    BrandSystem.GetEffectiveness(). Does NOT contain an effectiveness matrix.

    Args:
        namespace: C# namespace for the generated class.

    Returns:
        Complete C# source string.
    """
    lines = []
    lines.append("using UnityEngine;")
    lines.append("using VeilBreakers.Systems;")
    lines.append("using VeilBreakers.Data;")
    lines.append("")
    lines.append("namespace " + _safe_namespace(namespace))
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Extended damage type system with brand-specific resistance.")
    lines.append("    /// Delegates effectiveness calculations to BrandSystem.GetEffectiveness().")
    lines.append("    /// Does NOT reimplement brand effectiveness matrix.")
    lines.append("    /// Generated by VeilBreakers MCP toolkit.")
    lines.append("    /// </summary>")
    lines.append("    public static class VB_DamageTypeSystem")
    lines.append("    {")
    lines.append("        /// <summary>")
    lines.append("        /// Extended damage type categories:")
    lines.append("        /// Physical/Magical (generic), brand-specific, and True (bypasses resistance).")
    lines.append("        /// </summary>")
    lines.append("        public enum ExtendedDamageType")
    lines.append("        {")
    lines.append("            Physical,")
    lines.append("            Magical,")
    lines.append("            Iron,")
    lines.append("            Venom,")
    lines.append("            Surge,")
    lines.append("            Dread,")
    lines.append("            Blaze,")
    lines.append("            Savage,")
    lines.append("            Leech,")
    lines.append("            Grace,")
    lines.append("            Mend,")
    lines.append("            Ruin,")
    lines.append("            Void,")
    lines.append("            True  // Bypasses all resistance")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Apply resistance to base damage based on damage type and target brand.")
    lines.append("        /// Delegates to BrandSystem.GetEffectiveness() for multiplier.")
    lines.append("        /// </summary>")
    lines.append("        public static int ApplyResistance(int baseDamage, ExtendedDamageType damageType, Brand targetBrand)")
    lines.append("        {")
    lines.append("            // True damage bypasses all resistance")
    lines.append("            if (damageType == ExtendedDamageType.True)")
    lines.append("                return baseDamage;")
    lines.append("")
    lines.append("            // Generic Physical/Magical have no brand multiplier")
    lines.append("            if (damageType == ExtendedDamageType.Physical || damageType == ExtendedDamageType.Magical)")
    lines.append("                return baseDamage;")
    lines.append("")
    lines.append("            // Convert damage type to brand for effectiveness lookup")
    lines.append("            Brand attackBrand = DamageTypeToBrand(damageType);")
    lines.append("            if (attackBrand == Brand.NONE)")
    lines.append("                return baseDamage;")
    lines.append("")
    lines.append("            // Delegate to BrandSystem -- no reimplementation")
    lines.append("            float multiplier = BrandSystem.GetEffectiveness(attackBrand, targetBrand);")
    lines.append("            return Mathf.Max(1, Mathf.RoundToInt(baseDamage * multiplier));")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Map an extended damage type to a Brand enum value.")
    lines.append("        /// </summary>")
    lines.append("        public static Brand DamageTypeToBrand(ExtendedDamageType damageType)")
    lines.append("        {")
    lines.append("            switch (damageType)")
    lines.append("            {")
    lines.append("                case ExtendedDamageType.Iron:   return Brand.IRON;")
    lines.append("                case ExtendedDamageType.Venom:  return Brand.VENOM;")
    lines.append("                case ExtendedDamageType.Surge:  return Brand.SURGE;")
    lines.append("                case ExtendedDamageType.Dread:  return Brand.DREAD;")
    lines.append("                case ExtendedDamageType.Savage: return Brand.SAVAGE;")
    lines.append("                case ExtendedDamageType.Leech:  return Brand.LEECH;")
    lines.append("                case ExtendedDamageType.Grace:  return Brand.GRACE;")
    lines.append("                case ExtendedDamageType.Mend:   return Brand.MEND;")
    lines.append("                case ExtendedDamageType.Ruin:   return Brand.RUIN;")
    lines.append("                case ExtendedDamageType.Void:   return Brand.VOID;")
    lines.append("                default:                        return Brand.NONE;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Map a Brand to its corresponding extended damage type.")
    lines.append("        /// </summary>")
    lines.append("        public static ExtendedDamageType BrandToDamageType(Brand brand)")
    lines.append("        {")
    lines.append("            switch (brand)")
    lines.append("            {")
    lines.append("                case Brand.IRON:   return ExtendedDamageType.Iron;")
    lines.append("                case Brand.VENOM:  return ExtendedDamageType.Venom;")
    lines.append("                case Brand.SURGE:  return ExtendedDamageType.Surge;")
    lines.append("                case Brand.DREAD:  return ExtendedDamageType.Dread;")
    lines.append("                case Brand.SAVAGE: return ExtendedDamageType.Savage;")
    lines.append("                case Brand.LEECH:  return ExtendedDamageType.Leech;")
    lines.append("                case Brand.GRACE:  return ExtendedDamageType.Grace;")
    lines.append("                case Brand.MEND:   return ExtendedDamageType.Mend;")
    lines.append("                case Brand.RUIN:   return ExtendedDamageType.Ruin;")
    lines.append("                case Brand.VOID:   return ExtendedDamageType.Void;")
    lines.append("                default:           return ExtendedDamageType.Physical;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Check if a damage type is super effective against a target brand.")
    lines.append("        /// Delegates to BrandSystem.HasAdvantage().")
    lines.append("        /// </summary>")
    lines.append("        public static bool IsSuperEffective(ExtendedDamageType damageType, Brand targetBrand)")
    lines.append("        {")
    lines.append("            Brand attackBrand = DamageTypeToBrand(damageType);")
    lines.append("            if (attackBrand == Brand.NONE) return false;")
    lines.append("            return BrandSystem.GetEffectiveness(attackBrand, targetBrand) >= BrandSystem.SUPER_EFFECTIVE;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Check if a damage type is resisted by a target brand.")
    lines.append("        /// Delegates to BrandSystem.HasDisadvantage().")
    lines.append("        /// </summary>")
    lines.append("        public static bool IsResisted(ExtendedDamageType damageType, Brand targetBrand)")
    lines.append("        {")
    lines.append("            Brand attackBrand = DamageTypeToBrand(damageType);")
    lines.append("            if (attackBrand == Brand.NONE) return false;")
    lines.append("            return BrandSystem.GetEffectiveness(attackBrand, targetBrand) <= BrandSystem.NOT_EFFECTIVE;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Get UI tooltip text for damage type effectiveness.")
    lines.append("        /// </summary>")
    lines.append("        public static string GetEffectivenessTooltip(ExtendedDamageType damageType, Brand targetBrand)")
    lines.append("        {")
    lines.append("            if (damageType == ExtendedDamageType.True)")
    lines.append("                return \"True Damage (ignores resistance)\";")
    lines.append("            if (damageType == ExtendedDamageType.Physical || damageType == ExtendedDamageType.Magical)")
    lines.append("                return damageType.ToString() + \" Damage\";")
    lines.append("")
    lines.append("            Brand attackBrand = DamageTypeToBrand(damageType);")
    lines.append("            float mult = BrandSystem.GetEffectiveness(attackBrand, targetBrand);")
    lines.append("            return BrandSystem.GetEffectivenessText(mult);")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)
