"""Universal Skill VFX Factory -- archetype-based VFX composition for VeilBreakers.

Generates ``VBSkillVFXFactory`` MonoBehaviour that can create AAA-quality,
multi-phase skill VFX for ANY skill automatically from a simple config.
12 visual archetypes are composed with brand colors, timing, and scale to
produce unique-looking skills from reusable building blocks.

When hundreds of monsters each have 2-3 unique skills, this factory ensures
every skill looks studio-grade without writing custom VFX code each time.

Generated C# uses ParticleSystem + LineRenderer + TrailRenderer (NOT
VisualEffect), PrimeTween (NOT DOTween), C# events, and targets Unity
2022.3+ URP with ``Universal Render Pipeline/Particles/Unlit`` shader.

Exports:
    generate_skill_vfx_factory_script -- VBSkillVFXFactory MonoBehaviour
"""

from __future__ import annotations



# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_skill_vfx_factory_script() -> dict:
    """Return C# script dict for ``VBSkillVFXFactory``.

    The generated MonoBehaviour is placed under ``Assets/Scripts/VFX/`` and
    provides:
    - 12 visual archetype builder methods
    - 4-phase skill sequencing (charge / execute / impact / aftermath)
    - 30 pre-built skill configs in a static library
    - ``PlaySkill(name, brand, origin, target)`` one-call API
    """

    script = (
        _CS_HEADER
        + _CS_CONFIG_STRUCTS
        + _CS_BRAND_COLORS
        + _CS_FACTORY_FIELDS
        + _CS_PLAY_SKILL
        + _CS_EXECUTE_SEQUENCE
        + _CS_ARCHETYPE_ARC_BOLT
        + _CS_ARCHETYPE_PROJECTILE_ORB
        + _CS_ARCHETYPE_GROUND_RING
        + _CS_ARCHETYPE_SHIELD_DOME
        + _CS_ARCHETYPE_BEAM_RAY
        + _CS_ARCHETYPE_CONE_BLAST
        + _CS_ARCHETYPE_SUMMON_CIRCLE
        + _CS_ARCHETYPE_AURA_WRAP
        + _CS_ARCHETYPE_IMPACT_BURST
        + _CS_ARCHETYPE_VORTEX_SUCTION
        + _CS_ARCHETYPE_TRAIL_SLASH
        + _CS_ARCHETYPE_ENVIRONMENTAL_MARK
        + _CS_HELPERS
        + _CS_SKILL_LIBRARY
        + _CS_FOOTER
    )

    return {
        "script_path": "Assets/Scripts/VFX/VBSkillVFXFactory.cs",
        "script_content": script,
        "next_steps": [
            "Open Unity Editor and wait for compilation",
            "Attach VBSkillVFXFactory to a manager GameObject in the scene",
            "Call VBSkillVFXFactory.Instance.PlaySkill(\"chain_lightning\", \"SURGE\", origin, target)",
            "30 pre-built skills available via SKILL_LIBRARY dictionary",
            "Create custom skills by populating a SkillVFXConfig with archetype calls",
        ],
    }


# ===================================================================== #
#  C# source fragments                                                   #
# ===================================================================== #

_CS_HEADER = r'''// -----------------------------------------------------------------
// VBSkillVFXFactory.cs  --  Auto-generated by VeilBreakers MCP
// Universal Skill VFX Factory -- 12 archetypes, 4-phase sequencing,
// 30 pre-built skills.  Compose ANY skill from building blocks.
// -----------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
#if PRIME_TWEEN
using PrimeTween;
#endif

namespace VeilBreakers.VFX
{
    /// <summary>
    /// Universal factory that composes multi-phase skill VFX from 12 visual
    /// archetypes.  Attach to a persistent manager GameObject.
    /// </summary>
    public class VBSkillVFXFactory : MonoBehaviour
    {
        public static VBSkillVFXFactory Instance { get; private set; }

        void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
            InitSkillLibrary();
        }
'''

_CS_CONFIG_STRUCTS = r'''
        // =============================================================
        // Config structs
        // =============================================================

        [Serializable]
        public class SkillVFXConfig
        {
            public string skillName;
            public string brand;
            public ArchetypeCall[] chargePhase;
            public ArchetypeCall[] executePhase;
            public ArchetypeCall[] impactPhase;
            public ArchetypeCall[] aftermathPhase;
            public float chargeDuration = 0.3f;
            public float executeDuration = 0.2f;
            public float impactDuration = 0.15f;
            public float aftermathDuration = 1f;
            public float screenShakeIntensity = 0f;
            public float chromAbIntensity = 0f;
            public float slowMoScale = 1f;
            public float slowMoDuration = 0f;
    public SkillVFXConfig DeepClone()
    {
        var clone = (SkillVFXConfig)MemberwiseClone();
        if (chargePhase != null) clone.chargePhase = (ArchetypeCall[])chargePhase.Clone();
        if (executePhase != null) clone.executePhase = (ArchetypeCall[])executePhase.Clone();
        if (impactPhase != null) clone.impactPhase = (ArchetypeCall[])impactPhase.Clone();
        if (aftermathPhase != null) clone.aftermathPhase = (ArchetypeCall[])aftermathPhase.Clone();
        return clone;
    }

            public SkillVFXConfig Clone()
            {
                return (SkillVFXConfig)DeepClone();
            }
        }

        [Serializable]
        public class ArchetypeCall
        {
            public string archetype;
            public Vector3 offset;
            public float scale = 1f;
            public float delay = 0f;
            public Dictionary<string, float> extra;

            public float Get(string key, float fallback = 0f)
            {
                if (extra != null && extra.TryGetValue(key, out float v)) return v;
                return fallback;
            }
        }
'''

_CS_BRAND_COLORS = r'''
        // =============================================================
        // Brand HDR color lookup (matches VBBrandHDR)
        // =============================================================

        static readonly Dictionary<string, Color> BrandPrimary = new()
        {
            {"IRON",   new Color(0.55f, 0.35f, 0.22f, 1f)},
            {"SAVAGE", new Color(0.71f, 0.18f, 0.18f, 1f)},
            {"SURGE",  new Color(0.24f, 0.55f, 0.86f, 1f)},
            {"VENOM",  new Color(0.31f, 0.71f, 0.24f, 1f)},
            {"DREAD",  new Color(0.24f, 0.47f, 0.27f, 1f)},
            {"LEECH",  new Color(0.55f, 0.53f, 0.20f, 1f)},
            {"GRACE",  new Color(0.86f, 0.86f, 0.94f, 1f)},
            {"MEND",   new Color(0.78f, 0.67f, 0.31f, 1f)},
            {"RUIN",   new Color(0.86f, 0.47f, 0.16f, 1f)},
            {"VOID",   new Color(0.16f, 0.08f, 0.24f, 1f)},
        };

        static readonly Dictionary<string, Color> BrandGlow = new()
        {
            {"IRON",   new Color(0.80f, 0.55f, 0.30f, 1f)},
            {"SAVAGE", new Color(0.86f, 0.27f, 0.27f, 1f)},
            {"SURGE",  new Color(0.39f, 0.71f, 1.00f, 1f)},
            {"VENOM",  new Color(0.47f, 0.86f, 0.39f, 1f)},
            {"DREAD",  new Color(0.35f, 0.70f, 0.40f, 1f)},
            {"LEECH",  new Color(0.70f, 0.65f, 0.25f, 1f)},
            {"GRACE",  new Color(1.00f, 1.00f, 1.00f, 1f)},
            {"MEND",   new Color(0.94f, 0.82f, 0.47f, 1f)},
            {"RUIN",   new Color(1.00f, 0.63f, 0.31f, 1f)},
            {"VOID",   new Color(0.39f, 0.24f, 0.55f, 1f)},
        };

        static readonly Dictionary<string, Color> BrandDark = new()
        {
            {"IRON",   new Color(0.35f, 0.22f, 0.12f, 1f)},
            {"SAVAGE", new Color(0.47f, 0.10f, 0.10f, 1f)},
            {"SURGE",  new Color(0.12f, 0.31f, 0.55f, 1f)},
            {"VENOM",  new Color(0.16f, 0.39f, 0.12f, 1f)},
            {"DREAD",  new Color(0.12f, 0.27f, 0.14f, 1f)},
            {"LEECH",  new Color(0.35f, 0.33f, 0.10f, 1f)},
            {"GRACE",  new Color(0.63f, 0.63f, 0.71f, 1f)},
            {"MEND",   new Color(0.55f, 0.43f, 0.16f, 1f)},
            {"RUIN",   new Color(0.63f, 0.27f, 0.08f, 1f)},
            {"VOID",   new Color(0.06f, 0.02f, 0.10f, 1f)},
        };

        static readonly Dictionary<string, float> BrandBloom = new()
        {
            {"IRON",3f},{"SAVAGE",5f},{"SURGE",5f},{"VENOM",4f},{"DREAD",5f},
            {"LEECH",4f},{"GRACE",6f},{"MEND",4f},{"RUIN",5f},{"VOID",6f},
        };

        Color GetPrimary(string b) => BrandPrimary.TryGetValue(b, out var c) ? c : Color.white;
        Color GetGlow(string b)    => BrandGlow.TryGetValue(b, out var c) ? c : Color.white;
        Color GetDark(string b)    => BrandDark.TryGetValue(b, out var c) ? c : Color.gray;
        float GetBloom(string b)   => BrandBloom.TryGetValue(b, out var v) ? v : 4f;
        Color HDR(Color c, string b) => c * GetBloom(b);
'''

_CS_FACTORY_FIELDS = r'''
        // =============================================================
        // Skill library
        // =============================================================

        public static Dictionary<string, SkillVFXConfig> SKILL_LIBRARY { get; private set; }

        /// <summary>Raised when any skill starts playing.</summary>
        public event Action<string, string> OnSkillStarted;
        /// <summary>Raised when any skill finishes all phases.</summary>
        public event Action<string, string> OnSkillFinished;
'''

_CS_PLAY_SKILL = r'''
        // =============================================================
        // Public API
        // =============================================================

        /// <summary>
        /// Play a pre-built skill by name, overriding brand for color.
        /// </summary>
        public void PlaySkill(string skillName, string brand, Vector3 origin, Vector3 target)
        {
            if (!SKILL_LIBRARY.TryGetValue(skillName, out var template))
            {
                Debug.LogWarning($"[VBSkillVFX] Unknown skill: {skillName}");
                return;
            }
            var config = template.Clone();
            config.brand = brand;
            StartCoroutine(ExecuteSkillSequence(config, origin, target));
        }

        /// <summary>
        /// Play a fully custom config.
        /// </summary>
        public void PlayCustomSkill(SkillVFXConfig config, Vector3 origin, Vector3 target)
        {
            StartCoroutine(ExecuteSkillSequence(config, origin, target));
        }
'''

_CS_EXECUTE_SEQUENCE = r'''
        // =============================================================
        // Phase sequencer
        // =============================================================

        IEnumerator ExecuteSkillSequence(SkillVFXConfig cfg, Vector3 origin, Vector3 target)
        {
            string brand = cfg.brand ?? "SURGE";
            OnSkillStarted?.Invoke(cfg.skillName, brand);

            // -- Phase 1: Charge --
            if (cfg.chargePhase != null)
                yield return StartCoroutine(RunPhase(cfg.chargePhase, brand, origin, target, cfg.chargeDuration));

            // -- Phase 2: Execute --
            if (cfg.executePhase != null)
                yield return StartCoroutine(RunPhase(cfg.executePhase, brand, origin, target, cfg.executeDuration));

            // -- Screen effects at impact --
            if (cfg.screenShakeIntensity > 0f) ApplyScreenShake(cfg.screenShakeIntensity);
            if (cfg.chromAbIntensity > 0f)     ApplyChromaticAberration(cfg.chromAbIntensity);
            if (cfg.slowMoScale < 1f && cfg.slowMoDuration > 0f)
                StartCoroutine(ApplySlowMo(cfg.slowMoScale, cfg.slowMoDuration));

            // -- Phase 3: Impact --
            if (cfg.impactPhase != null)
                yield return StartCoroutine(RunPhase(cfg.impactPhase, brand, origin, target, cfg.impactDuration));

            // -- Phase 4: Aftermath --
            if (cfg.aftermathPhase != null)
                yield return StartCoroutine(RunPhase(cfg.aftermathPhase, brand, origin, target, cfg.aftermathDuration));

            OnSkillFinished?.Invoke(cfg.skillName, brand);
        }

        IEnumerator RunPhase(ArchetypeCall[] calls, string brand, Vector3 origin, Vector3 target, float phaseDur)
        {
            float phaseStart = Time.time;
            foreach (var call in calls)
            {
                if (call.delay > 0f) yield return new WaitForSeconds(call.delay);
                SpawnArchetype(call, brand, origin, target, phaseDur);
            }
            float elapsed = Time.time - phaseStart;
            if (elapsed < phaseDur)
                yield return new WaitForSeconds(phaseDur - elapsed);
        }

        void SpawnArchetype(ArchetypeCall call, string brand, Vector3 origin, Vector3 target, float lifetime)
        {
            Vector3 pos = origin + call.offset;
            float s = call.scale;
            switch (call.archetype)
            {
                case "arc_bolt":           Archetype_ArcBolt(pos, target, brand, s, lifetime); break;
                case "projectile_orb":     Archetype_ProjectileOrb(pos, target, brand, s, lifetime); break;
                case "ground_ring":        Archetype_GroundRing(pos, brand, s, lifetime); break;
                case "shield_dome":        Archetype_ShieldDome(pos, brand, s, lifetime); break;
                case "beam_ray":           Archetype_BeamRay(pos, target, brand, s, lifetime); break;
                case "cone_blast":         Archetype_ConeBlast(pos, target, brand, s, lifetime); break;
                case "summon_circle":      Archetype_SummonCircle(pos, brand, s, lifetime); break;
                case "aura_wrap":          Archetype_AuraWrap(pos, brand, s, lifetime); break;
                case "impact_burst":       Archetype_ImpactBurst(pos, brand, s, lifetime); break;
                case "vortex_suction":     Archetype_VortexSuction(pos, brand, s, lifetime); break;
                case "trail_slash":        Archetype_TrailSlash(pos, target, brand, s, lifetime); break;
                case "environmental_mark": Archetype_EnvironmentalMark(pos, brand, s, lifetime); break;
                default:
                    Debug.LogWarning($"[VBSkillVFX] Unknown archetype: {call.archetype}");
                    break;
            }
        }
'''

# -----------------------------------------------------------------------
# 12 Archetype methods
# -----------------------------------------------------------------------

_CS_ARCHETYPE_ARC_BOLT = r'''
        // =============================================================
        // Archetype 1: ARC BOLT -- jagged lightning between two points
        // =============================================================

        void Archetype_ArcBolt(Vector3 start, Vector3 end, string brand, float scale, float lifetime)
        {
            Color glow = HDR(GetGlow(brand), brand);
            Color core = HDR(Color.white, brand);
            float width = 0.08f * scale;
            int segments = 12;
            int branches = Mathf.RoundToInt(2 * scale);

            // -- Core bolt LineRenderer --
            var boltGO = new GameObject("VFX_ArcBolt");
            var lr = boltGO.AddComponent<LineRenderer>();
            lr.material = CreateAdditiveMat(glow);
            lr.startWidth = width; lr.endWidth = width * 0.3f;
            lr.widthCurve = AnimationCurve.EaseInOut(0, 1f, 1f, 0.2f);
            lr.positionCount = segments + 1;
            lr.useWorldSpace = true;
            GenerateBoltPath(lr, start, end, segments, scale * 0.25f);

            // -- Glow trail particles along path --
            var glowGO = CreateChild(boltGO, "GlowTrail");
            var ps = AddParticleSystem(glowGO, glow, 40, lifetime * 0.5f, 0.06f * scale);
            var shape = ps.shape; shape.shapeType = ParticleSystemShapeType.Cone;
            shape.radius = Vector3.Distance(start, end);
            var em = ps.emission; em.rateOverTime = 60f;

            // -- Core flash --
            var flashGO = CreateChild(boltGO, "CoreFlash");
            var fPS = AddParticleSystem(flashGO, core, 3, 0.06f, 0.2f * scale);
            var fEmit = fPS.emission; fEmit.rateOverTime = 0;
            fEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 3) });

            // -- Branch sub-bolts --
            for (int i = 0; i < branches; i++)
            {
                float t = UnityEngine.Random.Range(0.2f, 0.8f);
                Vector3 branchStart = Vector3.Lerp(start, end, t);
                Vector3 branchEnd = branchStart + UnityEngine.Random.insideUnitSphere * scale * 1.2f;
                var brGO = CreateChild(boltGO, $"Branch_{i}");
                var brLR = brGO.AddComponent<LineRenderer>();
                brLR.material = CreateAdditiveMat(glow * 0.7f);
                brLR.startWidth = width * 0.5f; brLR.endWidth = width * 0.1f;
                brLR.positionCount = 6;
                brLR.useWorldSpace = true;
                GenerateBoltPath(brLR, branchStart, branchEnd, 5, scale * 0.15f);
            }

            // -- Flicker regeneration coroutine --
            StartCoroutine(FlickerBolt(lr, start, end, segments, scale * 0.25f, lifetime));

            // -- Point light --
            var lightGO = CreateChild(boltGO, "BoltLight");
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = glow;
            light.intensity = 3f * scale; light.range = 4f * scale;
            lightGO.transform.position = Vector3.Lerp(start, end, 0.5f);
            Tween.LightIntensity(light, 0f, lifetime, Ease.InQuad);

            Destroy(boltGO, lifetime + 0.1f);
        }

        void GenerateBoltPath(LineRenderer lr, Vector3 a, Vector3 b, int segs, float jitter)
        {
            for (int i = 0; i <= segs; i++)
            {
                float t = (float)i / segs;
                Vector3 p = Vector3.Lerp(a, b, t);
                if (i > 0 && i < segs)
                {
                    Vector3 perp = Vector3.Cross(b - a, Vector3.up).normalized;
                    p += perp * UnityEngine.Random.Range(-jitter, jitter);
                    p.y += UnityEngine.Random.Range(-jitter * 0.5f, jitter * 0.5f);
                }
                lr.SetPosition(i, p);
            }
        }

        IEnumerator FlickerBolt(LineRenderer lr, Vector3 a, Vector3 b, int segs, float jitter, float dur)
        {
            float t = 0f;
            while (t < dur && lr != null)
            {
                GenerateBoltPath(lr, a, b, segs, jitter * (1f - t / dur));
                lr.startWidth = Mathf.Lerp(lr.startWidth, 0f, t / dur * 0.3f);
                yield return new WaitForSeconds(0.03f);
                t += 0.03f;
            }
        }
'''

_CS_ARCHETYPE_PROJECTILE_ORB = r'''
        // =============================================================
        // Archetype 2: PROJECTILE ORB -- homing/straight projectile
        // =============================================================

        void Archetype_ProjectileOrb(Vector3 origin, Vector3 target, string brand, float scale, float lifetime)
        {
            Color primary = HDR(GetPrimary(brand), brand);
            Color glow = HDR(GetGlow(brand), brand);
            float speed = 12f * scale;
            float size = 0.2f * scale;

            var root = new GameObject("VFX_ProjectileOrb");
            root.transform.position = origin;

            // -- Core glow particle --
            var coreGO = CreateChild(root, "Core");
            var corePS = AddParticleSystem(coreGO, glow, 1, lifetime, size);
            var coreMain = corePS.main;
            coreMain.simulationSpace = ParticleSystemSimulationSpace.Local;
            var coreEmit = corePS.emission; coreEmit.rateOverTime = 0;
            coreEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 1) });

            // -- Trail smoke particles --
            var trailGO = CreateChild(root, "Trail");
            var trailPS = AddParticleSystem(trailGO, primary * 0.6f, 30, 0.4f, size * 0.6f);
            var trailMain = trailPS.main;
            trailMain.simulationSpace = ParticleSystemSimulationSpace.World;
            var trailShape = trailPS.shape;
            trailShape.shapeType = ParticleSystemShapeType.Sphere;
            trailShape.radius = size * 0.3f;
            var trailSOL = trailPS.sizeOverLifetime; trailSOL.enabled = true;
            trailSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.EaseInOut(0, 1, 1, 0));

            // -- Point light --
            var lightGO = CreateChild(root, "OrbLight");
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 2.5f * scale; light.range = 3f * scale;

            // -- Fly toward target --
            StartCoroutine(FlyProjectile(root, origin, target, speed, brand, scale, lifetime));
        }

        IEnumerator FlyProjectile(GameObject obj, Vector3 from, Vector3 to, float speed, string brand, float scale, float maxLife)
        {
            float t = 0f;
            float dist = Vector3.Distance(from, to);
            float dur = dist / Mathf.Max(speed, 0.1f);
            while (t < dur && t < maxLife && obj != null)
            {
                t += Time.deltaTime;
                obj.transform.position = Vector3.Lerp(from, to, t / dur);
                yield return null;
            }
            if (obj != null)
            {
                // Impact burst at arrival
                SpawnImpactBurstAt(obj.transform.position, brand, scale * 1.2f);
                Destroy(obj);
            }
        }

        void SpawnImpactBurstAt(Vector3 pos, string brand, float scale)
        {
            Archetype_ImpactBurst(pos, brand, scale, 0.5f);
        }
'''

_CS_ARCHETYPE_GROUND_RING = r'''
        // =============================================================
        // Archetype 3: GROUND RING -- expanding ring on ground plane
        // =============================================================

        void Archetype_GroundRing(Vector3 center, string brand, float scale, float lifetime)
        {
            Color primary = HDR(GetPrimary(brand), brand);
            Color glow = HDR(GetGlow(brand), brand);
            float radius = 3f * scale;

            var root = new GameObject("VFX_GroundRing");
            root.transform.position = center;

            // -- Ring particles expanding outward --
            var ringGO = CreateChild(root, "Ring");
            ringGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f); // horizontal
            var ringPS = AddParticleSystem(ringGO, glow, 60, lifetime * 0.8f, 0.12f * scale);
            var ringShape = ringPS.shape;
            ringShape.shapeType = ParticleSystemShapeType.Circle;
            ringShape.radius = 0.1f;
            ringShape.radiusThickness = 0f; // emit from edge only
            var ringVOL = ringPS.velocityOverLifetime; ringVOL.enabled = true;
            ringVOL.radial = new ParticleSystem.MinMaxCurve(radius / lifetime);
            var ringSOL = ringPS.sizeOverLifetime; ringSOL.enabled = true;
            ringSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.EaseInOut(0, 0.3f, 1, 1));
            var ringCOL = ringPS.colorOverLifetime; ringCOL.enabled = true;
            Gradient ringGrad = new Gradient();
            ringGrad.SetKeys(
                new[] { new GradientColorKey(glow, 0f), new GradientColorKey(primary, 1f) },
                new[] { new GradientAlphaKey(1f, 0f), new GradientAlphaKey(0f, 1f) }
            );
            ringCOL.color = ringGrad;

            // -- Dust/debris along ring edge --
            var dustGO = CreateChild(root, "Dust");
            dustGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
            var dustPS = AddParticleSystem(dustGO, GetDark(brand) * 0.5f + Color.gray * 0.5f, 30, lifetime, 0.15f * scale);
            var dustShape = dustPS.shape;
            dustShape.shapeType = ParticleSystemShapeType.Circle;
            dustShape.radius = radius * 0.5f;
            var dustVOL = dustPS.velocityOverLifetime; dustVOL.enabled = true;
            dustVOL.y = new ParticleSystem.MinMaxCurve(0.5f, 1.5f);

            // -- Ground flash --
            var flashGO = CreateChild(root, "Flash");
            var flashPS = AddParticleSystem(flashGO, glow, 1, 0.15f, radius * 0.3f);
            var flashEmit = flashPS.emission; flashEmit.rateOverTime = 0;
            flashEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 1) });

            // -- Point light pulse --
            var lightGO = CreateChild(root, "RingLight");
            lightGO.transform.position = center + Vector3.up * 0.3f;
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 4f * scale; light.range = radius * 1.5f;
            Tween.LightIntensity(light, 0f, lifetime, Ease.OutQuad);

            Destroy(root, lifetime + 0.2f);
        }
'''

_CS_ARCHETYPE_SHIELD_DOME = r'''
        // =============================================================
        // Archetype 4: SHIELD DOME -- translucent protective sphere
        // =============================================================

        void Archetype_ShieldDome(Vector3 center, string brand, float scale, float lifetime)
        {
            Color primary = GetPrimary(brand);
            Color glow = HDR(GetGlow(brand), brand);
            float radius = 1.5f * scale;

            var root = new GameObject("VFX_ShieldDome");
            root.transform.position = center;

            // -- Sphere mesh with fresnel transparency --
            var domeGO = CreateChild(root, "Dome");
            var mf = domeGO.AddComponent<MeshFilter>();
            mf.mesh = CreateSphereMesh(16, 16);
            var mr = domeGO.AddComponent<MeshRenderer>();
            var mat = new Material(Shader.Find("Universal Render Pipeline/Particles/Unlit"));
            mat.SetColor("_BaseColor", new Color(primary.r, primary.g, primary.b, 0.15f));
            mat.SetFloat("_Surface", 1); // transparent
            mat.SetFloat("_Blend", 0);   // alpha
            mat.renderQueue = 3000;
            mr.material = mat;
            domeGO.transform.localScale = Vector3.one * radius * 2f;

            // Scale in with PrimeTween
            domeGO.transform.localScale = Vector3.zero;
            Tween.Scale(domeGO.transform, Vector3.one * radius * 2f, 0.2f, Ease.OutBack);

            // -- Surface sparkle particles --
            var sparkleGO = CreateChild(root, "Sparkles");
            var sparklePS = AddParticleSystem(sparkleGO, glow, 20, 0.6f, 0.04f * scale);
            var sparkleShape = sparklePS.shape;
            sparkleShape.shapeType = ParticleSystemShapeType.Sphere;
            sparkleShape.radius = radius;
            sparkleShape.radiusThickness = 0f; // surface only

            // -- Inner glow particles --
            var innerGO = CreateChild(root, "InnerGlow");
            var innerPS = AddParticleSystem(innerGO, primary * 0.4f, 5, lifetime * 0.8f, radius * 0.8f);
            var innerMain = innerPS.main;
            innerMain.simulationSpace = ParticleSystemSimulationSpace.Local;

            // -- Point light --
            var lightGO = CreateChild(root, "DomeLight");
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 2f * scale; light.range = radius * 2f;

            // -- Pulse opacity with PrimeTween --
            Tween.MaterialColor(mat, new Color(primary.r, primary.g, primary.b, 0.25f), lifetime * 0.5f,
                cycles: 3, cycleMode: CycleMode.Yoyo);

            Destroy(root, lifetime + 0.3f);
        }
'''

_CS_ARCHETYPE_BEAM_RAY = r'''
        // =============================================================
        // Archetype 5: BEAM RAY -- sustained beam between two points
        // =============================================================

        void Archetype_BeamRay(Vector3 origin, Vector3 target, string brand, float scale, float lifetime)
        {
            Color glow = HDR(GetGlow(brand), brand);
            Color core = HDR(Color.white * 0.9f + GetGlow(brand) * 0.1f, brand);
            float width = 0.12f * scale;

            var root = new GameObject("VFX_BeamRay");
            root.transform.position = origin;

            // -- Core beam LineRenderer --
            var beamGO = CreateChild(root, "Beam");
            var lr = beamGO.AddComponent<LineRenderer>();
            lr.material = CreateAdditiveMat(core);
            lr.startWidth = width; lr.endWidth = width * 0.8f;
            lr.positionCount = 2;
            lr.useWorldSpace = true;
            lr.SetPosition(0, origin); lr.SetPosition(1, target);

            // -- Outer glow beam --
            var outerGO = CreateChild(root, "OuterGlow");
            var olr = outerGO.AddComponent<LineRenderer>();
            olr.material = CreateAdditiveMat(glow * 0.4f);
            olr.startWidth = width * 2.5f; olr.endWidth = width * 2f;
            olr.positionCount = 2; olr.useWorldSpace = true;
            olr.SetPosition(0, origin); olr.SetPosition(1, target);

            // -- Particle stream along beam --
            var streamGO = CreateChild(root, "Stream");
            streamGO.transform.position = origin;
            streamGO.transform.LookAt(target);
            var streamPS = AddParticleSystem(streamGO, glow, 40, 0.3f, 0.05f * scale);
            var streamShape = streamPS.shape;
            streamShape.shapeType = ParticleSystemShapeType.Cone;
            streamShape.angle = 2f; streamShape.radius = width * 0.3f;
            streamShape.length = Vector3.Distance(origin, target);
            var streamVOL = streamPS.velocityOverLifetime; streamVOL.enabled = true;
            streamVOL.z = new ParticleSystem.MinMaxCurve(8f * scale);

            // -- Impact sparks at target --
            var impactGO = CreateChild(root, "ImpactSparks");
            impactGO.transform.position = target;
            var impPS = AddParticleSystem(impactGO, glow, 15, 0.4f, 0.04f * scale);
            var impShape = impPS.shape;
            impShape.shapeType = ParticleSystemShapeType.Hemisphere;
            impShape.radius = 0.2f * scale;
            var impVOL = impPS.velocityOverLifetime; impVOL.enabled = true;
            impVOL.radial = new ParticleSystem.MinMaxCurve(2f, 4f);

            // -- Origin glow --
            var origGO = CreateChild(root, "OriginGlow");
            origGO.transform.position = origin;
            var origPS = AddParticleSystem(origGO, core, 3, lifetime, 0.15f * scale);
            var origEmit = origPS.emission; origEmit.rateOverTime = 0;
            origEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 3) });

            // -- Width pulse via PrimeTween --
            StartCoroutine(PulseBeamWidth(lr, olr, width, lifetime));

            // -- Point lights at both ends --
            AddPointLight(root, "OriginLight", origin, GetGlow(brand), 2f * scale, 3f * scale, lifetime);
            AddPointLight(root, "TargetLight", target, GetGlow(brand), 3f * scale, 4f * scale, lifetime);

            Destroy(root, lifetime + 0.2f);
        }

        IEnumerator PulseBeamWidth(LineRenderer core, LineRenderer outer, float baseW, float dur)
        {
            float t = 0f;
            while (t < dur && core != null)
            {
                float pulse = 1f + Mathf.Sin(t * 15f) * 0.2f;
                core.startWidth = baseW * pulse;
                outer.startWidth = baseW * 2.5f * pulse;
                t += Time.deltaTime;
                yield return null;
            }
        }
'''

_CS_ARCHETYPE_CONE_BLAST = r'''
        // =============================================================
        // Archetype 6: CONE BLAST -- cone-shaped area attack
        // =============================================================

        void Archetype_ConeBlast(Vector3 origin, Vector3 target, string brand, float scale, float lifetime)
        {
            Color primary = HDR(GetPrimary(brand), brand);
            Color glow = HDR(GetGlow(brand), brand);
            Vector3 dir = (target - origin).normalized;
            float range = 4f * scale;
            float angle = 35f;

            var root = new GameObject("VFX_ConeBlast");
            root.transform.position = origin;
            root.transform.rotation = Quaternion.LookRotation(dir);

            // -- Main cone particle fan --
            var coneGO = CreateChild(root, "ConeFan");
            var conePS = AddParticleSystem(coneGO, primary, 80, lifetime * 0.7f, 0.18f * scale);
            var coneShape = conePS.shape;
            coneShape.shapeType = ParticleSystemShapeType.Cone;
            coneShape.angle = angle; coneShape.radius = 0.15f;
            var coneMain = conePS.main;
            coneMain.startSpeed = new ParticleSystem.MinMaxCurve(6f * scale, 10f * scale);
            var coneSOL = conePS.sizeOverLifetime; coneSOL.enabled = true;
            coneSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.EaseInOut(0, 0.5f, 1, 1.5f));
            var coneCOL = conePS.colorOverLifetime; coneCOL.enabled = true;
            Gradient coneGrad = new();
            coneGrad.SetKeys(
                new[] { new GradientColorKey(glow, 0f), new GradientColorKey(primary * 0.5f, 1f) },
                new[] { new GradientAlphaKey(1f, 0f), new GradientAlphaKey(0f, 1f) }
            );
            coneCOL.color = coneGrad;

            // -- Edge wisps curling outward --
            var wispGO = CreateChild(root, "EdgeWisps");
            var wispPS = AddParticleSystem(wispGO, primary * 0.4f, 20, lifetime, 0.1f * scale);
            var wispShape = wispPS.shape;
            wispShape.shapeType = ParticleSystemShapeType.Cone;
            wispShape.angle = angle + 10f; wispShape.radius = 0.3f;
            var wispMain = wispPS.main;
            wispMain.startSpeed = new ParticleSystem.MinMaxCurve(2f, 4f);
            var wispNoise = wispPS.noise; wispNoise.enabled = true;
            wispNoise.strength = 1.5f; wispNoise.frequency = 3f;

            // -- Ground scorch decal (simulated with flat particles) --
            var scorchGO = CreateChild(root, "GroundScorch");
            scorchGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
            scorchGO.transform.position = origin + Vector3.down * 0.05f;
            var scorchPS = AddParticleSystem(scorchGO, GetDark(brand) * 0.7f, 8, lifetime * 1.5f, range * 0.4f);
            var scorchEmit = scorchPS.emission; scorchEmit.rateOverTime = 0;
            scorchEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 8) });
            var scorchShape2 = scorchPS.shape;
            scorchShape2.shapeType = ParticleSystemShapeType.Cone;
            scorchShape2.angle = angle; scorchShape2.radius = 0.1f;

            // -- Light --
            AddPointLight(root, "ConeLight", origin + dir * range * 0.3f, GetGlow(brand), 4f * scale, range, lifetime);

            Destroy(root, lifetime * 1.5f + 0.3f);
        }
'''

_CS_ARCHETYPE_SUMMON_CIRCLE = r'''
        // =============================================================
        // Archetype 7: SUMMON CIRCLE -- magic circle on ground
        // =============================================================

        void Archetype_SummonCircle(Vector3 center, string brand, float scale, float lifetime)
        {
            Color glow = HDR(GetGlow(brand), brand);
            Color primary = HDR(GetPrimary(brand), brand);
            float radius = 2f * scale;
            int runeCount = Mathf.RoundToInt(6 * scale);

            var root = new GameObject("VFX_SummonCircle");
            root.transform.position = center;

            // -- Rotating rune ring (orbital velocity) --
            var ringGO = CreateChild(root, "RuneRing");
            ringGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
            var ringPS = AddParticleSystem(ringGO, glow, runeCount, lifetime, 0.12f * scale);
            var ringEmit = ringPS.emission; ringEmit.rateOverTime = 0;
            ringEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, (short)runeCount) });
            var ringShape = ringPS.shape;
            ringShape.shapeType = ParticleSystemShapeType.Circle;
            ringShape.radius = radius; ringShape.radiusThickness = 0f;
            var ringVOL = ringPS.velocityOverLifetime; ringVOL.enabled = true;
            ringVOL.orbitalY = new ParticleSystem.MinMaxCurve(1.5f);

            // -- Inner glow intensifying --
            var innerGO = CreateChild(root, "InnerGlow");
            var innerPS = AddParticleSystem(innerGO, primary * 0.6f, 15, lifetime, 0.2f * scale);
            var innerShape = innerPS.shape;
            innerShape.shapeType = ParticleSystemShapeType.Circle;
            innerShape.radius = radius * 0.5f;
            var innerSOL = innerPS.sizeOverLifetime; innerSOL.enabled = true;
            innerSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.Linear(0, 0.3f, 1, 1.2f));

            // -- Sigil particles rising from circle --
            var risingGO = CreateChild(root, "RisingSigils");
            var risingPS = AddParticleSystem(risingGO, glow * 0.8f, 10, 1.2f, 0.06f * scale);
            var risingShape = risingPS.shape;
            risingShape.shapeType = ParticleSystemShapeType.Circle;
            risingShape.radius = radius;
            var risingVOL = risingPS.velocityOverLifetime; risingVOL.enabled = true;
            risingVOL.y = new ParticleSystem.MinMaxCurve(1f, 2.5f);

            // -- Vertical energy pillar at 70% of lifetime --
            StartCoroutine(SpawnPillarDelayed(center, brand, scale, lifetime * 0.7f, lifetime * 0.3f));

            // -- Ground light --
            var lightGO = CreateChild(root, "CircleLight");
            lightGO.transform.position = center + Vector3.down * 0.1f;
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 0f; light.range = radius * 2f;
            Tween.LightIntensity(light, 5f * scale, lifetime * 0.7f, Ease.InCubic);

            Destroy(root, lifetime + 0.5f);
        }

        IEnumerator SpawnPillarDelayed(Vector3 pos, string brand, float scale, float delay, float dur)
        {
            yield return new WaitForSeconds(delay);
            Color glow = HDR(GetGlow(brand), brand);
            var pillarGO = new GameObject("VFX_EnergyPillar");
            pillarGO.transform.position = pos;
            var ps = AddParticleSystem(pillarGO, glow, 40, dur, 0.08f * scale);
            var main = ps.main;
            main.startSpeed = new ParticleSystem.MinMaxCurve(5f, 10f);
            var shape = ps.shape;
            shape.shapeType = ParticleSystemShapeType.Circle;
            shape.radius = 0.3f * scale;
            var vol = ps.velocityOverLifetime; vol.enabled = true;
            vol.y = new ParticleSystem.MinMaxCurve(6f, 12f);
            AddPointLight(pillarGO, "PillarLight", pos + Vector3.up * 1f, GetGlow(brand), 5f * scale, 5f * scale, dur);
            Destroy(pillarGO, dur + 0.3f);
        }
'''

_CS_ARCHETYPE_AURA_WRAP = r'''
        // =============================================================
        // Archetype 8: AURA WRAP -- persistent effect on character
        // =============================================================

        void Archetype_AuraWrap(Vector3 center, string brand, float scale, float lifetime)
        {
            Color primary = HDR(GetPrimary(brand), brand);
            Color glow = HDR(GetGlow(brand), brand);
            float radius = 0.8f * scale;

            var root = new GameObject("VFX_AuraWrap");
            root.transform.position = center;

            // -- Orbiting surface particles --
            var orbitGO = CreateChild(root, "OrbitParticles");
            var orbitPS = AddParticleSystem(orbitGO, glow, 25, 0.8f, 0.05f * scale);
            var orbitShape = orbitPS.shape;
            orbitShape.shapeType = ParticleSystemShapeType.Sphere;
            orbitShape.radius = radius; orbitShape.radiusThickness = 0f;
            var orbitVOL = orbitPS.velocityOverLifetime; orbitVOL.enabled = true;
            orbitVOL.orbitalY = new ParticleSystem.MinMaxCurve(2f, 3f);
            orbitVOL.orbitalX = new ParticleSystem.MinMaxCurve(0.5f, 1f);

            // -- Pulsing inner glow --
            var glowGO = CreateChild(root, "PulseGlow");
            var glowPS = AddParticleSystem(glowGO, primary * 0.5f, 5, lifetime, radius * 0.6f);
            var glowMain = glowPS.main;
            glowMain.simulationSpace = ParticleSystemSimulationSpace.Local;
            var glowEmit = glowPS.emission;
            glowEmit.rateOverTime = 3f;

            // -- Rising wisps --
            var wispGO = CreateChild(root, "Wisps");
            var wispPS = AddParticleSystem(wispGO, glow * 0.6f, 8, 1f, 0.03f * scale);
            var wispShape = wispPS.shape;
            wispShape.shapeType = ParticleSystemShapeType.Sphere;
            wispShape.radius = radius * 0.7f;
            var wispVOL = wispPS.velocityOverLifetime; wispVOL.enabled = true;
            wispVOL.y = new ParticleSystem.MinMaxCurve(0.5f, 1.2f);

            // -- Color shift for timed buffs --
            var colorShiftGO = CreateChild(root, "ColorShift");
            var csPS = AddParticleSystem(colorShiftGO, glow, 3, lifetime, 0.08f * scale);
            var csCOL = csPS.colorOverLifetime; csCOL.enabled = true;
            Gradient csGrad = new();
            csGrad.SetKeys(
                new[] { new GradientColorKey(glow, 0f), new GradientColorKey(primary, 0.5f), new GradientColorKey(glow, 1f) },
                new[] { new GradientAlphaKey(0f, 0f), new GradientAlphaKey(1f, 0.2f), new GradientAlphaKey(0f, 1f) }
            );
            csCOL.color = csGrad;

            // -- Point light pulsing --
            var lightGO = CreateChild(root, "AuraLight");
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 1.5f * scale; light.range = radius * 2.5f;
            Tween.LightIntensity(light, 2.5f * scale, lifetime * 0.3f,
                cycles: Mathf.Max(1, Mathf.RoundToInt(lifetime / 0.6f)), cycleMode: CycleMode.Yoyo);

            Destroy(root, lifetime + 0.3f);
        }
'''

_CS_ARCHETYPE_IMPACT_BURST = r'''
        // =============================================================
        // Archetype 9: IMPACT BURST -- hit impact at point
        // =============================================================

        void Archetype_ImpactBurst(Vector3 position, string brand, float scale, float lifetime)
        {
            Color glow = HDR(GetGlow(brand), brand);
            Color primary = HDR(GetPrimary(brand), brand);
            Color core = HDR(Color.white, brand);

            var root = new GameObject("VFX_ImpactBurst");
            root.transform.position = position;

            // -- Central flash (1 frame bright, fast fade) --
            var flashGO = CreateChild(root, "Flash");
            var flashPS = AddParticleSystem(flashGO, core, 1, 0.08f, 0.5f * scale);
            var flashEmit = flashPS.emission; flashEmit.rateOverTime = 0;
            flashEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 1) });
            var flashSOL = flashPS.sizeOverLifetime; flashSOL.enabled = true;
            flashSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.EaseInOut(0, 1f, 1, 0f));

            // -- Radial spark burst --
            var sparkGO = CreateChild(root, "Sparks");
            var sparkPS = AddParticleSystem(sparkGO, glow, 20, 0.5f, 0.03f * scale);
            var sparkMain = sparkPS.main;
            sparkMain.startSpeed = new ParticleSystem.MinMaxCurve(3f * scale, 7f * scale);
            sparkMain.gravityModifier = 1.2f;
            var sparkEmit = sparkPS.emission; sparkEmit.rateOverTime = 0;
            sparkEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 20) });
            var sparkShape = sparkPS.shape;
            sparkShape.shapeType = ParticleSystemShapeType.Sphere;
            sparkShape.radius = 0.1f;
            var sparkCol = sparkPS.collision; sparkCol.enabled = true;
            sparkCol.type = ParticleSystemCollisionType.World;
            sparkCol.bounce = 0.3f; sparkCol.dampen = 0.2f;

            // -- Smoke puff (alpha blend, slow dissipate) --
            var smokeGO = CreateChild(root, "Smoke");
            var smokePS = AddParticleSystem(smokeGO, GetDark(brand) * 0.5f + new Color(0.3f,0.3f,0.3f,0.6f), 5, 1.2f, 0.3f * scale);
            var smokeEmit = smokePS.emission; smokeEmit.rateOverTime = 0;
            smokeEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 5) });
            var smokeMain = smokePS.main;
            smokeMain.startSpeed = new ParticleSystem.MinMaxCurve(0.3f, 0.8f);
            var smokeSOL = smokePS.sizeOverLifetime; smokeSOL.enabled = true;
            smokeSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.EaseInOut(0, 0.5f, 1, 1.8f));
            var smokeNoise = smokePS.noise; smokeNoise.enabled = true;
            smokeNoise.strength = 0.5f; smokeNoise.frequency = 2f;
            var smokeCOL = smokePS.colorOverLifetime; smokeCOL.enabled = true;
            Gradient smokeGrad = new();
            smokeGrad.SetKeys(
                new[] { new GradientColorKey(Color.gray, 0f), new GradientColorKey(Color.gray, 1f) },
                new[] { new GradientAlphaKey(0.6f, 0f), new GradientAlphaKey(0f, 1f) }
            );
            smokeCOL.color = smokeGrad;

            // -- Ground crack (flat particle if heavy) --
            if (scale >= 0.8f)
            {
                var crackGO = CreateChild(root, "GroundCrack");
                crackGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
                crackGO.transform.position = position - Vector3.up * 0.02f;
                var crackPS = AddParticleSystem(crackGO, GetDark(brand), 1, lifetime * 2f, 0.6f * scale);
                var crackEmit = crackPS.emission; crackEmit.rateOverTime = 0;
                crackEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 1) });
                var crackCOL2 = crackPS.colorOverLifetime; crackCOL2.enabled = true;
                Gradient crackG = new();
                crackG.SetKeys(
                    new[] { new GradientColorKey(GetDark(brand), 0f), new GradientColorKey(GetDark(brand), 1f) },
                    new[] { new GradientAlphaKey(0.8f, 0f), new GradientAlphaKey(0f, 1f) }
                );
                crackCOL2.color = crackG;
            }

            // -- Flash light --
            var lightGO = CreateChild(root, "ImpactLight");
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 6f * scale; light.range = 4f * scale;
            Tween.LightIntensity(light, 0f, 0.25f, Ease.OutQuad);

            Destroy(root, Mathf.Max(lifetime, 1.5f) + 0.3f);
        }
'''

_CS_ARCHETYPE_VORTEX_SUCTION = r'''
        // =============================================================
        // Archetype 10: VORTEX SUCTION -- inward-pulling area effect
        // =============================================================

        void Archetype_VortexSuction(Vector3 center, string brand, float scale, float lifetime)
        {
            Color primary = HDR(GetPrimary(brand), brand);
            Color glow = HDR(GetGlow(brand), brand);
            Color dark = GetDark(brand);
            float radius = 2.5f * scale;

            var root = new GameObject("VFX_VortexSuction");
            root.transform.position = center;

            // -- Inward-sucked particles (negative radial velocity) --
            var suckGO = CreateChild(root, "SuctionParticles");
            var suckPS = AddParticleSystem(suckGO, glow, 50, 0.6f, 0.06f * scale);
            var suckShape = suckPS.shape;
            suckShape.shapeType = ParticleSystemShapeType.Sphere;
            suckShape.radius = radius;
            suckShape.radiusThickness = 0f;
            var suckVOL = suckPS.velocityOverLifetime; suckVOL.enabled = true;
            suckVOL.radial = new ParticleSystem.MinMaxCurve(-4f * scale, -8f * scale);
            suckVOL.orbitalY = new ParticleSystem.MinMaxCurve(2f, 4f);
            var suckSOL = suckPS.sizeOverLifetime; suckSOL.enabled = true;
            suckSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.EaseInOut(0, 1f, 1, 0.1f));

            // -- Orbiting debris accelerating inward --
            var debrisGO = CreateChild(root, "Debris");
            var debrisPS = AddParticleSystem(debrisGO, dark * 0.7f + Color.gray * 0.3f, 15, 0.8f, 0.1f * scale);
            var debrisShape = debrisPS.shape;
            debrisShape.shapeType = ParticleSystemShapeType.Sphere;
            debrisShape.radius = radius * 0.8f;
            var debrisVOL = debrisPS.velocityOverLifetime; debrisVOL.enabled = true;
            debrisVOL.radial = new ParticleSystem.MinMaxCurve(-2f, -5f);
            debrisVOL.orbitalY = new ParticleSystem.MinMaxCurve(3f, 5f);
            var debrisRot = debrisPS.rotationOverLifetime; debrisRot.enabled = true;
            debrisRot.z = new ParticleSystem.MinMaxCurve(-180f, 180f);

            // -- Dark core sphere --
            var coreGO = CreateChild(root, "DarkCore");
            var corePS = AddParticleSystem(coreGO, dark, 3, lifetime, 0.25f * scale);
            var coreEmit = corePS.emission; coreEmit.rateOverTime = 2f;
            var coreSOL = corePS.sizeOverLifetime; coreSOL.enabled = true;
            coreSOL.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.Linear(0, 0.5f, 1, 1.2f));

            // -- Distortion ring (visual hint of warping) --
            var distGO = CreateChild(root, "DistortionRing");
            distGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
            var distPS = AddParticleSystem(distGO, primary * 0.3f, 8, lifetime, 0.04f * scale);
            var distShape = distPS.shape;
            distShape.shapeType = ParticleSystemShapeType.Circle;
            distShape.radius = radius * 0.3f; distShape.radiusThickness = 0f;
            var distVOL = distPS.velocityOverLifetime; distVOL.enabled = true;
            distVOL.orbitalY = new ParticleSystem.MinMaxCurve(5f, 8f);

            // -- End collapse/explode --
            StartCoroutine(VortexCollapse(center, brand, scale, lifetime));

            // -- Light --
            var lightGO = CreateChild(root, "VortexLight");
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 3f * scale; light.range = radius * 1.5f;
            Tween.LightIntensity(light, 6f * scale, lifetime * 0.8f, Ease.InCubic);

            Destroy(root, lifetime + 0.5f);
        }

        IEnumerator VortexCollapse(Vector3 pos, string brand, float scale, float delay)
        {
            yield return new WaitForSeconds(delay * 0.9f);
            // Collapse flash
            Archetype_ImpactBurst(pos, brand, scale * 1.5f, 0.5f);
        }
'''

_CS_ARCHETYPE_TRAIL_SLASH = r'''
        // =============================================================
        // Archetype 11: TRAIL SLASH -- melee weapon arc trail
        // =============================================================

        void Archetype_TrailSlash(Vector3 origin, Vector3 target, string brand, float scale, float lifetime)
        {
            Color glow = HDR(GetGlow(brand), brand);
            Color primary = HDR(GetPrimary(brand), brand);
            Vector3 dir = (target - origin).normalized;
            float arcLen = 2f * scale;

            var root = new GameObject("VFX_TrailSlash");
            root.transform.position = origin;

            // -- TrailRenderer following arc path --
            var trailGO = CreateChild(root, "SlashTrail");
            var tr = trailGO.AddComponent<TrailRenderer>();
            tr.material = CreateAdditiveMat(glow);
            tr.startWidth = 0.25f * scale; tr.endWidth = 0.02f;
            tr.time = 0.3f;
            tr.widthCurve = AnimationCurve.EaseInOut(0, 1f, 1f, 0f);
            Gradient trGrad = new();
            trGrad.SetKeys(
                new[] { new GradientColorKey(glow, 0f), new GradientColorKey(primary, 1f) },
                new[] { new GradientAlphaKey(1f, 0f), new GradientAlphaKey(0f, 1f) }
            );
            tr.colorGradient = trGrad;

            // -- Animate arc swing --
            StartCoroutine(AnimateSlashArc(trailGO, origin, dir, arcLen, scale, lifetime * 0.3f));

            // -- Spark particles along trail --
            var sparkGO = CreateChild(root, "SlashSparks");
            var sparkPS = AddParticleSystem(sparkGO, glow, 15, 0.3f, 0.03f * scale);
            var sparkMain = sparkPS.main;
            sparkMain.startSpeed = new ParticleSystem.MinMaxCurve(1f, 3f);
            sparkMain.simulationSpace = ParticleSystemSimulationSpace.World;
            var sparkEmit = sparkPS.emission; sparkEmit.rateOverTime = 0;
            sparkEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 15) });
            var sparkShape = sparkPS.shape;
            sparkShape.shapeType = ParticleSystemShapeType.Hemisphere;
            sparkShape.radius = arcLen * 0.3f;

            // -- After-image ghost (persists 0.3s) --
            var ghostGO = CreateChild(root, "AfterImage");
            var ghostPS = AddParticleSystem(ghostGO, primary * 0.4f, 5, 0.3f, 0.15f * scale);
            var ghostEmit = ghostPS.emission; ghostEmit.rateOverTime = 0;
            ghostEmit.SetBursts(new[] { new ParticleSystem.Burst(0.05f, 5) });
            var ghostShape = ghostPS.shape;
            ghostShape.shapeType = ParticleSystemShapeType.Hemisphere;
            ghostShape.radius = arcLen * 0.2f;
            var ghostCOL = ghostPS.colorOverLifetime; ghostCOL.enabled = true;
            Gradient ghostGrad = new();
            ghostGrad.SetKeys(
                new[] { new GradientColorKey(primary, 0f), new GradientColorKey(primary, 1f) },
                new[] { new GradientAlphaKey(0.5f, 0f), new GradientAlphaKey(0f, 1f) }
            );
            ghostCOL.color = ghostGrad;

            // -- Impact sparks at midpoint --
            var impPos = origin + dir * arcLen * 0.5f;
            var impGO = CreateChild(root, "ImpactSparks");
            impGO.transform.position = impPos;
            var impPS = AddParticleSystem(impGO, glow, 10, 0.4f, 0.02f * scale);
            var impEmit = impPS.emission; impEmit.rateOverTime = 0;
            impEmit.SetBursts(new[] { new ParticleSystem.Burst(lifetime * 0.2f, 10) });
            var impMain = impPS.main;
            impMain.startSpeed = new ParticleSystem.MinMaxCurve(2f, 5f);
            impMain.gravityModifier = 0.8f;

            Destroy(root, lifetime + 0.5f);
        }

        IEnumerator AnimateSlashArc(GameObject trail, Vector3 origin, Vector3 dir, float arcLen, float scale, float dur)
        {
            Vector3 right = Vector3.Cross(dir, Vector3.up).normalized;
            float t = 0f;
            float arcAngle = 120f;
            float startAngle = -arcAngle * 0.5f;
            while (t < dur && trail != null)
            {
                float frac = t / dur;
                float angle = startAngle + arcAngle * frac;
                float rad = angle * Mathf.Deg2Rad;
                Vector3 offset = dir * Mathf.Cos(rad) * arcLen + right * Mathf.Sin(rad) * arcLen;
                trail.transform.position = origin + offset;
                t += Time.deltaTime;
                yield return null;
            }
        }
'''

_CS_ARCHETYPE_ENVIRONMENTAL_MARK = r'''
        // =============================================================
        // Archetype 12: ENVIRONMENTAL MARK -- persistent ground effect
        // =============================================================

        void Archetype_EnvironmentalMark(Vector3 position, string brand, float scale, float lifetime)
        {
            Color primary = HDR(GetPrimary(brand), brand);
            Color glow = HDR(GetGlow(brand), brand);
            Color dark = GetDark(brand);
            float radius = 1.5f * scale;

            var root = new GameObject("VFX_EnvironmentalMark");
            root.transform.position = position;

            // -- Ground-plane particle system (horizontal emission) --
            var groundGO = CreateChild(root, "GroundPool");
            groundGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
            groundGO.transform.position = position - Vector3.up * 0.03f;
            var groundPS = AddParticleSystem(groundGO, primary * 0.7f, 20, lifetime * 0.8f, 0.2f * scale);
            var groundShape = groundPS.shape;
            groundShape.shapeType = ParticleSystemShapeType.Circle;
            groundShape.radius = radius;
            var groundMain = groundPS.main;
            groundMain.startSpeed = 0f;
            var groundCOL = groundPS.colorOverLifetime; groundCOL.enabled = true;
            Gradient groundGrad = new();
            groundGrad.SetKeys(
                new[] { new GradientColorKey(primary, 0f), new GradientColorKey(dark, 1f) },
                new[] { new GradientAlphaKey(0.7f, 0f), new GradientAlphaKey(0f, 1f) }
            );
            groundCOL.color = groundGrad;

            // -- Rising wisps/mist from surface --
            var mistGO = CreateChild(root, "RisingMist");
            var mistPS = AddParticleSystem(mistGO, glow * 0.4f, 12, 1.0f, 0.08f * scale);
            var mistShape = mistPS.shape;
            mistShape.shapeType = ParticleSystemShapeType.Circle;
            mistShape.radius = radius * 0.8f;
            var mistVOL = mistPS.velocityOverLifetime; mistVOL.enabled = true;
            mistVOL.y = new ParticleSystem.MinMaxCurve(0.3f, 1.0f);
            var mistNoise = mistPS.noise; mistNoise.enabled = true;
            mistNoise.strength = 0.4f; mistNoise.frequency = 2f;

            // -- Pulsing glow on ground --
            var pulseGO = CreateChild(root, "GroundPulse");
            pulseGO.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
            pulseGO.transform.position = position - Vector3.up * 0.02f;
            var pulsePS = AddParticleSystem(pulseGO, glow * 0.5f, 1, lifetime, radius * 0.8f);
            var pulseEmit = pulsePS.emission; pulseEmit.rateOverTime = 0;
            pulseEmit.SetBursts(new[] { new ParticleSystem.Burst(0f, 1) });

            // -- Damage tick flash every second --
            StartCoroutine(DamageTickFlashes(position, brand, scale, lifetime));

            // -- Ground light --
            var lightGO = CreateChild(root, "MarkLight");
            lightGO.transform.position = position + Vector3.up * 0.2f;
            var light = lightGO.AddComponent<Light>();
            light.type = LightType.Point; light.color = GetGlow(brand);
            light.intensity = 2f * scale; light.range = radius * 2f;
            Tween.LightIntensity(light, 0f, lifetime, Ease.InQuad);

            Destroy(root, lifetime + 0.5f);
        }

        IEnumerator DamageTickFlashes(Vector3 pos, string brand, float scale, float dur)
        {
            float t = 0f;
            float interval = 1f;
            while (t < dur)
            {
                yield return new WaitForSeconds(interval);
                t += interval;
                if (t >= dur) break;
                Color glow = HDR(GetGlow(brand), brand);
                var flashGO = new GameObject("TickFlash");
                flashGO.transform.position = pos;
                var ps = AddParticleSystem(flashGO, glow, 5, 0.15f, 0.08f * scale);
                var emit = ps.emission; emit.rateOverTime = 0;
                emit.SetBursts(new[] { new ParticleSystem.Burst(0f, 5) });
                var main = ps.main;
                main.startSpeed = new ParticleSystem.MinMaxCurve(1f, 2f);
                Destroy(flashGO, 0.3f);
            }
        }
'''

# -----------------------------------------------------------------------
# Shared helpers
# -----------------------------------------------------------------------

_CS_HELPERS = r'''
        // =============================================================
        // Shared helpers
        // =============================================================

        GameObject CreateChild(GameObject parent, string name)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);
            return go;
        }

        ParticleSystem AddParticleSystem(GameObject go, Color color, int maxParticles, float lifetime, float size)
        {
            var ps = go.AddComponent<ParticleSystem>();
            var main = ps.main;
            main.startColor = color;
            main.maxParticles = maxParticles;
            main.startLifetime = lifetime;
            main.startSize = size;
            main.loop = false;
            main.playOnAwake = true;
            main.simulationSpace = ParticleSystemSimulationSpace.World;

            var renderer = go.GetComponent<ParticleSystemRenderer>();
            renderer.material = CreateAdditiveMat(color);
            renderer.renderMode = ParticleSystemRenderMode.Billboard;

            return ps;
        }

        Material CreateAdditiveMat(Color color)
        {
            var mat = new Material(Shader.Find("Universal Render Pipeline/Particles/Unlit"));
            mat.SetColor("_BaseColor", color);
            mat.SetFloat("_Surface", 1);
            mat.SetFloat("_Blend", 1); // Additive
            mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
            mat.EnableKeyword("_ALPHABLEND_ON");
            mat.renderQueue = 3000;
            return mat;
        }

        void AddPointLight(GameObject parent, string name, Vector3 pos, Color color, float intensity, float range, float fadeTime)
        {
            var go = CreateChild(parent, name);
            go.transform.position = pos;
            var light = go.AddComponent<Light>();
            light.type = LightType.Point;
            light.color = color;
            light.intensity = intensity;
            light.range = range;
            Tween.LightIntensity(light, 0f, fadeTime, Ease.OutQuad);
        }

        Mesh CreateSphereMesh(int lonSegments, int latSegments)
        {
            // Procedural sphere -- used for shield dome
            var mesh = new Mesh();
            int vertCount = (lonSegments + 1) * (latSegments + 1);
            var verts = new Vector3[vertCount];
            var uvs = new Vector2[vertCount];
            int idx = 0;
            for (int lat = 0; lat <= latSegments; lat++)
            {
                float theta = Mathf.PI * lat / latSegments;
                float sinT = Mathf.Sin(theta); float cosT = Mathf.Cos(theta);
                for (int lon = 0; lon <= lonSegments; lon++)
                {
                    float phi = 2f * Mathf.PI * lon / lonSegments;
                    verts[idx] = new Vector3(sinT * Mathf.Cos(phi), cosT, sinT * Mathf.Sin(phi)) * 0.5f;
                    uvs[idx] = new Vector2((float)lon / lonSegments, (float)lat / latSegments);
                    idx++;
                }
            }
            int triCount = latSegments * lonSegments * 6;
            var tris = new int[triCount];
            int ti = 0;
            for (int lat = 0; lat < latSegments; lat++)
            {
                for (int lon = 0; lon < lonSegments; lon++)
                {
                    int cur = lat * (lonSegments + 1) + lon;
                    int next = cur + lonSegments + 1;
                    tris[ti++] = cur; tris[ti++] = next; tris[ti++] = cur + 1;
                    tris[ti++] = cur + 1; tris[ti++] = next; tris[ti++] = next + 1;
                }
            }
            mesh.vertices = verts; mesh.uv = uvs; mesh.triangles = tris;
            mesh.RecalculateNormals();
            return mesh;
        }

        // -- Screen effects --

        void ApplyScreenShake(float intensity)
        {
            if (Camera.main == null) return;
            Tween.ShakeLocalPosition(Camera.main.transform, intensity, 0.3f);
        }

        void ApplyChromaticAberration(float intensity)
        {
            // Integration point: if post-processing stack is available, tween ChromAb
            // Fallback: slight camera offset flash
            if (Camera.main == null) return;
            Tween.ShakeLocalPosition(Camera.main.transform, intensity * 0.05f, 0.15f);
        }

        IEnumerator ApplySlowMo(float targetScale, float duration)
        {
            float original = Time.timeScale;
            Time.timeScale = targetScale;
            Time.fixedDeltaTime = 0.02f * targetScale;
            yield return new WaitForSecondsRealtime(duration);
            Time.timeScale = original;
            Time.fixedDeltaTime = 0.02f;
        }
'''

# -----------------------------------------------------------------------
# 30 pre-built skills
# -----------------------------------------------------------------------

_CS_SKILL_LIBRARY = r'''
        // =============================================================
        // Pre-built skill library (30 skills)
        // =============================================================

        void InitSkillLibrary()
        {
            SKILL_LIBRARY = new Dictionary<string, SkillVFXConfig>();

            // ---- MELEE (5) ----

            SKILL_LIBRARY["slash"] = new SkillVFXConfig
            {
                skillName = "slash",
                brand = "IRON",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.3f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "trail_slash", scale = 1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.7f },
                },
                aftermathPhase = null,
                chargeDuration = 0.15f,
                executeDuration = 0.15f,
                impactDuration = 0.1f,
                aftermathDuration = 0f,
                screenShakeIntensity = 0.15f,
            };

            SKILL_LIBRARY["slam"] = new SkillVFXConfig
            {
                skillName = "slam",
                brand = "IRON",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.5f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "trail_slash", scale = 1.2f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1.5f },
                    new ArchetypeCall { archetype = "ground_ring", scale = 1f, delay = 0.05f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.5f },
                },
                chargeDuration = 0.3f,
                executeDuration = 0.15f,
                impactDuration = 0.2f,
                aftermathDuration = 1.5f,
                screenShakeIntensity = 0.5f,
                chromAbIntensity = 0.3f,
            };

            SKILL_LIBRARY["thrust"] = new SkillVFXConfig
            {
                skillName = "thrust",
                brand = "IRON",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.2f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "trail_slash", scale = 0.8f },
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.3f, delay = 0.05f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.9f },
                },
                aftermathPhase = null,
                chargeDuration = 0.1f,
                executeDuration = 0.1f,
                impactDuration = 0.1f,
                screenShakeIntensity = 0.2f,
            };

            SKILL_LIBRARY["cleave"] = new SkillVFXConfig
            {
                skillName = "cleave",
                brand = "SAVAGE",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.6f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "trail_slash", scale = 1.5f },
                    new ArchetypeCall { archetype = "cone_blast", scale = 0.4f, delay = 0.05f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1.3f },
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.6f, delay = 0.1f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.4f },
                },
                chargeDuration = 0.25f,
                executeDuration = 0.2f,
                impactDuration = 0.15f,
                aftermathDuration = 1f,
                screenShakeIntensity = 0.4f,
                chromAbIntensity = 0.2f,
            };

            SKILL_LIBRARY["uppercut"] = new SkillVFXConfig
            {
                skillName = "uppercut",
                brand = "SAVAGE",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.4f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "trail_slash", scale = 1f, offset = Vector3.up * 0.5f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1f, offset = Vector3.up * 1.5f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.3f },
                },
                chargeDuration = 0.15f,
                executeDuration = 0.15f,
                impactDuration = 0.15f,
                aftermathDuration = 0.5f,
                screenShakeIntensity = 0.35f,
                slowMoScale = 0.5f,
                slowMoDuration = 0.15f,
            };

            // ---- PROJECTILE (5) ----

            SKILL_LIBRARY["bolt"] = new SkillVFXConfig
            {
                skillName = "bolt",
                brand = "SURGE",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.3f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.8f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.7f },
                },
                aftermathPhase = null,
                chargeDuration = 0.2f,
                executeDuration = 0.3f,
                impactDuration = 0.1f,
                screenShakeIntensity = 0.1f,
            };

            SKILL_LIBRARY["orb"] = new SkillVFXConfig
            {
                skillName = "orb",
                brand = "DREAD",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.3f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "projectile_orb", scale = 1.2f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1f },
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.5f, delay = 0.1f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.3f },
                },
                chargeDuration = 0.4f,
                executeDuration = 0.3f,
                impactDuration = 0.15f,
                aftermathDuration = 1f,
                screenShakeIntensity = 0.2f,
            };

            SKILL_LIBRARY["arrow"] = new SkillVFXConfig
            {
                skillName = "arrow",
                brand = "VENOM",
                chargePhase = null,
                executePhase = new[] {
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.5f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.5f },
                },
                aftermathPhase = null,
                chargeDuration = 0f,
                executeDuration = 0.2f,
                impactDuration = 0.1f,
                screenShakeIntensity = 0.05f,
            };

            SKILL_LIBRARY["missile"] = new SkillVFXConfig
            {
                skillName = "missile",
                brand = "RUIN",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.4f },
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.2f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "projectile_orb", scale = 1f },
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.7f, delay = 0.1f, offset = Vector3.right * 0.5f },
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.7f, delay = 0.15f, offset = Vector3.left * 0.5f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1.2f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.8f, delay = 0.1f, offset = Vector3.right * 1f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.8f, delay = 0.15f, offset = Vector3.left * 1f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.6f },
                },
                chargeDuration = 0.4f,
                executeDuration = 0.4f,
                impactDuration = 0.2f,
                aftermathDuration = 1.5f,
                screenShakeIntensity = 0.4f,
                chromAbIntensity = 0.3f,
            };

            SKILL_LIBRARY["beam"] = new SkillVFXConfig
            {
                skillName = "beam",
                brand = "GRACE",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.5f },
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.3f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "beam_ray", scale = 1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.3f },
                },
                chargeDuration = 0.5f,
                executeDuration = 0.8f,
                impactDuration = 0.15f,
                aftermathDuration = 0.8f,
                screenShakeIntensity = 0.2f,
            };

            // ---- AoE (5) ----

            SKILL_LIBRARY["eruption"] = new SkillVFXConfig
            {
                skillName = "eruption",
                brand = "RUIN",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.3f },
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.4f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1.5f },
                    new ArchetypeCall { archetype = "cone_blast", scale = 0.8f, offset = Vector3.up * 0.1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 1.2f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 1f },
                },
                chargeDuration = 0.5f,
                executeDuration = 0.2f,
                impactDuration = 0.3f,
                aftermathDuration = 2f,
                screenShakeIntensity = 0.6f,
                chromAbIntensity = 0.4f,
            };

            SKILL_LIBRARY["nova"] = new SkillVFXConfig
            {
                skillName = "nova",
                brand = "SURGE",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.5f },
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.8f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 1.5f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 1.2f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.6f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.5f, delay = 0.05f, offset = Vector3.right * 1f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.5f, delay = 0.08f, offset = Vector3.left * 1f },
                },
                aftermathPhase = null,
                chargeDuration = 0.4f,
                executeDuration = 0.15f,
                impactDuration = 0.2f,
                screenShakeIntensity = 0.5f,
                chromAbIntensity = 0.5f,
            };

            SKILL_LIBRARY["rain"] = new SkillVFXConfig
            {
                skillName = "rain",
                brand = "VENOM",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.5f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.4f, offset = Vector3.up * 5f },
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.3f, offset = new Vector3(1f, 5f, 0f), delay = 0.1f },
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.3f, offset = new Vector3(-1f, 5f, 0.5f), delay = 0.2f },
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.35f, offset = new Vector3(0.5f, 5f, -0.8f), delay = 0.3f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.5f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.4f, delay = 0.1f, offset = Vector3.right * 1f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.4f, delay = 0.2f, offset = Vector3.left * 1f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 1.2f },
                },
                chargeDuration = 0.5f,
                executeDuration = 0.6f,
                impactDuration = 0.3f,
                aftermathDuration = 2f,
                screenShakeIntensity = 0.2f,
            };

            SKILL_LIBRARY["field"] = new SkillVFXConfig
            {
                skillName = "field",
                brand = "MEND",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.6f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.8f },
                },
                impactPhase = null,
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 1.5f },
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.4f },
                },
                chargeDuration = 0.3f,
                executeDuration = 0.2f,
                impactDuration = 0f,
                aftermathDuration = 3f,
            };

            SKILL_LIBRARY["shockwave"] = new SkillVFXConfig
            {
                skillName = "shockwave",
                brand = "IRON",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.6f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 2f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.5f },
                },
                chargeDuration = 0.2f,
                executeDuration = 0.1f,
                impactDuration = 0.3f,
                aftermathDuration = 1f,
                screenShakeIntensity = 0.6f,
                chromAbIntensity = 0.3f,
            };

            // ---- DEFENSIVE (5) ----

            SKILL_LIBRARY["shield"] = new SkillVFXConfig
            {
                skillName = "shield",
                brand = "IRON",
                chargePhase = null,
                executePhase = new[] {
                    new ArchetypeCall { archetype = "shield_dome", scale = 1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.3f },
                },
                aftermathPhase = null,
                chargeDuration = 0f,
                executeDuration = 0.2f,
                impactDuration = 0.1f,
                aftermathDuration = 0f,
            };

            SKILL_LIBRARY["barrier"] = new SkillVFXConfig
            {
                skillName = "barrier",
                brand = "GRACE",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.3f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "shield_dome", scale = 1.3f },
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.4f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.4f },
                },
                aftermathPhase = null,
                chargeDuration = 0.3f,
                executeDuration = 0.3f,
                impactDuration = 0.15f,
            };

            SKILL_LIBRARY["dodge"] = new SkillVFXConfig
            {
                skillName = "dodge",
                brand = "SURGE",
                chargePhase = null,
                executePhase = new[] {
                    new ArchetypeCall { archetype = "trail_slash", scale = 0.4f },
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.3f },
                },
                impactPhase = null,
                aftermathPhase = null,
                chargeDuration = 0f,
                executeDuration = 0.15f,
                impactDuration = 0f,
            };

            SKILL_LIBRARY["parry"] = new SkillVFXConfig
            {
                skillName = "parry",
                brand = "IRON",
                chargePhase = null,
                executePhase = new[] {
                    new ArchetypeCall { archetype = "shield_dome", scale = 0.5f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.3f },
                },
                aftermathPhase = null,
                chargeDuration = 0f,
                executeDuration = 0.1f,
                impactDuration = 0.15f,
                screenShakeIntensity = 0.3f,
            };

            SKILL_LIBRARY["absorb"] = new SkillVFXConfig
            {
                skillName = "absorb",
                brand = "LEECH",
                chargePhase = null,
                executePhase = new[] {
                    new ArchetypeCall { archetype = "shield_dome", scale = 0.8f },
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.4f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.5f },
                },
                aftermathPhase = null,
                chargeDuration = 0f,
                executeDuration = 0.3f,
                impactDuration = 0.2f,
            };

            // ---- UTILITY (5) ----

            SKILL_LIBRARY["heal"] = new SkillVFXConfig
            {
                skillName = "heal",
                brand = "MEND",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.4f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.8f },
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.5f },
                },
                impactPhase = null,
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.3f },
                },
                chargeDuration = 0.3f,
                executeDuration = 0.4f,
                impactDuration = 0f,
                aftermathDuration = 1f,
            };

            SKILL_LIBRARY["buff"] = new SkillVFXConfig
            {
                skillName = "buff",
                brand = "GRACE",
                chargePhase = null,
                executePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.3f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.4f },
                },
                chargeDuration = 0f,
                executeDuration = 0.2f,
                impactDuration = 0.1f,
                aftermathDuration = 2f,
            };

            SKILL_LIBRARY["debuff"] = new SkillVFXConfig
            {
                skillName = "debuff",
                brand = "DREAD",
                chargePhase = null,
                executePhase = new[] {
                    new ArchetypeCall { archetype = "projectile_orb", scale = 0.4f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.6f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.4f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.3f },
                },
                chargeDuration = 0f,
                executeDuration = 0.2f,
                impactDuration = 0.15f,
                aftermathDuration = 2f,
            };

            SKILL_LIBRARY["summon"] = new SkillVFXConfig
            {
                skillName = "summon",
                brand = "VOID",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 1f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.5f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1f },
                    new ArchetypeCall { archetype = "ground_ring", scale = 0.6f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.4f },
                },
                chargeDuration = 0.8f,
                executeDuration = 0.4f,
                impactDuration = 0.2f,
                aftermathDuration = 1f,
                screenShakeIntensity = 0.3f,
                chromAbIntensity = 0.3f,
            };

            SKILL_LIBRARY["teleport"] = new SkillVFXConfig
            {
                skillName = "teleport",
                brand = "VOID",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.4f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.8f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.5f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.6f },
                },
                aftermathPhase = null,
                chargeDuration = 0.2f,
                executeDuration = 0.1f,
                impactDuration = 0.2f,
                chromAbIntensity = 0.4f,
            };

            // ---- SIGNATURE (5) ----

            SKILL_LIBRARY["chain_lightning"] = new SkillVFXConfig
            {
                skillName = "chain_lightning",
                brand = "SURGE",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.5f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "arc_bolt", scale = 1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.8f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.7f, delay = 0.1f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.6f, delay = 0.15f, offset = Vector3.right * 2f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.5f, delay = 0.2f, offset = Vector3.right * 2f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.4f, delay = 0.25f, offset = Vector3.right * 4f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.3f },
                },
                chargeDuration = 0.3f,
                executeDuration = 0.2f,
                impactDuration = 0.4f,
                aftermathDuration = 1f,
                screenShakeIntensity = 0.3f,
                chromAbIntensity = 0.3f,
            };

            SKILL_LIBRARY["void_rend"] = new SkillVFXConfig
            {
                skillName = "void_rend",
                brand = "VOID",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.3f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "trail_slash", scale = 1f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.4f, delay = 0.05f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "vortex_suction", scale = 1f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 1.2f, delay = 0.3f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 1f },
                },
                chargeDuration = 0.3f,
                executeDuration = 0.2f,
                impactDuration = 0.5f,
                aftermathDuration = 1.5f,
                screenShakeIntensity = 0.5f,
                chromAbIntensity = 0.6f,
                slowMoScale = 0.3f,
                slowMoDuration = 0.3f,
            };

            SKILL_LIBRARY["breath_weapon"] = new SkillVFXConfig
            {
                skillName = "breath_weapon",
                brand = "RUIN",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.7f },
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.2f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "cone_blast", scale = 1.5f },
                    new ArchetypeCall { archetype = "beam_ray", scale = 0.5f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 1f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.8f, delay = 0.1f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "environmental_mark", scale = 1.5f },
                },
                chargeDuration = 0.5f,
                executeDuration = 0.8f,
                impactDuration = 0.2f,
                aftermathDuration = 2.5f,
                screenShakeIntensity = 0.4f,
                chromAbIntensity = 0.3f,
            };

            SKILL_LIBRARY["evolution"] = new SkillVFXConfig
            {
                skillName = "evolution",
                brand = "LEECH",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 1f },
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.6f },
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.8f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "impact_burst", scale = 1.5f },
                    new ArchetypeCall { archetype = "ground_ring", scale = 1.2f },
                    new ArchetypeCall { archetype = "shield_dome", scale = 0.8f, delay = 0.1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "ground_ring", scale = 2f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.6f, delay = 0.1f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.5f, delay = 0.15f, offset = Vector3.right * 1.5f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.5f, delay = 0.2f, offset = Vector3.left * 1.5f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "aura_wrap", scale = 1.2f },
                    new ArchetypeCall { archetype = "environmental_mark", scale = 0.8f },
                },
                chargeDuration = 1f,
                executeDuration = 0.3f,
                impactDuration = 0.4f,
                aftermathDuration = 2f,
                screenShakeIntensity = 0.7f,
                chromAbIntensity = 0.6f,
                slowMoScale = 0.2f,
                slowMoDuration = 0.5f,
            };

            SKILL_LIBRARY["capture"] = new SkillVFXConfig
            {
                skillName = "capture",
                brand = "DREAD",
                chargePhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.8f },
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.4f },
                },
                executePhase = new[] {
                    new ArchetypeCall { archetype = "beam_ray", scale = 0.6f },
                    new ArchetypeCall { archetype = "arc_bolt", scale = 0.5f, delay = 0.1f },
                },
                impactPhase = new[] {
                    new ArchetypeCall { archetype = "shield_dome", scale = 0.7f },
                    new ArchetypeCall { archetype = "vortex_suction", scale = 0.8f },
                    new ArchetypeCall { archetype = "impact_burst", scale = 0.6f, delay = 0.2f },
                },
                aftermathPhase = new[] {
                    new ArchetypeCall { archetype = "summon_circle", scale = 0.4f },
                    new ArchetypeCall { archetype = "aura_wrap", scale = 0.3f },
                },
                chargeDuration = 0.6f,
                executeDuration = 0.4f,
                impactDuration = 0.5f,
                aftermathDuration = 1.5f,
                screenShakeIntensity = 0.4f,
                chromAbIntensity = 0.4f,
                slowMoScale = 0.4f,
                slowMoDuration = 0.3f,
            };
        }
'''

_CS_FOOTER = r'''
    }
}
'''
