"""Procedural particle texture generator C# template for Unity.

Generates a static utility class ``VBProceduralParticleTextures`` that creates
high-quality particle textures entirely from code at runtime -- no external
assets required.  Textures are cached on first access so subsequent calls are
free.

Texture types (10):
    smoke, spark, soft_glow, magic_rune, blood_splatter,
    lightning, energy_orb, distortion_normal, ground_crack, dissolve_mask

Also includes two material factory helpers:
    CreateAdditiveMaterial  -- additive blend (sparks, glows, lightning)
    CreateAlphaBlendMaterial -- alpha blend (smoke, blood, cracks)

All noise algorithms (Perlin, Voronoi) are implemented inline in C# so
the class has zero external dependencies beyond Unity 2022.3 URP.

Each function returns ``{"script_path", "script_content", "next_steps"}``.
"""

from __future__ import annotations

from ._cs_sanitize import sanitize_cs_string, sanitize_cs_identifier


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_procedural_particle_textures_script() -> dict:
    """Return C# script dict for ``VBProceduralParticleTextures``.

    The generated class lives under ``Assets/Scripts/VFX/`` (runtime, not
    Editor) so any gameplay script can call
    ``VBProceduralParticleTextures.GetTexture("smoke")`` at runtime.
    """

    script = _CS_HEADER + _CS_CACHE + _CS_NOISE + _CS_VORONOI + _CS_TEXTURES + _CS_MATERIALS + _CS_FOOTER

    return {
        "script_path": "Assets/Scripts/VFX/VBProceduralParticleTextures.cs",
        "script_content": script,
        "next_steps": [
            "Open Unity Editor and wait for compilation",
            "Call VBProceduralParticleTextures.GetTexture(\"smoke\") from any script",
            "Or use CreateAdditiveMaterial / CreateAlphaBlendMaterial helpers",
            "Textures are generated once on first access and cached automatically",
        ],
    }


# ===================================================================== #
#  C# source fragments -- assembled in generate_ function above         #
# ===================================================================== #

_CS_HEADER = r'''// -----------------------------------------------------------------
// VBProceduralParticleTextures.cs  --  Auto-generated by VeilBreakers MCP
// Procedural particle texture library -- zero external assets needed.
// -----------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace VeilBreakers.VFX
{
    /// <summary>
    /// Procedurally generates and caches 10 particle texture types plus
    /// two material factory methods.  All noise is computed inline.
    /// </summary>
    public static class VBProceduralParticleTextures
    {
'''

# ---- cache + public accessor ----
_CS_CACHE = r'''
        // ---------------------------------------------------------
        // Texture cache
        // ---------------------------------------------------------
        private static readonly Dictionary<string, Texture2D> _texCache =
            new Dictionary<string, Texture2D>();
        private static readonly Dictionary<int, Material> _matCache =
            new Dictionary<int, Material>();

        /// <summary>Retrieve (or generate) a named procedural texture.</summary>
        public static Texture2D GetTexture(string type, int size = 0)
        {
            string key = size > 0 ? $"{type}_{size}" : type;
            if (_texCache.TryGetValue(key, out var cached) && cached != null)
                return cached;

            Texture2D tex = type switch
            {
                "smoke"             => GenerateSmoke(size > 0 ? size : 256),
                "spark"             => GenerateSpark(size > 0 ? size : 64),
                "soft_glow"         => GenerateSoftGlow(size > 0 ? size : 128),
                "magic_rune"        => GenerateMagicRune(size > 0 ? size : 256),
                "blood_splatter"    => GenerateBloodSplatter(size > 0 ? size : 256),
                "lightning"         => GenerateLightning(size > 0 ? size : 256),
                "energy_orb"        => GenerateEnergyOrb(size > 0 ? size : 128),
                "distortion_normal" => GenerateDistortionNormal(size > 0 ? size : 128),
                "ground_crack"      => GenerateGroundCrack(size > 0 ? size : 256),
                "dissolve_mask"     => GenerateDissolveMask(size > 0 ? size : 256),
                _ => GenerateSoftGlow(128),
            };
            tex.name = $"VB_Proc_{type}";
            _texCache[key] = tex;
            return tex;
        }

        /// <summary>Purge all cached textures and materials.</summary>
        public static void ClearCache()
        {
            foreach (var t in _texCache.Values)
                if (t != null) UnityEngine.Object.Destroy(t);
            _texCache.Clear();
            foreach (var m in _matCache.Values)
                if (m != null) UnityEngine.Object.Destroy(m);
            _matCache.Clear();
        }

'''

# ---- Perlin noise ----
_CS_NOISE = r'''
        // =============================================================
        // Improved Perlin noise (Ken Perlin, 2002) -- self-contained
        // =============================================================
        private static readonly int[] _perm = new int[512];
        private static bool _permReady;

        private static void EnsurePerm()
        {
            if (_permReady) return;
            int[] p = {
                151,160,137,91,90,15,131,13,201,95,96,53,194,233,7,225,
                140,36,103,30,69,142,8,99,37,240,21,10,23,190,6,148,
                247,120,234,75,0,26,197,62,94,252,219,203,117,35,11,32,
                57,177,33,88,237,149,56,87,174,20,125,136,171,168,68,175,
                74,165,71,134,139,48,27,166,77,146,158,231,83,111,229,122,
                60,211,133,230,220,105,92,41,55,46,245,40,244,102,143,54,
                65,25,63,161,1,216,80,73,209,76,132,187,208,89,18,169,
                200,196,135,130,116,188,159,86,164,100,109,198,173,186,3,64,
                52,217,226,250,124,123,5,202,38,147,118,126,255,82,85,212,
                207,206,59,227,47,16,58,17,182,189,28,42,223,183,170,213,
                119,248,152,2,44,154,163,70,221,153,101,155,167,43,172,9,
                129,22,39,253,19,98,108,110,79,113,224,232,178,185,112,104,
                218,246,97,228,251,34,242,193,238,210,144,12,191,179,162,241,
                81,51,145,235,249,14,239,107,49,192,214,31,181,199,106,157,
                4,184,204,176,115,121,50,45,127,4,150,254,138,236,205,93,
                222,114,67,29,24,72,243,141,128,195,78,66,215,61,156,180
            };
            for (int i = 0; i < 256; i++)
            {
                _perm[i] = p[i];
                _perm[256 + i] = p[i];
            }
            _permReady = true;
        }

        private static float Fade(float t) => t * t * t * (t * (t * 6f - 15f) + 10f);

        private static float Grad(int hash, float x, float y)
        {
            int h = hash & 7;
            float u = h < 4 ? x : y;
            float v = h < 4 ? y : x;
            return ((h & 1) == 0 ? u : -u) + ((h & 2) == 0 ? v : -v);
        }

        /// <summary>2-D Perlin noise returning roughly [-1,1].</summary>
        private static float Perlin(float x, float y)
        {
            EnsurePerm();
            int xi = ((int)Mathf.Floor(x)) & 255;
            int yi = ((int)Mathf.Floor(y)) & 255;
            float xf = x - Mathf.Floor(x);
            float yf = y - Mathf.Floor(y);
            float u = Fade(xf);
            float v = Fade(yf);
            int aa = _perm[_perm[xi] + yi];
            int ab = _perm[_perm[xi] + yi + 1];
            int ba = _perm[_perm[xi + 1] + yi];
            int bb = _perm[_perm[xi + 1] + yi + 1];
            float x1 = Mathf.Lerp(Grad(aa, xf, yf), Grad(ba, xf - 1f, yf), u);
            float x2 = Mathf.Lerp(Grad(ab, xf, yf - 1f), Grad(bb, xf - 1f, yf - 1f), u);
            return Mathf.Lerp(x1, x2, v);
        }

        /// <summary>Fractal Brownian Motion (fBm) via Perlin octaves.</summary>
        private static float FBM(float x, float y, int octaves, float persistence)
        {
            float total = 0f, amplitude = 1f, frequency = 1f, maxVal = 0f;
            for (int i = 0; i < octaves; i++)
            {
                total += Perlin(x * frequency, y * frequency) * amplitude;
                maxVal += amplitude;
                amplitude *= persistence;
                frequency *= 2f;
            }
            return total / maxVal;
        }

'''

# ---- Voronoi ----
_CS_VORONOI = r'''
        // =============================================================
        // Voronoi distance helpers
        // =============================================================

        /// <summary>
        /// Returns the distance to the nearest Voronoi cell edge (F2-F1).
        /// Useful for crack and splatter patterns.
        /// </summary>
        private static float VoronoiEdge(float x, float y, float cellScale)
        {
            x *= cellScale;
            y *= cellScale;
            int ix = (int)Mathf.Floor(x);
            int iy = (int)Mathf.Floor(y);
            float d1 = float.MaxValue;
            float d2 = float.MaxValue;

            for (int ox = -1; ox <= 1; ox++)
            {
                for (int oy = -1; oy <= 1; oy++)
                {
                    int cx = ix + ox;
                    int cy = iy + oy;
                    // Deterministic hash for cell point
                    float hx = Frac(Mathf.Sin(cx * 127.1f + cy * 311.7f) * 43758.5453f);
                    float hy = Frac(Mathf.Sin(cx * 269.5f + cy * 183.3f) * 43758.5453f);
                    float px = cx + hx;
                    float py = cy + hy;
                    float dist = (px - x) * (px - x) + (py - y) * (py - y);
                    if (dist < d1) { d2 = d1; d1 = dist; }
                    else if (dist < d2) { d2 = dist; }
                }
            }
            return Mathf.Sqrt(d2) - Mathf.Sqrt(d1);
        }

        /// <summary>Returns distance to the nearest Voronoi cell center (F1).</summary>
        private static float VoronoiF1(float x, float y, float cellScale)
        {
            x *= cellScale;
            y *= cellScale;
            int ix = (int)Mathf.Floor(x);
            int iy = (int)Mathf.Floor(y);
            float d1 = float.MaxValue;
            for (int ox = -1; ox <= 1; ox++)
            {
                for (int oy = -1; oy <= 1; oy++)
                {
                    int cx = ix + ox;
                    int cy = iy + oy;
                    float hx = Frac(Mathf.Sin(cx * 127.1f + cy * 311.7f) * 43758.5453f);
                    float hy = Frac(Mathf.Sin(cx * 269.5f + cy * 183.3f) * 43758.5453f);
                    float px = cx + hx;
                    float py = cy + hy;
                    float dist = (px - x) * (px - x) + (py - y) * (py - y);
                    if (dist < d1) d1 = dist;
                }
            }
            return Mathf.Sqrt(d1);
        }

        private static float Frac(float v) => v - Mathf.Floor(v);

        /// <summary>Seeded hash for deterministic random per pixel.</summary>
        private static float Hash(float x, float y)
        {
            return Frac(Mathf.Sin(x * 12.9898f + y * 78.233f) * 43758.5453f);
        }

'''

# ---- Texture generation methods ----
_CS_TEXTURES = r'''
        // =============================================================
        // 1. Smoke -- billowy cloud puff
        // =============================================================
        public static Texture2D GenerateSmoke(int size = 256)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size * 0.5f;
            float invHalf = 1f / half;

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = (x - half) * invHalf;
                    float ny = (y - half) * invHalf;
                    float r = Mathf.Sqrt(nx * nx + ny * ny);

                    // Gaussian radial falloff
                    float radial = Mathf.Exp(-r * r * 3.5f);

                    // 4-octave fBm for cloud shape
                    float n = FBM(x * 0.015f + 3.7f, y * 0.015f + 7.1f, 4, 0.5f);
                    n = n * 0.5f + 0.5f; // remap to [0,1]

                    // Warp coordinates with noise for organic edge
                    float warpX = nx + Perlin(x * 0.02f, y * 0.02f + 100f) * 0.15f;
                    float warpY = ny + Perlin(x * 0.02f + 100f, y * 0.02f) * 0.15f;
                    float rWarp = Mathf.Sqrt(warpX * warpX + warpY * warpY);
                    float warpRadial = Mathf.Exp(-rWarp * rWarp * 3.0f);

                    float alpha = Mathf.Clamp01(warpRadial * n * 1.4f) * radial;

                    // Slight density variation in luminance
                    float lum = 0.85f + n * 0.15f;
                    pixels[y * size + x] = new Color(lum * alpha, lum * alpha, lum * alpha, alpha);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 2. Spark -- stretched bright streak
        // =============================================================
        public static Texture2D GenerateSpark(int size = 64)
        {
            int w = size;
            int h = size;
            var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
            var pixels = new Color[w * h];
            float hw = w * 0.5f;
            float hh = h * 0.5f;

            for (int y = 0; y < h; y++)
            {
                for (int x = 0; x < w; x++)
                {
                    // Elongated ellipse: 4:1 ratio along X
                    float nx = (x - hw) / hw;
                    float ny = (y - hh) / hh;
                    float ellipse = nx * nx + ny * ny * 16f; // 4:1 stretch

                    // Sharp bright core with soft glow falloff
                    float core = Mathf.Max(0f, 1f - ellipse * 4f);
                    core = core * core; // sharpen core
                    float glow = Mathf.Exp(-ellipse * 2.5f);
                    float intensity = Mathf.Clamp01(core + glow * 0.6f);

                    float alpha = Mathf.Clamp01(glow);
                    // Premultiplied alpha
                    pixels[y * w + x] = new Color(intensity * alpha, intensity * alpha, intensity * alpha, alpha);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 3. Soft Glow -- pure radial gradient
        // =============================================================
        public static Texture2D GenerateSoftGlow(int size = 128)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size * 0.5f;

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = (x - half) / half;
                    float ny = (y - half) / half;
                    float r2 = nx * nx + ny * ny;

                    // Exponential falloff: brightest at dead center
                    float v = Mathf.Exp(-r2 * 4f);
                    pixels[y * size + x] = new Color(v, v, v, v);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 4. Magic Rune -- concentric rings + radial lines
        // =============================================================
        public static Texture2D GenerateMagicRune(int size = 256)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size * 0.5f;
            float invHalf = 1f / half;
            const int numSegments = 12;
            const float segAngle = 2f * Mathf.PI / numSegments;

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = (x - half) * invHalf;
                    float ny = (y - half) * invHalf;
                    float r = Mathf.Sqrt(nx * nx + ny * ny);
                    float angle = Mathf.Atan2(ny, nx);

                    // Noise-distorted radius for organic feel
                    float noiseOff = Perlin(x * 0.04f + 5f, y * 0.04f + 5f) * 0.06f;
                    float rn = r + noiseOff;

                    // Concentric rings at r=0.35, 0.55, 0.75, 0.9
                    float rings = 0f;
                    float[] ringRadii = { 0.35f, 0.55f, 0.75f, 0.9f };
                    float[] ringWidths = { 0.025f, 0.02f, 0.03f, 0.015f };
                    for (int i = 0; i < ringRadii.Length; i++)
                    {
                        float d = Mathf.Abs(rn - ringRadii[i]);
                        rings = Mathf.Max(rings, Mathf.Clamp01(1f - d / ringWidths[i]));
                    }

                    // Radial segment lines
                    float segVal = 0f;
                    if (r > 0.3f && r < 0.92f)
                    {
                        float angMod = Mathf.Repeat(angle + Mathf.PI, segAngle);
                        float angDist = Mathf.Min(angMod, segAngle - angMod);
                        float lineWidth = 0.035f;
                        segVal = Mathf.Clamp01(1f - angDist / lineWidth) * 0.8f;
                    }

                    // Inner arcane symbol: small rune marks at inner ring
                    float inner = 0f;
                    if (r < 0.3f)
                    {
                        // Small diamond/cross pattern at center
                        float ax = Mathf.Abs(nx);
                        float ay = Mathf.Abs(ny);
                        float cross = Mathf.Max(
                            Mathf.Clamp01(1f - ax / 0.015f) * Mathf.Clamp01(1f - ay / 0.18f),
                            Mathf.Clamp01(1f - ay / 0.015f) * Mathf.Clamp01(1f - ax / 0.18f)
                        );
                        float diamond = Mathf.Clamp01(1f - (ax + ay) / 0.2f) * 0.5f;
                        inner = Mathf.Max(cross * 0.9f, diamond);
                    }

                    // Small dots between segments on outer ring
                    float dots = 0f;
                    if (r > 0.4f && r < 0.6f)
                    {
                        float dotAngle = Mathf.Repeat(angle + Mathf.PI + segAngle * 0.5f, segAngle);
                        float dotAngDist = Mathf.Abs(dotAngle - segAngle * 0.5f);
                        if (dotAngDist < 0.08f)
                        {
                            float dotR = Mathf.Abs(rn - 0.5f);
                            dots = Mathf.Clamp01(1f - dotR / 0.02f) * Mathf.Clamp01(1f - dotAngDist / 0.08f);
                        }
                    }

                    float v = Mathf.Clamp01(Mathf.Max(Mathf.Max(rings, segVal), Mathf.Max(inner, dots)));

                    // Outer fade
                    float edgeFade = Mathf.Clamp01((1f - r) / 0.08f);
                    v *= edgeFade;

                    pixels[y * size + x] = new Color(v, v, v, v);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 5. Blood Splatter -- visceral irregular blob
        // =============================================================
        public static Texture2D GenerateBloodSplatter(int size = 256)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size * 0.5f;
            float invHalf = 1f / half;

            // Pre-generate scattered droplet positions (12-20 droplets)
            int dropCount = 16;
            float[] dropX = new float[dropCount];
            float[] dropY = new float[dropCount];
            float[] dropR = new float[dropCount];
            for (int i = 0; i < dropCount; i++)
            {
                float angle = Hash(i * 1.3f, i * 2.7f) * Mathf.PI * 2f;
                float dist = 0.3f + Hash(i * 3.1f, i * 0.7f) * 0.55f;
                dropX[i] = Mathf.Cos(angle) * dist;
                dropY[i] = Mathf.Sin(angle) * dist;
                dropR[i] = 0.03f + Hash(i * 5.3f, i * 1.9f) * 0.06f;
            }

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = (x - half) * invHalf;
                    float ny = (y - half) * invHalf;
                    float r = Mathf.Sqrt(nx * nx + ny * ny);

                    // Main splat: Voronoi-distorted blob
                    float vEdge = VoronoiEdge(nx * 2f + 10f, ny * 2f + 10f, 5f);
                    float vF1 = VoronoiF1(nx * 2f + 10f, ny * 2f + 10f, 4f);
                    float noise = FBM(x * 0.025f + 42f, y * 0.025f + 17f, 3, 0.6f) * 0.5f + 0.5f;

                    // Irregular blob radius modulated by noise + Voronoi
                    float blobRadius = 0.45f + noise * 0.2f + vEdge * 0.15f;
                    float mainBlob = Mathf.Clamp01((blobRadius - r) / 0.08f);

                    // Roughen edges with high-freq noise
                    float edgeNoise = FBM(x * 0.06f + 99f, y * 0.06f + 33f, 2, 0.7f) * 0.5f + 0.5f;
                    mainBlob *= Mathf.Clamp01(edgeNoise * 1.3f);

                    // Dark center, semi-transparent edges
                    float centerDarkness = Mathf.Clamp01(1f - r * 1.5f);
                    float lum = 0.5f + centerDarkness * 0.3f;

                    // Scattered droplets
                    float dropVal = 0f;
                    for (int d = 0; d < dropCount; d++)
                    {
                        float dx = nx - dropX[d];
                        float dy = ny - dropY[d];
                        float dr = Mathf.Sqrt(dx * dx + dy * dy);
                        float dBlob = Mathf.Clamp01((dropR[d] - dr) / 0.015f);
                        dropVal = Mathf.Max(dropVal, dBlob);
                    }

                    // Streaks radiating from center
                    float angle2 = Mathf.Atan2(ny, nx);
                    float streak = 0f;
                    for (int s = 0; s < 6; s++)
                    {
                        float sa = Hash(s * 7.1f, s * 3.3f) * Mathf.PI * 2f;
                        float angDiff = Mathf.Abs(Mathf.DeltaAngle(angle2 * Mathf.Rad2Deg, sa * Mathf.Rad2Deg)) / 180f;
                        float sLen = 0.5f + Hash(s * 2.1f, s * 9.7f) * 0.35f;
                        if (angDiff < 0.03f && r > 0.25f && r < sLen)
                        {
                            streak = Mathf.Max(streak, (1f - angDiff / 0.03f) * 0.7f * Mathf.Clamp01(1f - (r - 0.25f) / (sLen - 0.25f)));
                        }
                    }

                    float alpha = Mathf.Clamp01(Mathf.Max(Mathf.Max(mainBlob, dropVal), streak));
                    pixels[y * size + x] = new Color(lum * alpha, lum * alpha, lum * alpha, alpha);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 6. Lightning -- branching bolt
        // =============================================================
        public static Texture2D GenerateLightning(int size = 256)
        {
            // 64 wide, 256 tall by default (vertical bolt)
            int w = size / 4;
            int h = size;
            var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
            var pixels = new Color[w * h];

            // Clear to black/transparent
            for (int i = 0; i < pixels.Length; i++)
                pixels[i] = new Color(0, 0, 0, 0);

            float hw = w * 0.5f;

            // Random walk for main bolt
            DrawBolt(pixels, w, h, hw, 0f, hw, h, 3.5f, 1f, 0);

            // Apply glow pass (8px soft falloff)
            var glowed = new Color[w * h];
            int glowRadius = Mathf.Max(2, w / 8);
            for (int y = 0; y < h; y++)
            {
                for (int x = 0; x < w; x++)
                {
                    float maxA = pixels[y * w + x].a;
                    float glow = 0f;
                    for (int gy = -glowRadius; gy <= glowRadius; gy++)
                    {
                        for (int gx = -glowRadius; gx <= glowRadius; gx++)
                        {
                            int sx = x + gx;
                            int sy = y + gy;
                            if (sx >= 0 && sx < w && sy >= 0 && sy < h)
                            {
                                float src = pixels[sy * w + sx].a;
                                float dist = Mathf.Sqrt(gx * gx + gy * gy);
                                float falloff = Mathf.Exp(-dist * dist / (glowRadius * 0.7f));
                                glow = Mathf.Max(glow, src * falloff);
                            }
                        }
                    }
                    float combined = Mathf.Max(maxA, glow * 0.55f);
                    float bright = Mathf.Max(pixels[y * w + x].r, glow * 0.4f);
                    glowed[y * w + x] = new Color(bright, bright, bright, combined);
                }
            }

            tex.SetPixels(glowed);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        /// <summary>Recursive random-walk bolt drawer.</summary>
        private static void DrawBolt(Color[] pixels, int w, int h,
            float x0, float y0, float x1, float y1,
            float width, float alpha, int depth)
        {
            if (depth > 5) return;

            float dx = x1 - x0;
            float dy = y1 - y0;
            float len = Mathf.Sqrt(dx * dx + dy * dy);
            int steps = Mathf.Max(4, (int)(len * 0.5f));

            float prevX = x0, prevY = y0;
            float drift = 0f;

            for (int i = 0; i <= steps; i++)
            {
                float t = (float)i / steps;
                float cx = Mathf.Lerp(x0, x1, t);
                float cy = Mathf.Lerp(y0, y1, t);

                // Perpendicular jitter via random walk
                drift += (Hash(i * 13.7f + depth * 29f, t * 97f + depth * 53f) - 0.5f) * 4f;
                drift *= 0.92f; // dampen

                // Perpendicular direction
                float perpX = -dy / (len + 0.001f);
                cx += perpX * drift;

                // Draw fat pixel line from prev to current
                DrawThickLine(pixels, w, h, prevX, prevY, cx, cy, width, alpha);

                // Branch probability: 8% per step
                if (depth < 3 && Hash(i * 7.3f + depth * 41f, len) > 0.92f)
                {
                    float bAngle = (Hash(i * 3.1f, depth * 19f) - 0.5f) * 1.2f + Mathf.Atan2(dy, dx);
                    float bLen = len * (0.2f + Hash(i * 11f, depth * 7f) * 0.25f);
                    float bx1 = cx + Mathf.Cos(bAngle) * bLen * 0.5f;
                    float by1 = cy + Mathf.Sin(bAngle) * bLen;
                    DrawBolt(pixels, w, h, cx, cy, bx1, by1,
                        Mathf.Max(1f, width * 0.5f), alpha * 0.6f, depth + 1);
                }

                prevX = cx;
                prevY = cy;
            }
        }

        private static void DrawThickLine(Color[] pixels, int w, int h,
            float x0, float y0, float x1, float y1, float thickness, float alpha)
        {
            float dx = x1 - x0;
            float dy = y1 - y0;
            float len = Mathf.Sqrt(dx * dx + dy * dy);
            int steps = Mathf.Max(1, (int)(len * 2f));
            float halfT = thickness * 0.5f;

            for (int s = 0; s <= steps; s++)
            {
                float t = (float)s / Mathf.Max(1, steps);
                float px = Mathf.Lerp(x0, x1, t);
                float py = Mathf.Lerp(y0, y1, t);
                int ihalfT = (int)Mathf.Ceil(halfT) + 1;

                for (int oy = -ihalfT; oy <= ihalfT; oy++)
                {
                    for (int ox = -ihalfT; ox <= ihalfT; ox++)
                    {
                        int ix = (int)(px + ox);
                        int iy = (int)(py + oy);
                        if (ix < 0 || ix >= w || iy < 0 || iy >= h) continue;
                        float dist = Mathf.Sqrt(ox * ox + oy * oy);
                        float falloff = Mathf.Clamp01(1f - dist / (halfT + 0.5f));
                        float val = alpha * falloff;
                        int idx = iy * w + ix;
                        if (val > pixels[idx].a)
                            pixels[idx] = new Color(val, val, val, val);
                    }
                }
            }
        }

        // =============================================================
        // 7. Energy Orb -- swirling energy sphere
        // =============================================================
        public static Texture2D GenerateEnergyOrb(int size = 128)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size * 0.5f;
            float invHalf = 1f / half;

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = (x - half) * invHalf;
                    float ny = (y - half) * invHalf;
                    float r = Mathf.Sqrt(nx * nx + ny * ny);

                    // Swirl: rotate UV by distance from center
                    float swirlAmount = 3.0f;
                    float angle = Mathf.Atan2(ny, nx) + r * swirlAmount;
                    float sx = Mathf.Cos(angle) * r;
                    float sy = Mathf.Sin(angle) * r;

                    // Noise-distorted circle with swirl
                    float n = FBM(sx * 3f + 20f, sy * 3f + 20f, 3, 0.5f) * 0.5f + 0.5f;

                    // Bright core
                    float core = Mathf.Exp(-r * r * 12f);
                    // Medium ring
                    float ring = Mathf.Clamp01(1f - Mathf.Abs(r - 0.5f) / 0.15f) * 0.5f;
                    ring *= n;
                    // Outer void
                    float outerFade = Mathf.Clamp01((0.85f - r) / 0.15f);

                    float intensity = Mathf.Clamp01(core + ring * 0.7f + n * 0.3f * outerFade);
                    float alpha = Mathf.Clamp01((core + Mathf.Max(ring, n * 0.5f)) * outerFade + core);

                    pixels[y * size + x] = new Color(intensity * alpha, intensity * alpha, intensity * alpha, alpha);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 8. Distortion Normal -- normal map for heat haze
        // =============================================================
        public static Texture2D GenerateDistortionNormal(int size = 128)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size * 0.5f;
            float invHalf = 1f / half;
            float texelSize = 1f / size;

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = (x - half) * invHalf;
                    float ny = (y - half) * invHalf;
                    float r = Mathf.Sqrt(nx * nx + ny * ny);

                    // Radial falloff so distortion is strongest at center
                    float falloff = Mathf.Exp(-r * r * 2.5f);

                    // Compute normal from noise height via central difference
                    float scale = 4f;
                    float hL = FBM((x - 1) * texelSize * scale + 50f, y * texelSize * scale + 50f, 3, 0.5f);
                    float hR = FBM((x + 1) * texelSize * scale + 50f, y * texelSize * scale + 50f, 3, 0.5f);
                    float hD = FBM(x * texelSize * scale + 50f, (y - 1) * texelSize * scale + 50f, 3, 0.5f);
                    float hU = FBM(x * texelSize * scale + 50f, (y + 1) * texelSize * scale + 50f, 3, 0.5f);

                    // XY displacement encoded in RG, B=1 (pointing up)
                    float dX = (hL - hR) * falloff;
                    float dY = (hD - hU) * falloff;

                    // Pack [-1,1] into [0,1]
                    float rChan = dX * 0.5f + 0.5f;
                    float gChan = dY * 0.5f + 0.5f;
                    float bChan = 1f;

                    pixels[y * size + x] = new Color(rChan, gChan, bChan, falloff);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 9. Ground Crack -- Voronoi cell edges
        // =============================================================
        public static Texture2D GenerateGroundCrack(int size = 256)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size * 0.5f;
            float invHalf = 1f / half;

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = (x - half) * invHalf;
                    float ny = (y - half) * invHalf;
                    float r = Mathf.Sqrt(nx * nx + ny * ny);

                    // Large structural cracks
                    float largeCrack = VoronoiEdge(nx + 5f, ny + 5f, 4f);
                    float largeVal = Mathf.Clamp01(1f - largeCrack / 0.06f);

                    // Small detail cracks
                    float smallCrack = VoronoiEdge(nx * 2f + 15f, ny * 2f + 15f, 8f);
                    float smallVal = Mathf.Clamp01(1f - smallCrack / 0.04f) * 0.5f;

                    // Micro fractures
                    float microCrack = VoronoiEdge(nx * 4f + 30f, ny * 4f + 30f, 12f);
                    float microVal = Mathf.Clamp01(1f - microCrack / 0.03f) * 0.25f;

                    float combined = Mathf.Clamp01(largeVal + smallVal + microVal);

                    // Radial falloff from center (impact point)
                    float radial = Mathf.Clamp01(1f - r * 0.9f);
                    radial = radial * radial; // stronger at center
                    combined *= radial;

                    // Slight noise variation for organic feel
                    float n = FBM(x * 0.03f + 77f, y * 0.03f + 33f, 2, 0.5f) * 0.5f + 0.5f;
                    combined *= 0.7f + n * 0.3f;

                    // White cracks on black background
                    pixels[y * size + x] = new Color(combined, combined, combined, combined);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

        // =============================================================
        // 10. Dissolve Mask -- multi-octave Perlin noise
        // =============================================================
        public static Texture2D GenerateDissolveMask(int size = 256)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    // 5-octave fBm for rich noise pattern
                    float n = FBM(x * 0.012f + 123f, y * 0.012f + 456f, 5, 0.5f);
                    // Remap from [-1,1] to [0,1]
                    n = n * 0.5f + 0.5f;
                    n = Mathf.Clamp01(n);
                    pixels[y * size + x] = new Color(n, n, n, 1f);
                }
            }
            tex.SetPixels(pixels);
            tex.Apply(false, false);
            tex.wrapMode = TextureWrapMode.Repeat;
            tex.filterMode = FilterMode.Bilinear;
            return tex;
        }

'''

# ---- Material factory methods ----
_CS_MATERIALS = r'''
        // =============================================================
        // Material factory methods
        // =============================================================

        /// <summary>
        /// Create a cached additive-blend URP particle material.
        /// Best for sparks, glows, lightning, energy.
        /// </summary>
        public static Material CreateAdditiveMaterial(Color color, string textureType = "soft_glow")
        {
            int key = HashCode(color, textureType, "additive");
            if (_matCache.TryGetValue(key, out var cached) && cached != null)
                return cached;

            // URP Particles/Unlit shader
            Shader shader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
            if (shader == null)
                shader = Shader.Find("Particles/Standard Unlit");
            if (shader == null)
            {
                Debug.LogWarning("[VBProceduralParticleTextures] Could not find URP particle shader, falling back to default.");
                shader = Shader.Find("Sprites/Default");
            }

            var mat = new Material(shader);
            mat.name = $"VB_Additive_{textureType}";

            // Set blend mode to Additive
            mat.SetFloat("_Surface", 1f);  // 0=Opaque, 1=Transparent
            mat.SetFloat("_Blend", 1f);    // 0=Alpha, 1=Additive, 2=Multiply
            mat.SetFloat("_SrcBlend", (float)UnityEngine.Rendering.BlendMode.SrcAlpha);
            mat.SetFloat("_DstBlend", (float)UnityEngine.Rendering.BlendMode.One);
            mat.SetFloat("_ZWrite", 0f);
            mat.SetFloat("_ColorMode", 1f); // Multiply
            mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
            mat.EnableKeyword("_BLENDMODE_ADD");
            mat.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;

            mat.SetTexture("_BaseMap", GetTexture(textureType));
            mat.SetColor("_BaseColor", color);

            _matCache[key] = mat;
            return mat;
        }

        /// <summary>
        /// Create a cached alpha-blend URP particle material.
        /// Best for smoke, blood, cracks, runes.
        /// </summary>
        public static Material CreateAlphaBlendMaterial(Color color, string textureType = "smoke")
        {
            int key = HashCode(color, textureType, "alpha");
            if (_matCache.TryGetValue(key, out var cached) && cached != null)
                return cached;

            Shader shader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
            if (shader == null)
                shader = Shader.Find("Particles/Standard Unlit");
            if (shader == null)
                shader = Shader.Find("Sprites/Default");

            var mat = new Material(shader);
            mat.name = $"VB_Alpha_{textureType}";

            // Set blend mode to Alpha Blend
            mat.SetFloat("_Surface", 1f);
            mat.SetFloat("_Blend", 0f);
            mat.SetFloat("_SrcBlend", (float)UnityEngine.Rendering.BlendMode.SrcAlpha);
            mat.SetFloat("_DstBlend", (float)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
            mat.SetFloat("_ZWrite", 0f);
            mat.SetFloat("_ColorMode", 1f);
            mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
            mat.EnableKeyword("_BLENDMODE_ALPHA");
            mat.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;

            mat.SetTexture("_BaseMap", GetTexture(textureType));
            mat.SetColor("_BaseColor", color);

            _matCache[key] = mat;
            return mat;
        }

        /// <summary>Deterministic hash for material cache key.</summary>
        private static int HashCode(Color c, string texType, string blendMode)
        {
            unchecked
            {
                int h = 17;
                h = h * 31 + (((int)(c.r * 255f)) << 24);
                h = h * 31 + (((int)(c.g * 255f)) << 16);
                h = h * 31 + (((int)(c.b * 255f)) << 8);
                h = h * 31 + ((int)(c.a * 255f));
                h = h * 31 + texType.GetHashCode();
                h = h * 31 + blendMode.GetHashCode();
                return h;
            }
        }

'''

_CS_FOOTER = r'''
    }  // class VBProceduralParticleTextures
}  // namespace VeilBreakers.VFX
'''
