"""World streaming C# template generators for Unity map pipeline.

Provides:
    generate_map_streaming_script   -- C# editor script for Addressable groups,
                                       static flags, and occlusion bake
    generate_occlusion_zone_spec    -- Pure Python portal/zone spec for
                                       interior ↔ exterior streaming

Phase 37 -- PIPE-02: Map streaming setup from Blender scene hierarchy.
"""

from __future__ import annotations

from typing import Any

from ._cs_sanitize import sanitize_cs_identifier


# ---------------------------------------------------------------------------
# generate_map_streaming_script
# ---------------------------------------------------------------------------


def generate_map_streaming_script(
    scene_hierarchy: dict,
    namespace: str = "",
) -> str:
    """Generate a C# editor script that sets up Addressable groups, static
    flags, and occlusion culling for a map exported from Blender.

    Parameters
    ----------
    scene_hierarchy : dict
        The scene hierarchy dict produced by ``emit_scene_hierarchy`` or loaded
        from the ``scene_hierarchy.json`` file written by ``generate_map_package``.
        Must contain ``map_name`` and ``objects`` keys.
    namespace : str, optional
        C# namespace suffix appended to ``VeilBreakers.World``.

    Returns
    -------
    str
        Complete C# source for an editor script.
    """
    map_name = scene_hierarchy.get("map_name", "Map")
    objects = scene_hierarchy.get("objects", [])

    # Group objects by district for Addressable group assignment
    groups: dict[str, list[str]] = {}
    for obj in objects:
        district = obj.get("district", "") or "default"
        groups.setdefault(district, []).append(obj["name"])

    ns = f"VeilBreakers.World.{namespace}" if namespace else "VeilBreakers.World"

    # Per-group configuration methods
    group_entries: list[str] = []
    for district, obj_names in groups.items():
        escaped_district = sanitize_cs_identifier(district) or "Default"
        asset_paths_list = ", ".join(f'"{n}"' for n in obj_names)
        group_entries.append(f"""
        private static void Configure_{escaped_district}_Group()
        {{
            var group = CreateOrGetGroup("{map_name}_{escaped_district}");
            foreach (var path in new[] {{ {asset_paths_list} }})
            {{
                var guid = AssetDatabase.AssetPathToGUID("Assets/Maps/{map_name}/" + path + ".fbx");
                if (!string.IsNullOrEmpty(guid))
                    AddToGroup(group, guid);
            }}
        }}""")

    group_calls = "\n            ".join(
        f"Configure_{sanitize_cs_identifier(d) or 'Default'}_Group();"
        for d in groups
    )

    # Static flags for buildings
    static_flags_code = ""
    _BUILDING_DISTRICTS = {"town", "castle", "dungeon", "ruins", "building"}
    for obj in objects:
        obj_district = obj.get("district", "")
        if obj_district in _BUILDING_DISTRICTS:
            obj_name = obj["name"]
            static_flags_code += f"""
            // Set static flags for building: {obj_name}
            var buildingObj_{sanitize_cs_identifier(obj_name)} = GameObject.Find("{obj_name}");
            if (buildingObj_{sanitize_cs_identifier(obj_name)} != null)
                GameObjectUtility.SetStaticEditorFlags(buildingObj_{sanitize_cs_identifier(obj_name)}, StaticEditorFlags.BatchingStatic | StaticEditorFlags.OccluderStatic | StaticEditorFlags.OccludeeStatic);
"""

    safe_map_name = sanitize_cs_identifier(map_name)

    return f"""// Auto-generated map streaming setup for {map_name}
// Generated by VeilBreakers MCP Pipeline (Phase 37 -- PIPE-02)

using UnityEditor;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;

namespace {ns}
{{
    public static class MapStreaming_{safe_map_name}
    {{
        [MenuItem("VeilBreakers/World/Setup Map Streaming - {map_name}")]
        public static void Execute()
        {{
            Debug.Log("[MapStreaming] Setting up Addressable groups for {map_name}...");
            {group_calls}
{static_flags_code}
            // Bake occlusion culling
            Debug.Log("[MapStreaming] Baking occlusion culling...");
            StaticOcclusionCulling.Compute();
            Debug.Log("[MapStreaming] Setup complete for {map_name}");
        }}

        private static AddressableAssetGroup CreateOrGetGroup(string groupName)
        {{
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null) return null;
            var group = settings.FindGroup(groupName);
            if (group == null)
                group = settings.CreateGroup(groupName, false, false, true, null, typeof(AddressableAssetGroupSchema));
            return group;
        }}

        private static void AddToGroup(AddressableAssetGroup group, string guid)
        {{
            if (group == null || string.IsNullOrEmpty(guid)) return;
            var settings = group.Settings;
            var entry = settings.CreateOrMoveEntry(guid, group);
            entry.SetAddress(AssetDatabase.GUIDToAssetPath(guid));
        }}
{"".join(group_entries)}
    }}
}}
"""


# ---------------------------------------------------------------------------
# generate_occlusion_zone_spec
# ---------------------------------------------------------------------------


def generate_occlusion_zone_spec(
    door: dict,
    room_bounds: dict,
) -> dict:
    """Generate a portal-based occlusion zone specification.

    Creates an occlusion zone around a door that acts as a portal between
    two spaces.  The zone is inset slightly from the room bounds so it
    sits just inside the doorframe.

    Parameters
    ----------
    door : dict
        Door descriptor with keys: ``position`` (3-list), ``width`` (float),
        ``height`` (float), ``facing`` (str: north/south/east/west).
    room_bounds : dict
        Room bounds with ``min`` (3-list) and ``max`` (3-list) corners.

    Returns
    -------
    dict
        Occlusion zone spec with ``portal_center``, ``portal_extents``,
        ``zone_min``, ``zone_max``, ``facing``, ``door_width``,
        ``door_height`` keys.
    """
    pos = door.get("position", [0, 0, 0])
    width = door.get("width", 1.2)
    height = door.get("height", 2.4)
    facing = door.get("facing", "north")

    # Portal center is at door position
    portal_center = list(pos)

    # Portal extents depend on facing
    if facing in ("north", "south"):
        portal_extents = [width / 2.0, height / 2.0, 0.15]
    else:
        portal_extents = [0.15, height / 2.0, width / 2.0]

    # Zone is room bounds inset by a small margin
    _INSET = 0.1
    r_min = room_bounds.get("min", [0, 0, 0])
    r_max = room_bounds.get("max", [10, 4, 10])

    zone_min = [r_min[0] + _INSET, r_min[1], r_min[2] + _INSET]
    zone_max = [r_max[0] - _INSET, r_max[1], r_max[2] - _INSET]

    return {
        "portal_center": portal_center,
        "portal_extents": portal_extents,
        "zone_min": zone_min,
        "zone_max": zone_max,
        "facing": facing,
        "door_width": width,
        "door_height": height,
    }
